// GENERATED by tools/build-reference.js from tools/reference-src/python.js. Do not edit by hand.
(function (root) {
  'use strict';
  const LP = (root.LP = root.LP || {});
  (LP.reference = LP.reference || {}).python = [
 {
  "name": "abs",
  "sig": "abs(x)",
  "desc": "Absolute value of a number.",
  "group": "Built-in functions",
  "ex": "print(abs(-7.5))",
  "out": "7.5",
  "lesson": "py-variables"
 },
 {
  "name": "aiter",
  "sig": "aiter(async_iterable)",
  "desc": "Return an asynchronous iterator (used with async for).",
  "group": "Built-in functions",
  "ex": "import asyncio\nasync def gen():\n    yield 1\nasync def main():\n    it = aiter(gen())\n    print(await anext(it))\nasyncio.run(main())",
  "out": "1",
  "lesson": "py-functions"
 },
 {
  "name": "all",
  "sig": "all(iterable)",
  "desc": "True if every element is truthy (True for an empty iterable).",
  "group": "Built-in functions",
  "ex": "print(all([1, 2, 3]), all([1, 0]), all([]))",
  "out": "True False True",
  "lesson": "py-loops"
 },
 {
  "name": "anext",
  "sig": "anext(async_iterator)",
  "desc": "Get the next item from an async iterator (awaitable).",
  "group": "Built-in functions",
  "ex": "import asyncio\nasync def gen():\n    yield \"a\"\nasync def main():\n    print(await anext(gen()))\nasyncio.run(main())",
  "out": "a",
  "lesson": "py-functions"
 },
 {
  "name": "any",
  "sig": "any(iterable)",
  "desc": "True if at least one element is truthy.",
  "group": "Built-in functions",
  "ex": "print(any([0, 0, 3]), any([]))",
  "out": "True False",
  "lesson": "py-loops"
 },
 {
  "name": "ascii",
  "sig": "ascii(obj)",
  "desc": "Like repr() but escapes non-ASCII characters.",
  "group": "Built-in functions",
  "ex": "print(ascii(\"café\"))",
  "out": "'caf\\xe9'",
  "lesson": "py-strings"
 },
 {
  "name": "bin",
  "sig": "bin(n)",
  "desc": "Binary string of an integer.",
  "group": "Built-in functions",
  "ex": "print(bin(10))",
  "out": "0b1010",
  "lesson": "py-variables"
 },
 {
  "name": "bool",
  "sig": "bool(x)",
  "desc": "Convert to True/False using truthiness rules.",
  "group": "Built-in functions",
  "ex": "print(bool(0), bool(\"a\"), bool([]))",
  "out": "False True False",
  "lesson": "py-conditions"
 },
 {
  "name": "breakpoint",
  "sig": "breakpoint()",
  "desc": "Drop into the debugger at this line (interactive; not for scripts under test).",
  "group": "Built-in functions",
  "ex": "print(\"use breakpoint() in a real terminal to debug\")",
  "out": "use breakpoint() in a real terminal to debug",
  "lesson": "py-testing"
 },
 {
  "name": "bytearray",
  "sig": "bytearray(source)",
  "desc": "A mutable sequence of bytes.",
  "group": "Built-in functions",
  "ex": "b = bytearray(b\"abc\")\nb[0] = 65\nprint(b)",
  "out": "bytearray(b'Abc')",
  "lesson": "py-files"
 },
 {
  "name": "bytes",
  "sig": "bytes(source)",
  "desc": "An immutable sequence of bytes.",
  "group": "Built-in functions",
  "ex": "print(bytes([72, 105]), \"Hi\".encode())",
  "out": "b'Hi' b'Hi'",
  "lesson": "py-files"
 },
 {
  "name": "callable",
  "sig": "callable(obj)",
  "desc": "True if the object can be called like a function.",
  "group": "Built-in functions",
  "ex": "print(callable(len), callable(5))",
  "out": "True False",
  "lesson": "py-functions"
 },
 {
  "name": "chr",
  "sig": "chr(i)",
  "desc": "Character for a Unicode code point.",
  "group": "Built-in functions",
  "ex": "print(chr(97), chr(8364))",
  "out": "a €",
  "lesson": "py-strings"
 },
 {
  "name": "classmethod",
  "sig": "@classmethod",
  "desc": "Decorator: method receives the class (cls) instead of an instance.",
  "group": "Built-in functions",
  "ex": "class A:\n    @classmethod\n    def make(cls):\n        return cls()\nprint(type(A.make()).__name__)",
  "out": "A",
  "lesson": "py-classes"
 },
 {
  "name": "compile",
  "sig": "compile(source, filename, mode)",
  "desc": "Compile source text into a code object.",
  "group": "Built-in functions",
  "ex": "code = compile(\"1 + 2\", \"<s>\", \"eval\")\nprint(eval(code))",
  "out": "3",
  "lesson": "py-functions"
 },
 {
  "name": "complex",
  "sig": "complex(real, imag)",
  "desc": "A complex number.",
  "group": "Built-in functions",
  "ex": "print(complex(1, 2) * 2)",
  "out": "(2+4j)",
  "lesson": "py-variables"
 },
 {
  "name": "delattr",
  "sig": "delattr(obj, name)",
  "desc": "Delete an attribute from an object.",
  "group": "Built-in functions",
  "ex": "class A:\n    x = 1\na = A()\na.y = 2\ndelattr(a, \"y\")\nprint(hasattr(a, \"y\"))",
  "out": "False",
  "lesson": "py-classes"
 },
 {
  "name": "dict",
  "sig": "dict(**kwargs)",
  "desc": "Create a dictionary.",
  "group": "Built-in functions",
  "ex": "print(dict(a=1, b=2), dict([(\"x\", 1)]))",
  "out": "{'a': 1, 'b': 2} {'x': 1}",
  "lesson": "py-dicts"
 },
 {
  "name": "dir",
  "sig": "dir(obj)",
  "desc": "List the names an object defines.",
  "group": "Built-in functions",
  "ex": "print([n for n in dir(\"\") if n.startswith(\"up\")])",
  "out": "['upper']",
  "lesson": "py-classes"
 },
 {
  "name": "divmod",
  "sig": "divmod(a, b)",
  "desc": "Quotient and remainder together.",
  "group": "Built-in functions",
  "ex": "print(divmod(17, 5))",
  "out": "(3, 2)",
  "lesson": "py-variables"
 },
 {
  "name": "enumerate",
  "sig": "enumerate(iterable, start=0)",
  "desc": "Pair each item with a counter.",
  "group": "Built-in functions",
  "ex": "print(list(enumerate(\"ab\", start=1)))",
  "out": "[(1, 'a'), (2, 'b')]",
  "lesson": "py-loops"
 },
 {
  "name": "eval",
  "sig": "eval(expr)",
  "desc": "Evaluate a Python expression given as a string.",
  "group": "Built-in functions",
  "ex": "print(eval(\"2 ** 8\"))",
  "out": "256",
  "lesson": "py-functions"
 },
 {
  "name": "exec",
  "sig": "exec(code)",
  "desc": "Execute Python statements given as a string.",
  "group": "Built-in functions",
  "ex": "exec(\"x = 5\\nprint(x * 2)\")",
  "out": "10",
  "lesson": "py-functions"
 },
 {
  "name": "filter",
  "sig": "filter(func, iterable)",
  "desc": "Keep items for which func is true.",
  "group": "Built-in functions",
  "ex": "print(list(filter(lambda n: n % 2, range(8))))",
  "out": "[1, 3, 5, 7]",
  "lesson": "py-functions"
 },
 {
  "name": "float",
  "sig": "float(x)",
  "desc": "Convert to a floating-point number.",
  "group": "Built-in functions",
  "ex": "print(float(\"3.5\"), float(2))",
  "out": "3.5 2.0",
  "lesson": "py-variables"
 },
 {
  "name": "format",
  "sig": "format(value, spec)",
  "desc": "Format a value with a format spec.",
  "group": "Built-in functions",
  "ex": "print(format(3.14159, \".2f\"), format(255, \"x\"))",
  "out": "3.14 ff",
  "lesson": "py-strings"
 },
 {
  "name": "frozenset",
  "sig": "frozenset(iterable)",
  "desc": "An immutable set.",
  "group": "Built-in functions",
  "ex": "print(frozenset([1, 2, 2, 3]) == frozenset({1, 2, 3}))",
  "out": "True",
  "lesson": "py-lists"
 },
 {
  "name": "getattr",
  "sig": "getattr(obj, name, default)",
  "desc": "Read an attribute by name.",
  "group": "Built-in functions",
  "ex": "class A:\n    x = 5\nprint(getattr(A, \"x\"), getattr(A, \"nope\", \"default\"))",
  "out": "5 default",
  "lesson": "py-classes"
 },
 {
  "name": "globals",
  "sig": "globals()",
  "desc": "Dictionary of the module-level names.",
  "group": "Built-in functions",
  "ex": "y = 3\nprint(globals()[\"y\"])",
  "out": "3",
  "lesson": "py-functions"
 },
 {
  "name": "hasattr",
  "sig": "hasattr(obj, name)",
  "desc": "True if the object has that attribute.",
  "group": "Built-in functions",
  "ex": "print(hasattr(\"abc\", \"upper\"), hasattr(5, \"upper\"))",
  "out": "True False",
  "lesson": "py-classes"
 },
 {
  "name": "hash",
  "sig": "hash(obj)",
  "desc": "Integer hash of a hashable object.",
  "group": "Built-in functions",
  "ex": "print(hash(5), hash(\"a\") == hash(\"a\"))",
  "out": "5 True",
  "lesson": "py-dicts"
 },
 {
  "name": "help",
  "sig": "help(obj)",
  "desc": "Show documentation for an object (interactive).",
  "group": "Built-in functions",
  "ex": "print(len.__doc__.splitlines()[0])",
  "out": "Return the number of items in a container.",
  "lesson": "py-functions"
 },
 {
  "name": "hex",
  "sig": "hex(n)",
  "desc": "Hexadecimal string of an integer.",
  "group": "Built-in functions",
  "ex": "print(hex(255))",
  "out": "0xff",
  "lesson": "py-variables"
 },
 {
  "name": "id",
  "sig": "id(obj)",
  "desc": "Identity number of an object (unique while it lives).",
  "group": "Built-in functions",
  "ex": "a = [1]\nb = a\nprint(id(a) == id(b), id(a) == id([1]))",
  "out": "True False",
  "lesson": "py-lists"
 },
 {
  "name": "input",
  "sig": "input(prompt)",
  "desc": "Read a line from the user as text.",
  "group": "Built-in functions",
  "ex": "import io, sys\nsys.stdin = io.StringIO(\"Ada\\n\")\nprint(\"Hi,\", input(\"name? \"))",
  "out": "name? Hi, Ada",
  "lesson": "py-hello"
 },
 {
  "name": "int",
  "sig": "int(x, base=10)",
  "desc": "Convert to an integer.",
  "group": "Built-in functions",
  "ex": "print(int(\"42\"), int(3.9), int(\"ff\", 16))",
  "out": "42 3 255",
  "lesson": "py-variables"
 },
 {
  "name": "isinstance",
  "sig": "isinstance(obj, cls)",
  "desc": "True if obj is an instance of cls (or a subclass).",
  "group": "Built-in functions",
  "ex": "print(isinstance(5, int), isinstance(True, int), isinstance(\"a\", (int, float)))",
  "out": "True True False",
  "lesson": "py-inheritance"
 },
 {
  "name": "issubclass",
  "sig": "issubclass(cls, parent)",
  "desc": "True if cls inherits from parent.",
  "group": "Built-in functions",
  "ex": "print(issubclass(bool, int), issubclass(int, str))",
  "out": "True False",
  "lesson": "py-inheritance"
 },
 {
  "name": "iter",
  "sig": "iter(iterable)",
  "desc": "Get an iterator from an iterable.",
  "group": "Built-in functions",
  "ex": "it = iter([1, 2])\nprint(next(it), next(it))",
  "out": "1 2",
  "lesson": "py-loops"
 },
 {
  "name": "len",
  "sig": "len(obj)",
  "desc": "Number of items.",
  "group": "Built-in functions",
  "ex": "print(len(\"hello\"), len([1, 2, 3]), len({}))",
  "out": "5 3 0",
  "lesson": "py-lists"
 },
 {
  "name": "list",
  "sig": "list(iterable)",
  "desc": "Create a list.",
  "group": "Built-in functions",
  "ex": "print(list(\"abc\"), list(range(3)))",
  "out": "['a', 'b', 'c'] [0, 1, 2]",
  "lesson": "py-lists"
 },
 {
  "name": "locals",
  "sig": "locals()",
  "desc": "Dictionary of the local names.",
  "group": "Built-in functions",
  "ex": "def f(a):\n    b = 2\n    return sorted(locals())\nprint(f(1))",
  "out": "['a', 'b']",
  "lesson": "py-functions"
 },
 {
  "name": "map",
  "sig": "map(func, *iterables)",
  "desc": "Apply func to each item.",
  "group": "Built-in functions",
  "ex": "print(list(map(str.upper, [\"a\", \"b\"])), list(map(pow, [2, 3], [3, 2])))",
  "out": "['A', 'B'] [8, 9]",
  "lesson": "py-functions"
 },
 {
  "name": "max",
  "sig": "max(iterable, key=None, default=...)",
  "desc": "Largest item.",
  "group": "Built-in functions",
  "ex": "print(max([3, 9, 2]), max([\"aa\", \"b\"], key=len))",
  "out": "9 aa",
  "lesson": "py-lists"
 },
 {
  "name": "memoryview",
  "sig": "memoryview(obj)",
  "desc": "View over binary data without copying.",
  "group": "Built-in functions",
  "ex": "m = memoryview(b\"abc\")\nprint(m[0], bytes(m[1:]))",
  "out": "97 b'bc'",
  "lesson": "py-functions"
 },
 {
  "name": "min",
  "sig": "min(iterable, key=None, default=...)",
  "desc": "Smallest item.",
  "group": "Built-in functions",
  "ex": "print(min([3, 9, 2]), min([], default=0))",
  "out": "2 0",
  "lesson": "py-lists"
 },
 {
  "name": "next",
  "sig": "next(iterator, default)",
  "desc": "Next item of an iterator.",
  "group": "Built-in functions",
  "ex": "it = iter(\"a\")\nprint(next(it), next(it, \"done\"))",
  "out": "a done",
  "lesson": "py-loops"
 },
 {
  "name": "object",
  "sig": "object()",
  "desc": "Base class of every class.",
  "group": "Built-in functions",
  "ex": "print(isinstance(5, object), object.__name__)",
  "out": "True object",
  "lesson": "py-inheritance"
 },
 {
  "name": "oct",
  "sig": "oct(n)",
  "desc": "Octal string of an integer.",
  "group": "Built-in functions",
  "ex": "print(oct(8))",
  "out": "0o10",
  "lesson": "py-variables"
 },
 {
  "name": "open",
  "sig": "open(path, mode=\"r\")",
  "desc": "Open a file (use with for automatic closing).",
  "group": "Built-in functions",
  "ex": "with open(\"hello.txt\", \"w\") as f:\n    f.write(\"hi\")\nwith open(\"hello.txt\") as f:\n    print(f.read())",
  "out": "hi",
  "lesson": "py-files"
 },
 {
  "name": "ord",
  "sig": "ord(ch)",
  "desc": "Code point of a character.",
  "group": "Built-in functions",
  "ex": "print(ord(\"a\"))",
  "out": "97",
  "lesson": "py-strings"
 },
 {
  "name": "pow",
  "sig": "pow(base, exp, mod=None)",
  "desc": "Power, optionally modulo.",
  "group": "Built-in functions",
  "ex": "print(pow(2, 10), pow(2, 10, 1000))",
  "out": "1024 24",
  "lesson": "py-variables"
 },
 {
  "name": "print",
  "sig": "print(*values, sep=\" \", end=\"\\n\")",
  "desc": "Write values to the output.",
  "group": "Built-in functions",
  "ex": "print(\"a\", \"b\", sep=\"-\", end=\"!\\n\")",
  "out": "a-b!",
  "lesson": "py-hello"
 },
 {
  "name": "property",
  "sig": "@property",
  "desc": "Decorator: access a method like an attribute.",
  "group": "Built-in functions",
  "ex": "class C:\n    @property\n    def area(self):\n        return 6\nprint(C().area)",
  "out": "6",
  "lesson": "py-classes"
 },
 {
  "name": "range",
  "sig": "range(start, stop, step)",
  "desc": "A lazy sequence of integers.",
  "group": "Built-in functions",
  "ex": "print(list(range(2, 10, 3)), len(range(100)))",
  "out": "[2, 5, 8] 100",
  "lesson": "py-loops"
 },
 {
  "name": "repr",
  "sig": "repr(obj)",
  "desc": "Developer-friendly text for an object.",
  "group": "Built-in functions",
  "ex": "print(repr(\"hi\"), repr([1, \"a\"]))",
  "out": "'hi' [1, 'a']",
  "lesson": "py-strings"
 },
 {
  "name": "reversed",
  "sig": "reversed(seq)",
  "desc": "Iterate in reverse.",
  "group": "Built-in functions",
  "ex": "print(list(reversed([1, 2, 3])))",
  "out": "[3, 2, 1]",
  "lesson": "py-lists"
 },
 {
  "name": "round",
  "sig": "round(x, ndigits)",
  "desc": "Round (ties go to the even number).",
  "group": "Built-in functions",
  "ex": "print(round(2.5), round(3.5), round(3.14159, 2))",
  "out": "2 4 3.14",
  "lesson": "py-variables"
 },
 {
  "name": "set",
  "sig": "set(iterable)",
  "desc": "An unordered collection of unique items.",
  "group": "Built-in functions",
  "ex": "print(sorted(set([3, 1, 3, 2])))",
  "out": "[1, 2, 3]",
  "lesson": "py-lists"
 },
 {
  "name": "setattr",
  "sig": "setattr(obj, name, value)",
  "desc": "Set an attribute by name.",
  "group": "Built-in functions",
  "ex": "class A: pass\na = A()\nsetattr(a, \"x\", 9)\nprint(a.x)",
  "out": "9",
  "lesson": "py-classes"
 },
 {
  "name": "slice",
  "sig": "slice(start, stop, step)",
  "desc": "A slice object (what a[1:3] builds).",
  "group": "Built-in functions",
  "ex": "s = slice(1, 4)\nprint([0, 1, 2, 3, 4][s])",
  "out": "[1, 2, 3]",
  "lesson": "py-lists"
 },
 {
  "name": "sorted",
  "sig": "sorted(iterable, key=None, reverse=False)",
  "desc": "A new sorted list.",
  "group": "Built-in functions",
  "ex": "print(sorted([\"b\", \"A\", \"c\"], key=str.lower, reverse=True))",
  "out": "['c', 'b', 'A']",
  "lesson": "py-functions"
 },
 {
  "name": "staticmethod",
  "sig": "@staticmethod",
  "desc": "Decorator: method that needs neither self nor cls.",
  "group": "Built-in functions",
  "ex": "class M:\n    @staticmethod\n    def add(a, b):\n        return a + b\nprint(M.add(2, 3))",
  "out": "5",
  "lesson": "py-classes"
 },
 {
  "name": "str",
  "sig": "str(obj)",
  "desc": "Convert to text.",
  "group": "Built-in functions",
  "ex": "print(str(12) + \"!\", str([1, 2]))",
  "out": "12! [1, 2]",
  "lesson": "py-strings"
 },
 {
  "name": "sum",
  "sig": "sum(iterable, start=0)",
  "desc": "Add up the items.",
  "group": "Built-in functions",
  "ex": "print(sum([1, 2, 3]), sum([[1], [2]], []))",
  "out": "6 [1, 2]",
  "lesson": "py-lists"
 },
 {
  "name": "super",
  "sig": "super()",
  "desc": "Access the parent class from a subclass.",
  "group": "Built-in functions",
  "ex": "class A:\n    def hi(self):\n        return \"A\"\nclass B(A):\n    def hi(self):\n        return super().hi() + \"B\"\nprint(B().hi())",
  "out": "AB",
  "lesson": "py-inheritance"
 },
 {
  "name": "tuple",
  "sig": "tuple(iterable)",
  "desc": "An immutable sequence.",
  "group": "Built-in functions",
  "ex": "print(tuple([1, 2, 3]), (1,) + (2,))",
  "out": "(1, 2, 3) (1, 2)",
  "lesson": "py-lists"
 },
 {
  "name": "type",
  "sig": "type(obj)",
  "desc": "The class of an object (or, with 3 args, create a class).",
  "group": "Built-in functions",
  "ex": "print(type(5).__name__, type(\"a\") is str)",
  "out": "int True",
  "lesson": "py-classes"
 },
 {
  "name": "vars",
  "sig": "vars(obj)",
  "desc": "The __dict__ of an object.",
  "group": "Built-in functions",
  "ex": "class A:\n    def __init__(self):\n        self.x = 1\nprint(vars(A()))",
  "out": "{'x': 1}",
  "lesson": "py-classes"
 },
 {
  "name": "zip",
  "sig": "zip(*iterables)",
  "desc": "Pair up items from several iterables.",
  "group": "Built-in functions",
  "ex": "print(list(zip(\"ab\", [1, 2, 3])))",
  "out": "[('a', 1), ('b', 2)]",
  "lesson": "py-functions"
 },
 {
  "name": "__import__",
  "sig": "__import__(name)",
  "desc": "The function behind import (use import instead).",
  "group": "Built-in functions",
  "ex": "print(__import__(\"math\").pi)",
  "out": "3.141592653589793",
  "lesson": "py-stdlib"
 },
 {
  "name": "True",
  "sig": "True",
  "desc": "Boolean true (equals 1).",
  "group": "Built-in functions",
  "ex": "print(True + True)",
  "out": "2",
  "lesson": "py-conditions"
 },
 {
  "name": "False",
  "sig": "False",
  "desc": "Boolean false (equals 0).",
  "group": "Built-in functions",
  "ex": "print(False == 0)",
  "out": "True",
  "lesson": "py-conditions"
 },
 {
  "name": "None",
  "sig": "None",
  "desc": "The \"nothing\" value; test with is None.",
  "group": "Built-in functions",
  "ex": "x = None\nprint(x is None)",
  "out": "True",
  "lesson": "py-functions"
 },
 {
  "name": "Ellipsis",
  "sig": "... / Ellipsis",
  "desc": "A placeholder object, often used in slices and stubs.",
  "group": "Built-in functions",
  "ex": "print(... is Ellipsis)",
  "out": "True",
  "lesson": "py-functions"
 },
 {
  "name": "NotImplemented",
  "sig": "NotImplemented",
  "desc": "Return from a dunder method to say \"I do not handle this operand\".",
  "group": "Built-in functions",
  "ex": "class A:\n    def __eq__(self, o):\n        return NotImplemented\nprint(A() == 1)",
  "out": "False",
  "lesson": "py-inheritance"
 },
 {
  "name": "str.capitalize",
  "sig": "s.capitalize()",
  "desc": "First letter upper, rest lower.",
  "group": "str methods",
  "ex": "print(\"hELLO wORLD\".capitalize())",
  "out": "Hello world",
  "lesson": "py-strings"
 },
 {
  "name": "str.casefold",
  "sig": "s.casefold()",
  "desc": "Aggressive lower() for caseless comparison.",
  "group": "str methods",
  "ex": "print(\"Straße\".casefold() == \"STRASSE\".casefold())",
  "out": "True",
  "lesson": "py-strings"
 },
 {
  "name": "str.center",
  "sig": "s.center(width, fill=\" \")",
  "desc": "Centre in a field.",
  "group": "str methods",
  "ex": "print(\"[\" + \"hi\".center(6, \"*\") + \"]\")",
  "out": "[**hi**]",
  "lesson": "py-strings"
 },
 {
  "name": "str.count",
  "sig": "s.count(sub)",
  "desc": "Number of non-overlapping occurrences.",
  "group": "str methods",
  "ex": "print(\"banana\".count(\"an\"))",
  "out": "2",
  "lesson": "py-strings"
 },
 {
  "name": "str.encode",
  "sig": "s.encode(encoding=\"utf-8\")",
  "desc": "Convert to bytes.",
  "group": "str methods",
  "ex": "print(\"é\".encode())",
  "out": "b'\\xc3\\xa9'",
  "lesson": "py-files"
 },
 {
  "name": "str.endswith",
  "sig": "s.endswith(suffix)",
  "desc": "True if it ends with the suffix (or a tuple of suffixes).",
  "group": "str methods",
  "ex": "print(\"a.py\".endswith((\".py\", \".txt\")))",
  "out": "True",
  "lesson": "py-strings"
 },
 {
  "name": "str.expandtabs",
  "sig": "s.expandtabs(tabsize=8)",
  "desc": "Replace tabs with spaces.",
  "group": "str methods",
  "ex": "print(\"a\\tb\".expandtabs(4))",
  "out": "a   b",
  "lesson": "py-strings"
 },
 {
  "name": "str.find",
  "sig": "s.find(sub)",
  "desc": "Index of the first match, or -1.",
  "group": "str methods",
  "ex": "print(\"hello\".find(\"l\"), \"hello\".find(\"z\"))",
  "out": "2 -1",
  "lesson": "py-strings"
 },
 {
  "name": "str.format",
  "sig": "s.format(*args, **kwargs)",
  "desc": "Fill {} placeholders.",
  "group": "str methods",
  "ex": "print(\"{} is {:.1f}\".format(\"pi\", 3.14159))",
  "out": "pi is 3.1",
  "lesson": "py-strings"
 },
 {
  "name": "str.format_map",
  "sig": "s.format_map(mapping)",
  "desc": "format() taking a dict.",
  "group": "str methods",
  "ex": "print(\"{a}-{b}\".format_map({\"a\": 1, \"b\": 2}))",
  "out": "1-2",
  "lesson": "py-strings"
 },
 {
  "name": "str.index",
  "sig": "s.index(sub)",
  "desc": "Like find but raises ValueError when absent.",
  "group": "str methods",
  "ex": "print(\"hello\".index(\"e\"))",
  "out": "1",
  "lesson": "py-strings"
 },
 {
  "name": "str.isalnum",
  "sig": "s.isalnum()",
  "desc": "Letters and digits only?",
  "group": "str methods",
  "ex": "print(\"abc123\".isalnum(), \"a b\".isalnum())",
  "out": "True False",
  "lesson": "py-strings"
 },
 {
  "name": "str.isalpha",
  "sig": "s.isalpha()",
  "desc": "Letters only?",
  "group": "str methods",
  "ex": "print(\"abc\".isalpha(), \"ab1\".isalpha())",
  "out": "True False",
  "lesson": "py-strings"
 },
 {
  "name": "str.isascii",
  "sig": "s.isascii()",
  "desc": "All ASCII characters?",
  "group": "str methods",
  "ex": "print(\"abc\".isascii(), \"é\".isascii())",
  "out": "True False",
  "lesson": "py-strings"
 },
 {
  "name": "str.isdecimal",
  "sig": "s.isdecimal()",
  "desc": "Decimal digits only?",
  "group": "str methods",
  "ex": "print(\"123\".isdecimal(), \"1.5\".isdecimal())",
  "out": "True False",
  "lesson": "py-strings"
 },
 {
  "name": "str.isdigit",
  "sig": "s.isdigit()",
  "desc": "Digits only?",
  "group": "str methods",
  "ex": "print(\"123\".isdigit(), \"\".isdigit())",
  "out": "True False",
  "lesson": "py-strings"
 },
 {
  "name": "str.isidentifier",
  "sig": "s.isidentifier()",
  "desc": "A valid Python name?",
  "group": "str methods",
  "ex": "print(\"my_var\".isidentifier(), \"2x\".isidentifier())",
  "out": "True False",
  "lesson": "py-strings"
 },
 {
  "name": "str.islower",
  "sig": "s.islower()",
  "desc": "All cased letters lower-case?",
  "group": "str methods",
  "ex": "print(\"abc\".islower(), \"Abc\".islower())",
  "out": "True False",
  "lesson": "py-strings"
 },
 {
  "name": "str.isnumeric",
  "sig": "s.isnumeric()",
  "desc": "Numeric characters only?",
  "group": "str methods",
  "ex": "print(\"½\".isnumeric(), \"x\".isnumeric())",
  "out": "True False",
  "lesson": "py-strings"
 },
 {
  "name": "str.isprintable",
  "sig": "s.isprintable()",
  "desc": "No control characters?",
  "group": "str methods",
  "ex": "print(\"abc\".isprintable(), \"a\\nb\".isprintable())",
  "out": "True False",
  "lesson": "py-strings"
 },
 {
  "name": "str.isspace",
  "sig": "s.isspace()",
  "desc": "Whitespace only?",
  "group": "str methods",
  "ex": "print(\"  \\t\".isspace(), \"\".isspace())",
  "out": "True False",
  "lesson": "py-strings"
 },
 {
  "name": "str.istitle",
  "sig": "s.istitle()",
  "desc": "Title-cased?",
  "group": "str methods",
  "ex": "print(\"Hello World\".istitle(), \"hello\".istitle())",
  "out": "True False",
  "lesson": "py-strings"
 },
 {
  "name": "str.isupper",
  "sig": "s.isupper()",
  "desc": "All cased letters upper-case?",
  "group": "str methods",
  "ex": "print(\"ABC\".isupper(), \"AbC\".isupper())",
  "out": "True False",
  "lesson": "py-strings"
 },
 {
  "name": "str.join",
  "sig": "sep.join(iterable)",
  "desc": "Glue strings together with a separator.",
  "group": "str methods",
  "ex": "print(\"-\".join([\"a\", \"b\", \"c\"]))",
  "out": "a-b-c",
  "lesson": "py-strings"
 },
 {
  "name": "str.ljust",
  "sig": "s.ljust(width, fill=\" \")",
  "desc": "Left-align in a field.",
  "group": "str methods",
  "ex": "print(\"[\" + \"ab\".ljust(5, \".\") + \"]\")",
  "out": "[ab...]",
  "lesson": "py-strings"
 },
 {
  "name": "str.lower",
  "sig": "s.lower()",
  "desc": "Lower-case copy.",
  "group": "str methods",
  "ex": "print(\"HeLLo\".lower())",
  "out": "hello",
  "lesson": "py-strings"
 },
 {
  "name": "str.lstrip",
  "sig": "s.lstrip(chars=None)",
  "desc": "Remove leading whitespace/characters.",
  "group": "str methods",
  "ex": "print(\"  hi \".lstrip() + \"|\", \"xxhi\".lstrip(\"x\"))",
  "out": "hi | hi",
  "lesson": "py-strings"
 },
 {
  "name": "str.maketrans",
  "sig": "str.maketrans(x, y)",
  "desc": "Build a translation table for translate().",
  "group": "str methods",
  "ex": "print(\"hello\".translate(str.maketrans(\"el\", \"ip\")))",
  "out": "hippo",
  "lesson": "py-strings"
 },
 {
  "name": "str.partition",
  "sig": "s.partition(sep)",
  "desc": "Split into (before, sep, after) at the first sep.",
  "group": "str methods",
  "ex": "print(\"a=b=c\".partition(\"=\"))",
  "out": "('a', '=', 'b=c')",
  "lesson": "py-strings"
 },
 {
  "name": "str.removeprefix",
  "sig": "s.removeprefix(prefix)",
  "desc": "Drop a prefix if present.",
  "group": "str methods",
  "ex": "print(\"test_x\".removeprefix(\"test_\"))",
  "out": "x",
  "lesson": "py-strings"
 },
 {
  "name": "str.removesuffix",
  "sig": "s.removesuffix(suffix)",
  "desc": "Drop a suffix if present.",
  "group": "str methods",
  "ex": "print(\"file.py\".removesuffix(\".py\"))",
  "out": "file",
  "lesson": "py-strings"
 },
 {
  "name": "str.replace",
  "sig": "s.replace(old, new, count=-1)",
  "desc": "Replace occurrences.",
  "group": "str methods",
  "ex": "print(\"a-b-c\".replace(\"-\", \"+\", 1))",
  "out": "a+b-c",
  "lesson": "py-strings"
 },
 {
  "name": "str.rfind",
  "sig": "s.rfind(sub)",
  "desc": "Index of the last match, or -1.",
  "group": "str methods",
  "ex": "print(\"hello\".rfind(\"l\"))",
  "out": "3",
  "lesson": "py-strings"
 },
 {
  "name": "str.rindex",
  "sig": "s.rindex(sub)",
  "desc": "Last match index; ValueError if absent.",
  "group": "str methods",
  "ex": "print(\"hello\".rindex(\"l\"))",
  "out": "3",
  "lesson": "py-strings"
 },
 {
  "name": "str.rjust",
  "sig": "s.rjust(width, fill=\" \")",
  "desc": "Right-align in a field.",
  "group": "str methods",
  "ex": "print(\"[\" + \"7\".rjust(3, \"0\") + \"]\")",
  "out": "[007]",
  "lesson": "py-strings"
 },
 {
  "name": "str.rpartition",
  "sig": "s.rpartition(sep)",
  "desc": "Like partition but at the last sep.",
  "group": "str methods",
  "ex": "print(\"a=b=c\".rpartition(\"=\"))",
  "out": "('a=b', '=', 'c')",
  "lesson": "py-strings"
 },
 {
  "name": "str.rsplit",
  "sig": "s.rsplit(sep, maxsplit)",
  "desc": "Split from the right.",
  "group": "str methods",
  "ex": "print(\"a.b.c\".rsplit(\".\", 1))",
  "out": "['a.b', 'c']",
  "lesson": "py-strings"
 },
 {
  "name": "str.rstrip",
  "sig": "s.rstrip(chars=None)",
  "desc": "Remove trailing whitespace/characters.",
  "group": "str methods",
  "ex": "print(\"hi\\n\".rstrip() + \"|\")",
  "out": "hi|",
  "lesson": "py-strings"
 },
 {
  "name": "str.split",
  "sig": "s.split(sep=None, maxsplit=-1)",
  "desc": "Split into a list.",
  "group": "str methods",
  "ex": "print(\"a b  c\".split(), \"a,b\".split(\",\"))",
  "out": "['a', 'b', 'c'] ['a', 'b']",
  "lesson": "py-strings"
 },
 {
  "name": "str.splitlines",
  "sig": "s.splitlines()",
  "desc": "Split on line breaks.",
  "group": "str methods",
  "ex": "print(\"a\\nb\\r\\nc\".splitlines())",
  "out": "['a', 'b', 'c']",
  "lesson": "py-strings"
 },
 {
  "name": "str.startswith",
  "sig": "s.startswith(prefix)",
  "desc": "True if it starts with the prefix.",
  "group": "str methods",
  "ex": "print(\"hello\".startswith(\"he\"))",
  "out": "True",
  "lesson": "py-strings"
 },
 {
  "name": "str.strip",
  "sig": "s.strip(chars=None)",
  "desc": "Remove whitespace/characters at both ends.",
  "group": "str methods",
  "ex": "print(\"  hi  \".strip() + \"|\", \"--x--\".strip(\"-\"))",
  "out": "hi| x",
  "lesson": "py-strings"
 },
 {
  "name": "str.swapcase",
  "sig": "s.swapcase()",
  "desc": "Swap upper and lower case.",
  "group": "str methods",
  "ex": "print(\"Hello\".swapcase())",
  "out": "hELLO",
  "lesson": "py-strings"
 },
 {
  "name": "str.title",
  "sig": "s.title()",
  "desc": "Title Case Every Word.",
  "group": "str methods",
  "ex": "print(\"hello big world\".title())",
  "out": "Hello Big World",
  "lesson": "py-strings"
 },
 {
  "name": "str.translate",
  "sig": "s.translate(table)",
  "desc": "Map characters through a table.",
  "group": "str methods",
  "ex": "print(\"abc\".translate({ord(\"a\"): \"A\"}))",
  "out": "Abc",
  "lesson": "py-strings"
 },
 {
  "name": "str.upper",
  "sig": "s.upper()",
  "desc": "Upper-case copy.",
  "group": "str methods",
  "ex": "print(\"hi\".upper())",
  "out": "HI",
  "lesson": "py-strings"
 },
 {
  "name": "str.zfill",
  "sig": "s.zfill(width)",
  "desc": "Pad with leading zeros.",
  "group": "str methods",
  "ex": "print(\"42\".zfill(5), \"-7\".zfill(4))",
  "out": "00042 -007",
  "lesson": "py-strings"
 },
 {
  "name": "list.append",
  "sig": "a.append(x)",
  "desc": "Add one item to the end.",
  "group": "list methods",
  "ex": "a = [1]\na.append(2)\nprint(a)",
  "out": "[1, 2]",
  "lesson": "py-lists"
 },
 {
  "name": "list.clear",
  "sig": "a.clear()",
  "desc": "Remove every item.",
  "group": "list methods",
  "ex": "a = [1, 2]\na.clear()\nprint(a)",
  "out": "[]",
  "lesson": "py-lists"
 },
 {
  "name": "list.copy",
  "sig": "a.copy()",
  "desc": "A shallow copy.",
  "group": "list methods",
  "ex": "a = [1, [2]]\nb = a.copy()\nb[0] = 9\nprint(a, b)",
  "out": "[1, [2]] [9, [2]]",
  "lesson": "py-lists"
 },
 {
  "name": "list.count",
  "sig": "a.count(x)",
  "desc": "How many times x appears.",
  "group": "list methods",
  "ex": "print([1, 2, 1, 1].count(1))",
  "out": "3",
  "lesson": "py-lists"
 },
 {
  "name": "list.extend",
  "sig": "a.extend(iterable)",
  "desc": "Append every item of an iterable.",
  "group": "list methods",
  "ex": "a = [1]\na.extend([2, 3])\nprint(a)",
  "out": "[1, 2, 3]",
  "lesson": "py-lists"
 },
 {
  "name": "list.index",
  "sig": "a.index(x)",
  "desc": "Position of the first x (ValueError if absent).",
  "group": "list methods",
  "ex": "print([\"a\", \"b\"].index(\"b\"))",
  "out": "1",
  "lesson": "py-lists"
 },
 {
  "name": "list.insert",
  "sig": "a.insert(i, x)",
  "desc": "Insert x before position i.",
  "group": "list methods",
  "ex": "a = [1, 3]\na.insert(1, 2)\nprint(a)",
  "out": "[1, 2, 3]",
  "lesson": "py-lists"
 },
 {
  "name": "list.pop",
  "sig": "a.pop(i=-1)",
  "desc": "Remove and return an item.",
  "group": "list methods",
  "ex": "a = [1, 2, 3]\nprint(a.pop(), a.pop(0), a)",
  "out": "3 1 [2]",
  "lesson": "py-lists"
 },
 {
  "name": "list.remove",
  "sig": "a.remove(x)",
  "desc": "Remove the first x.",
  "group": "list methods",
  "ex": "a = [1, 2, 1]\na.remove(1)\nprint(a)",
  "out": "[2, 1]",
  "lesson": "py-lists"
 },
 {
  "name": "list.reverse",
  "sig": "a.reverse()",
  "desc": "Reverse in place.",
  "group": "list methods",
  "ex": "a = [1, 2, 3]\na.reverse()\nprint(a)",
  "out": "[3, 2, 1]",
  "lesson": "py-lists"
 },
 {
  "name": "list.sort",
  "sig": "a.sort(key=None, reverse=False)",
  "desc": "Sort in place (returns None).",
  "group": "list methods",
  "ex": "a = [\"bb\", \"a\", \"ccc\"]\na.sort(key=len, reverse=True)\nprint(a)",
  "out": "['ccc', 'bb', 'a']",
  "lesson": "py-functions"
 },
 {
  "name": "dict.clear",
  "sig": "d.clear()",
  "desc": "Remove all items.",
  "group": "dict methods",
  "ex": "d = {\"a\": 1}\nd.clear()\nprint(d)",
  "out": "{}",
  "lesson": "py-dicts"
 },
 {
  "name": "dict.copy",
  "sig": "d.copy()",
  "desc": "A shallow copy.",
  "group": "dict methods",
  "ex": "d = {\"a\": 1}\ne = d.copy()\ne[\"a\"] = 2\nprint(d, e)",
  "out": "{'a': 1} {'a': 2}",
  "lesson": "py-dicts"
 },
 {
  "name": "dict.fromkeys",
  "sig": "dict.fromkeys(keys, value=None)",
  "desc": "New dict with the same value for every key.",
  "group": "dict methods",
  "ex": "print(dict.fromkeys([\"a\", \"b\"], 0))",
  "out": "{'a': 0, 'b': 0}",
  "lesson": "py-dicts"
 },
 {
  "name": "dict.get",
  "sig": "d.get(key, default=None)",
  "desc": "Value for key, or default (no KeyError).",
  "group": "dict methods",
  "ex": "d = {\"a\": 1}\nprint(d.get(\"a\"), d.get(\"z\", 0))",
  "out": "1 0",
  "lesson": "py-dicts"
 },
 {
  "name": "dict.items",
  "sig": "d.items()",
  "desc": "View of (key, value) pairs.",
  "group": "dict methods",
  "ex": "print(list({\"a\": 1, \"b\": 2}.items()))",
  "out": "[('a', 1), ('b', 2)]",
  "lesson": "py-dicts"
 },
 {
  "name": "dict.keys",
  "sig": "d.keys()",
  "desc": "View of the keys.",
  "group": "dict methods",
  "ex": "print(list({\"a\": 1, \"b\": 2}.keys()))",
  "out": "['a', 'b']",
  "lesson": "py-dicts"
 },
 {
  "name": "dict.pop",
  "sig": "d.pop(key, default)",
  "desc": "Remove and return a value.",
  "group": "dict methods",
  "ex": "d = {\"a\": 1}\nprint(d.pop(\"a\"), d.pop(\"z\", \"none\"), d)",
  "out": "1 none {}",
  "lesson": "py-dicts"
 },
 {
  "name": "dict.popitem",
  "sig": "d.popitem()",
  "desc": "Remove and return the last (key, value).",
  "group": "dict methods",
  "ex": "d = {\"a\": 1, \"b\": 2}\nprint(d.popitem(), d)",
  "out": "('b', 2) {'a': 1}",
  "lesson": "py-dicts"
 },
 {
  "name": "dict.setdefault",
  "sig": "d.setdefault(key, default)",
  "desc": "Get a key, inserting the default if missing.",
  "group": "dict methods",
  "ex": "d = {}\nd.setdefault(\"k\", []).append(1)\nprint(d)",
  "out": "{'k': [1]}",
  "lesson": "py-dicts"
 },
 {
  "name": "dict.update",
  "sig": "d.update(other)",
  "desc": "Merge another mapping in.",
  "group": "dict methods",
  "ex": "d = {\"a\": 1}\nd.update({\"b\": 2}, a=9)\nprint(d)",
  "out": "{'a': 9, 'b': 2}",
  "lesson": "py-dicts"
 },
 {
  "name": "dict.values",
  "sig": "d.values()",
  "desc": "View of the values.",
  "group": "dict methods",
  "ex": "print(sum({\"a\": 1, \"b\": 2}.values()))",
  "out": "3",
  "lesson": "py-dicts"
 },
 {
  "name": "set.add",
  "sig": "s.add(x)",
  "desc": "Add an element.",
  "group": "set methods",
  "ex": "s = {1}\ns.add(2)\nprint(sorted(s))",
  "out": "[1, 2]",
  "lesson": "py-lists"
 },
 {
  "name": "set.clear",
  "sig": "s.clear()",
  "desc": "Remove everything.",
  "group": "set methods",
  "ex": "s = {1}\ns.clear()\nprint(s)",
  "out": "set()",
  "lesson": "py-lists"
 },
 {
  "name": "set.copy",
  "sig": "s.copy()",
  "desc": "Shallow copy.",
  "group": "set methods",
  "ex": "s = {1, 2}\nt = s.copy()\nt.add(3)\nprint(sorted(s), sorted(t))",
  "out": "[1, 2] [1, 2, 3]",
  "lesson": "py-lists"
 },
 {
  "name": "set.difference",
  "sig": "a.difference(b)  /  a - b",
  "desc": "Elements in a but not b.",
  "group": "set methods",
  "ex": "print(sorted({1, 2, 3} - {2}))",
  "out": "[1, 3]",
  "lesson": "py-lists"
 },
 {
  "name": "set.difference_update",
  "sig": "a.difference_update(b)",
  "desc": "Remove b's elements from a.",
  "group": "set methods",
  "ex": "a = {1, 2, 3}\na.difference_update({1})\nprint(sorted(a))",
  "out": "[2, 3]",
  "lesson": "py-lists"
 },
 {
  "name": "set.discard",
  "sig": "s.discard(x)",
  "desc": "Remove x if present (no error).",
  "group": "set methods",
  "ex": "s = {1}\ns.discard(5)\nprint(s)",
  "out": "{1}",
  "lesson": "py-lists"
 },
 {
  "name": "set.intersection",
  "sig": "a.intersection(b)  /  a & b",
  "desc": "Elements in both.",
  "group": "set methods",
  "ex": "print(sorted({1, 2, 3} & {2, 3, 4}))",
  "out": "[2, 3]",
  "lesson": "py-lists"
 },
 {
  "name": "set.intersection_update",
  "sig": "a.intersection_update(b)",
  "desc": "Keep only elements also in b.",
  "group": "set methods",
  "ex": "a = {1, 2, 3}\na.intersection_update({2, 3, 9})\nprint(sorted(a))",
  "out": "[2, 3]",
  "lesson": "py-lists"
 },
 {
  "name": "set.isdisjoint",
  "sig": "a.isdisjoint(b)",
  "desc": "No elements in common?",
  "group": "set methods",
  "ex": "print({1, 2}.isdisjoint({3}))",
  "out": "True",
  "lesson": "py-lists"
 },
 {
  "name": "set.issubset",
  "sig": "a.issubset(b)  /  a <= b",
  "desc": "Every element of a is in b?",
  "group": "set methods",
  "ex": "print({1}.issubset({1, 2}))",
  "out": "True",
  "lesson": "py-lists"
 },
 {
  "name": "set.issuperset",
  "sig": "a.issuperset(b)  /  a >= b",
  "desc": "a contains every element of b?",
  "group": "set methods",
  "ex": "print({1, 2}.issuperset({1}))",
  "out": "True",
  "lesson": "py-lists"
 },
 {
  "name": "set.pop",
  "sig": "s.pop()",
  "desc": "Remove and return an arbitrary element.",
  "group": "set methods",
  "ex": "s = {7}\nprint(s.pop(), s)",
  "out": "7 set()",
  "lesson": "py-lists"
 },
 {
  "name": "set.remove",
  "sig": "s.remove(x)",
  "desc": "Remove x (KeyError if absent).",
  "group": "set methods",
  "ex": "s = {1, 2}\ns.remove(1)\nprint(s)",
  "out": "{2}",
  "lesson": "py-lists"
 },
 {
  "name": "set.symmetric_difference",
  "sig": "a.symmetric_difference(b)  /  a ^ b",
  "desc": "Elements in exactly one of the two.",
  "group": "set methods",
  "ex": "print(sorted({1, 2} ^ {2, 3}))",
  "out": "[1, 3]",
  "lesson": "py-lists"
 },
 {
  "name": "set.union",
  "sig": "a.union(b)  /  a | b",
  "desc": "Elements in either.",
  "group": "set methods",
  "ex": "print(sorted({1} | {2}))",
  "out": "[1, 2]",
  "lesson": "py-lists"
 },
 {
  "name": "set.update",
  "sig": "s.update(iterable)",
  "desc": "Add many elements.",
  "group": "set methods",
  "ex": "s = {1}\ns.update([2, 3])\nprint(sorted(s))",
  "out": "[1, 2, 3]",
  "lesson": "py-lists"
 },
 {
  "name": "tuple.count",
  "sig": "t.count(x)",
  "desc": "How many times x appears.",
  "group": "tuple methods",
  "ex": "print((1, 2, 1).count(1))",
  "out": "2",
  "lesson": "py-lists"
 },
 {
  "name": "tuple.index",
  "sig": "t.index(x)",
  "desc": "Position of x.",
  "group": "tuple methods",
  "ex": "print((\"a\", \"b\").index(\"b\"))",
  "out": "1",
  "lesson": "py-lists"
 },
 {
  "name": "math.ceil",
  "sig": "math.ceil(x)",
  "desc": "Round up to an integer.",
  "group": "math",
  "ex": "import math\nprint(math.ceil(2.1))",
  "out": "3",
  "lesson": "py-stdlib"
 },
 {
  "name": "math.comb",
  "sig": "math.comb(n, k)",
  "desc": "Number of ways to choose k of n.",
  "group": "math",
  "ex": "import math\nprint(math.comb(5, 2))",
  "out": "10",
  "lesson": "py-stdlib"
 },
 {
  "name": "math.cos",
  "sig": "math.cos(x)",
  "desc": "Cosine (radians).",
  "group": "math",
  "ex": "import math\nprint(round(math.cos(math.pi), 3))",
  "out": "-1.0",
  "lesson": "py-stdlib"
 },
 {
  "name": "math.degrees",
  "sig": "math.degrees(x)",
  "desc": "Radians to degrees.",
  "group": "math",
  "ex": "import math\nprint(math.degrees(math.pi))",
  "out": "180.0",
  "lesson": "py-stdlib"
 },
 {
  "name": "math.e",
  "sig": "math.e",
  "desc": "Euler's number.",
  "group": "math",
  "ex": "import math\nprint(round(math.e, 5))",
  "out": "2.71828",
  "lesson": "py-stdlib"
 },
 {
  "name": "math.exp",
  "sig": "math.exp(x)",
  "desc": "e to the power x.",
  "group": "math",
  "ex": "import math\nprint(round(math.exp(1), 5))",
  "out": "2.71828",
  "lesson": "py-stdlib"
 },
 {
  "name": "math.factorial",
  "sig": "math.factorial(n)",
  "desc": "n!",
  "group": "math",
  "ex": "import math\nprint(math.factorial(5))",
  "out": "120",
  "lesson": "py-stdlib"
 },
 {
  "name": "math.floor",
  "sig": "math.floor(x)",
  "desc": "Round down to an integer.",
  "group": "math",
  "ex": "import math\nprint(math.floor(-2.1))",
  "out": "-3",
  "lesson": "py-stdlib"
 },
 {
  "name": "math.gcd",
  "sig": "math.gcd(a, b)",
  "desc": "Greatest common divisor.",
  "group": "math",
  "ex": "import math\nprint(math.gcd(12, 18))",
  "out": "6",
  "lesson": "py-stdlib"
 },
 {
  "name": "math.hypot",
  "sig": "math.hypot(*coords)",
  "desc": "Euclidean distance.",
  "group": "math",
  "ex": "import math\nprint(math.hypot(3, 4))",
  "out": "5.0",
  "lesson": "py-stdlib"
 },
 {
  "name": "math.inf",
  "sig": "math.inf",
  "desc": "Positive infinity.",
  "group": "math",
  "ex": "import math\nprint(math.inf > 10**100)",
  "out": "True",
  "lesson": "py-stdlib"
 },
 {
  "name": "math.isclose",
  "sig": "math.isclose(a, b)",
  "desc": "Are two floats nearly equal?",
  "group": "math",
  "ex": "import math\nprint(0.1 + 0.2 == 0.3, math.isclose(0.1 + 0.2, 0.3))",
  "out": "False True",
  "lesson": "py-variables"
 },
 {
  "name": "math.isqrt",
  "sig": "math.isqrt(n)",
  "desc": "Integer square root.",
  "group": "math",
  "ex": "import math\nprint(math.isqrt(17))",
  "out": "4",
  "lesson": "py-stdlib"
 },
 {
  "name": "math.lcm",
  "sig": "math.lcm(a, b)",
  "desc": "Least common multiple.",
  "group": "math",
  "ex": "import math\nprint(math.lcm(4, 6))",
  "out": "12",
  "lesson": "py-stdlib"
 },
 {
  "name": "math.log",
  "sig": "math.log(x, base=e)",
  "desc": "Logarithm.",
  "group": "math",
  "ex": "import math\nprint(math.log(8, 2), math.log(math.e))",
  "out": "3.0 1.0",
  "lesson": "py-stdlib"
 },
 {
  "name": "math.log10",
  "sig": "math.log10(x)",
  "desc": "Base-10 logarithm.",
  "group": "math",
  "ex": "import math\nprint(math.log10(1000))",
  "out": "3.0",
  "lesson": "py-stdlib"
 },
 {
  "name": "math.perm",
  "sig": "math.perm(n, k)",
  "desc": "Ordered arrangements of k from n.",
  "group": "math",
  "ex": "import math\nprint(math.perm(5, 2))",
  "out": "20",
  "lesson": "py-stdlib"
 },
 {
  "name": "math.pi",
  "sig": "math.pi",
  "desc": "The constant pi.",
  "group": "math",
  "ex": "import math\nprint(round(math.pi, 5))",
  "out": "3.14159",
  "lesson": "py-stdlib"
 },
 {
  "name": "math.radians",
  "sig": "math.radians(x)",
  "desc": "Degrees to radians.",
  "group": "math",
  "ex": "import math\nprint(round(math.radians(180), 5))",
  "out": "3.14159",
  "lesson": "py-stdlib"
 },
 {
  "name": "math.sin",
  "sig": "math.sin(x)",
  "desc": "Sine (radians).",
  "group": "math",
  "ex": "import math\nprint(round(math.sin(math.pi / 2), 3))",
  "out": "1.0",
  "lesson": "py-stdlib"
 },
 {
  "name": "math.sqrt",
  "sig": "math.sqrt(x)",
  "desc": "Square root.",
  "group": "math",
  "ex": "import math\nprint(math.sqrt(16))",
  "out": "4.0",
  "lesson": "py-stdlib"
 },
 {
  "name": "math.tan",
  "sig": "math.tan(x)",
  "desc": "Tangent (radians).",
  "group": "math",
  "ex": "import math\nprint(round(math.tan(math.pi / 4), 3))",
  "out": "1.0",
  "lesson": "py-stdlib"
 },
 {
  "name": "math.trunc",
  "sig": "math.trunc(x)",
  "desc": "Drop the fractional part.",
  "group": "math",
  "ex": "import math\nprint(math.trunc(-2.7))",
  "out": "-2",
  "lesson": "py-stdlib"
 },
 {
  "name": "random.seed",
  "sig": "random.seed(n)",
  "desc": "Make random numbers reproducible.",
  "group": "random & statistics",
  "ex": "import random\nrandom.seed(1)\na = random.random()\nrandom.seed(1)\nprint(a == random.random())",
  "out": "True",
  "lesson": "py-stdlib"
 },
 {
  "name": "random.random",
  "sig": "random.random()",
  "desc": "Float in [0, 1).",
  "group": "random & statistics",
  "ex": "import random\nrandom.seed(3)\nprint(0 <= random.random() < 1)",
  "out": "True",
  "lesson": "py-stdlib"
 },
 {
  "name": "random.randint",
  "sig": "random.randint(a, b)",
  "desc": "Integer in [a, b] inclusive.",
  "group": "random & statistics",
  "ex": "import random\nrandom.seed(3)\nprint(1 <= random.randint(1, 6) <= 6)",
  "out": "True",
  "lesson": "py-stdlib"
 },
 {
  "name": "random.choice",
  "sig": "random.choice(seq)",
  "desc": "One random item.",
  "group": "random & statistics",
  "ex": "import random\nrandom.seed(3)\nprint(random.choice(\"abc\") in \"abc\")",
  "out": "True",
  "lesson": "py-stdlib"
 },
 {
  "name": "random.choices",
  "sig": "random.choices(pop, k=n)",
  "desc": "k items, with replacement.",
  "group": "random & statistics",
  "ex": "import random\nrandom.seed(3)\nprint(len(random.choices([1, 2], k=5)))",
  "out": "5",
  "lesson": "py-stdlib"
 },
 {
  "name": "random.sample",
  "sig": "random.sample(pop, k)",
  "desc": "k distinct items.",
  "group": "random & statistics",
  "ex": "import random\nrandom.seed(3)\nprint(len(set(random.sample(range(10), 4))))",
  "out": "4",
  "lesson": "py-stdlib"
 },
 {
  "name": "random.shuffle",
  "sig": "random.shuffle(list)",
  "desc": "Shuffle a list in place.",
  "group": "random & statistics",
  "ex": "import random\nrandom.seed(3)\na = [1, 2, 3, 4]\nrandom.shuffle(a)\nprint(sorted(a))",
  "out": "[1, 2, 3, 4]",
  "lesson": "py-stdlib"
 },
 {
  "name": "random.uniform",
  "sig": "random.uniform(a, b)",
  "desc": "Float between a and b.",
  "group": "random & statistics",
  "ex": "import random\nrandom.seed(3)\nprint(2 <= random.uniform(2, 3) <= 3)",
  "out": "True",
  "lesson": "py-stdlib"
 },
 {
  "name": "statistics.mean",
  "sig": "statistics.mean(data)",
  "desc": "Arithmetic mean.",
  "group": "random & statistics",
  "ex": "import statistics\nprint(statistics.mean([1, 2, 3, 4]))",
  "out": "2.5",
  "lesson": "py-stdlib"
 },
 {
  "name": "statistics.median",
  "sig": "statistics.median(data)",
  "desc": "Middle value.",
  "group": "random & statistics",
  "ex": "import statistics\nprint(statistics.median([1, 3, 2, 10]))",
  "out": "2.5",
  "lesson": "py-stdlib"
 },
 {
  "name": "statistics.mode",
  "sig": "statistics.mode(data)",
  "desc": "Most common value.",
  "group": "random & statistics",
  "ex": "import statistics\nprint(statistics.mode([1, 2, 2, 3]))",
  "out": "2",
  "lesson": "py-stdlib"
 },
 {
  "name": "statistics.stdev",
  "sig": "statistics.stdev(data)",
  "desc": "Sample standard deviation.",
  "group": "random & statistics",
  "ex": "import statistics\nprint(round(statistics.stdev([2, 4, 4, 4, 5, 5, 7, 9]), 4))",
  "out": "2.1381",
  "lesson": "py-stdlib"
 },
 {
  "name": "statistics.pstdev",
  "sig": "statistics.pstdev(data)",
  "desc": "Population standard deviation.",
  "group": "random & statistics",
  "ex": "import statistics\nprint(statistics.pstdev([2, 4, 4, 4, 5, 5, 7, 9]))",
  "out": "2.0",
  "lesson": "py-stdlib"
 },
 {
  "name": "statistics.variance",
  "sig": "statistics.variance(data)",
  "desc": "Sample variance.",
  "group": "random & statistics",
  "ex": "import statistics\nprint(statistics.variance([1, 2, 3, 4]))",
  "out": "1.6666666666666667",
  "lesson": "py-stdlib"
 },
 {
  "name": "collections.Counter",
  "sig": "Counter(iterable)",
  "desc": "Count occurrences.",
  "group": "collections & itertools & functools",
  "ex": "from collections import Counter\nc = Counter(\"banana\")\nprint(c.most_common(2))",
  "out": "[('a', 3), ('n', 2)]",
  "lesson": "py-stdlib"
 },
 {
  "name": "collections.defaultdict",
  "sig": "defaultdict(factory)",
  "desc": "A dict with automatic default values.",
  "group": "collections & itertools & functools",
  "ex": "from collections import defaultdict\nd = defaultdict(list)\nd[\"a\"].append(1)\nprint(dict(d))",
  "out": "{'a': [1]}",
  "lesson": "py-stdlib"
 },
 {
  "name": "collections.deque",
  "sig": "deque(iterable, maxlen)",
  "desc": "Fast appends/pops at both ends.",
  "group": "collections & itertools & functools",
  "ex": "from collections import deque\nd = deque([1, 2, 3], maxlen=3)\nd.append(4)\nd.appendleft(0)\nprint(list(d))",
  "out": "[0, 2, 3]",
  "lesson": "py-lists"
 },
 {
  "name": "collections.namedtuple",
  "sig": "namedtuple(name, fields)",
  "desc": "A tuple with named fields.",
  "group": "collections & itertools & functools",
  "ex": "from collections import namedtuple\nP = namedtuple(\"P\", \"x y\")\np = P(1, 2)\nprint(p.x, p)",
  "out": "1 P(x=1, y=2)",
  "lesson": "py-stdlib"
 },
 {
  "name": "collections.OrderedDict",
  "sig": "OrderedDict()",
  "desc": "A dict with order-aware operations (e.g. move_to_end).",
  "group": "collections & itertools & functools",
  "ex": "from collections import OrderedDict\nd = OrderedDict(a=1, b=2)\nd.move_to_end(\"a\")\nprint(list(d))",
  "out": "['b', 'a']",
  "lesson": "py-stdlib"
 },
 {
  "name": "itertools.chain",
  "sig": "chain(*iterables)",
  "desc": "Iterate several iterables as one.",
  "group": "collections & itertools & functools",
  "ex": "from itertools import chain\nprint(list(chain([1], \"ab\")))",
  "out": "[1, 'a', 'b']",
  "lesson": "py-stdlib"
 },
 {
  "name": "itertools.combinations",
  "sig": "combinations(it, r)",
  "desc": "All r-sized combinations.",
  "group": "collections & itertools & functools",
  "ex": "from itertools import combinations\nprint(list(combinations(\"abc\", 2)))",
  "out": "[('a', 'b'), ('a', 'c'), ('b', 'c')]",
  "lesson": "py-stdlib"
 },
 {
  "name": "itertools.count",
  "sig": "count(start, step)",
  "desc": "Endless counter.",
  "group": "collections & itertools & functools",
  "ex": "from itertools import count, islice\nprint(list(islice(count(5, 2), 3)))",
  "out": "[5, 7, 9]",
  "lesson": "py-stdlib"
 },
 {
  "name": "itertools.cycle",
  "sig": "cycle(iterable)",
  "desc": "Repeat forever.",
  "group": "collections & itertools & functools",
  "ex": "from itertools import cycle, islice\nprint(list(islice(cycle(\"ab\"), 5)))",
  "out": "['a', 'b', 'a', 'b', 'a']",
  "lesson": "py-stdlib"
 },
 {
  "name": "itertools.groupby",
  "sig": "groupby(it, key)",
  "desc": "Group consecutive equal keys (sort first).",
  "group": "collections & itertools & functools",
  "ex": "from itertools import groupby\nprint([(k, len(list(g))) for k, g in groupby(\"aabccc\")])",
  "out": "[('a', 2), ('b', 1), ('c', 3)]",
  "lesson": "py-stdlib"
 },
 {
  "name": "itertools.islice",
  "sig": "islice(it, stop)",
  "desc": "Slice any iterator.",
  "group": "collections & itertools & functools",
  "ex": "from itertools import islice\nprint(list(islice(range(100), 3)))",
  "out": "[0, 1, 2]",
  "lesson": "py-stdlib"
 },
 {
  "name": "itertools.permutations",
  "sig": "permutations(it, r)",
  "desc": "All orderings.",
  "group": "collections & itertools & functools",
  "ex": "from itertools import permutations\nprint(len(list(permutations(\"abc\"))))",
  "out": "6",
  "lesson": "py-stdlib"
 },
 {
  "name": "itertools.product",
  "sig": "product(*its)",
  "desc": "Cartesian product.",
  "group": "collections & itertools & functools",
  "ex": "from itertools import product\nprint(list(product(\"ab\", [1, 2])))",
  "out": "[('a', 1), ('a', 2), ('b', 1), ('b', 2)]",
  "lesson": "py-stdlib"
 },
 {
  "name": "itertools.accumulate",
  "sig": "accumulate(it, func)",
  "desc": "Running totals.",
  "group": "collections & itertools & functools",
  "ex": "from itertools import accumulate\nprint(list(accumulate([1, 2, 3, 4])))",
  "out": "[1, 3, 6, 10]",
  "lesson": "py-stdlib"
 },
 {
  "name": "functools.reduce",
  "sig": "reduce(func, it, init)",
  "desc": "Fold a sequence into one value.",
  "group": "collections & itertools & functools",
  "ex": "from functools import reduce\nprint(reduce(lambda a, b: a * b, [1, 2, 3, 4]))",
  "out": "24",
  "lesson": "py-functions"
 },
 {
  "name": "functools.lru_cache",
  "sig": "@lru_cache(maxsize)",
  "desc": "Memoise a function's results.",
  "group": "collections & itertools & functools",
  "ex": "from functools import lru_cache\n@lru_cache(maxsize=None)\ndef fib(n):\n    return n if n < 2 else fib(n - 1) + fib(n - 2)\nprint(fib(50))",
  "out": "12586269025",
  "lesson": "py-functions"
 },
 {
  "name": "functools.partial",
  "sig": "partial(func, *args)",
  "desc": "Pre-fill some arguments.",
  "group": "collections & itertools & functools",
  "ex": "from functools import partial\ndouble = partial(pow, exp=2)\nprint(double(5))",
  "out": "25",
  "lesson": "py-functions"
 },
 {
  "name": "functools.wraps",
  "sig": "@wraps(func)",
  "desc": "Keep a decorated function's name and docstring.",
  "group": "collections & itertools & functools",
  "ex": "from functools import wraps\ndef deco(f):\n    @wraps(f)\n    def inner(*a):\n        return f(*a)\n    return inner\n@deco\ndef hi():\n    \"doc\"\nprint(hi.__name__)",
  "out": "hi",
  "lesson": "py-functions"
 },
 {
  "name": "re.findall",
  "sig": "re.findall(pattern, text)",
  "desc": "All matches as a list.",
  "group": "re, json, datetime, pathlib",
  "ex": "import re\nprint(re.findall(r\"\\d+\", \"a1 b22 c333\"))",
  "out": "['1', '22', '333']",
  "lesson": "py-stdlib"
 },
 {
  "name": "re.match",
  "sig": "re.match(pattern, text)",
  "desc": "Match at the start of the text.",
  "group": "re, json, datetime, pathlib",
  "ex": "import re\nm = re.match(r\"(\\w+)@(\\w+)\", \"ada@lab\")\nprint(m.groups())",
  "out": "('ada', 'lab')",
  "lesson": "py-stdlib"
 },
 {
  "name": "re.search",
  "sig": "re.search(pattern, text)",
  "desc": "First match anywhere.",
  "group": "re, json, datetime, pathlib",
  "ex": "import re\nprint(re.search(r\"\\d+\", \"ab12cd\").group())",
  "out": "12",
  "lesson": "py-stdlib"
 },
 {
  "name": "re.sub",
  "sig": "re.sub(pattern, repl, text)",
  "desc": "Replace matches.",
  "group": "re, json, datetime, pathlib",
  "ex": "import re\nprint(re.sub(r\"\\s+\", \" \", \"a   b \\n c\"))",
  "out": "a b c",
  "lesson": "py-stdlib"
 },
 {
  "name": "re.split",
  "sig": "re.split(pattern, text)",
  "desc": "Split on a pattern.",
  "group": "re, json, datetime, pathlib",
  "ex": "import re\nprint(re.split(r\"[,;]\\s*\", \"a, b;c\"))",
  "out": "['a', 'b', 'c']",
  "lesson": "py-stdlib"
 },
 {
  "name": "re.compile",
  "sig": "re.compile(pattern)",
  "desc": "Pre-compile a pattern for reuse.",
  "group": "re, json, datetime, pathlib",
  "ex": "import re\nr = re.compile(r\"^\\d{3}$\")\nprint(bool(r.match(\"123\")), bool(r.match(\"12\")))",
  "out": "True False",
  "lesson": "py-stdlib"
 },
 {
  "name": "re.fullmatch",
  "sig": "re.fullmatch(pattern, text)",
  "desc": "The whole string must match.",
  "group": "re, json, datetime, pathlib",
  "ex": "import re\nprint(bool(re.fullmatch(r\"\\d+\", \"123\")), bool(re.fullmatch(r\"\\d+\", \"12a\")))",
  "out": "True False",
  "lesson": "py-stdlib"
 },
 {
  "name": "json.dumps",
  "sig": "json.dumps(obj, indent=None)",
  "desc": "Python object to a JSON string.",
  "group": "re, json, datetime, pathlib",
  "ex": "import json\nprint(json.dumps({\"a\": [1, True, None]}))",
  "out": "{\"a\": [1, true, null]}",
  "lesson": "py-files"
 },
 {
  "name": "json.loads",
  "sig": "json.loads(text)",
  "desc": "JSON string to a Python object.",
  "group": "re, json, datetime, pathlib",
  "ex": "import json\nprint(json.loads('{\"a\": [1, 2]}')[\"a\"])",
  "out": "[1, 2]",
  "lesson": "py-files"
 },
 {
  "name": "json.dump",
  "sig": "json.dump(obj, file)",
  "desc": "Write JSON to an open file.",
  "group": "re, json, datetime, pathlib",
  "ex": "import json\nwith open(\"d.json\", \"w\") as f:\n    json.dump({\"x\": 1}, f)\nprint(open(\"d.json\").read())",
  "out": "{\"x\": 1}",
  "lesson": "py-files"
 },
 {
  "name": "json.load",
  "sig": "json.load(file)",
  "desc": "Read JSON from an open file.",
  "group": "re, json, datetime, pathlib",
  "ex": "import json\nwith open(\"d2.json\", \"w\") as f:\n    f.write('{\"x\": 2}')\nprint(json.load(open(\"d2.json\")))",
  "out": "{'x': 2}",
  "lesson": "py-files"
 },
 {
  "name": "datetime.date",
  "sig": "date(year, month, day)",
  "desc": "A calendar date.",
  "group": "re, json, datetime, pathlib",
  "ex": "from datetime import date\nd = date(2024, 2, 29)\nprint(d.weekday(), d.isoformat())",
  "out": "3 2024-02-29",
  "lesson": "py-stdlib"
 },
 {
  "name": "datetime.timedelta",
  "sig": "timedelta(days=, hours=...)",
  "desc": "A span of time.",
  "group": "re, json, datetime, pathlib",
  "ex": "from datetime import date, timedelta\nprint(date(2024, 1, 31) + timedelta(days=30))",
  "out": "2024-03-01",
  "lesson": "py-stdlib"
 },
 {
  "name": "datetime.datetime",
  "sig": "datetime(y, m, d, h, mi, s)",
  "desc": "A date and time.",
  "group": "re, json, datetime, pathlib",
  "ex": "from datetime import datetime\nd = datetime(2024, 5, 17, 13, 45)\nprint(d.strftime(\"%d %b %Y %H:%M\"))",
  "out": "17 May 2024 13:45",
  "lesson": "py-stdlib"
 },
 {
  "name": "datetime.strptime",
  "sig": "datetime.strptime(text, fmt)",
  "desc": "Parse text into a datetime.",
  "group": "re, json, datetime, pathlib",
  "ex": "from datetime import datetime\nprint(datetime.strptime(\"2024-03-09\", \"%Y-%m-%d\").year)",
  "out": "2024",
  "lesson": "py-stdlib"
 },
 {
  "name": "pathlib.Path",
  "sig": "Path(path)",
  "desc": "Object-oriented file paths.",
  "group": "re, json, datetime, pathlib",
  "ex": "from pathlib import Path\np = Path(\"a\") / \"b.txt\"\nprint(p.name, p.suffix, p.parent)",
  "out": "b.txt .txt a",
  "lesson": "py-files"
 },
 {
  "name": "os.path.join",
  "sig": "os.path.join(a, b)",
  "desc": "Join path parts with the right separator.",
  "group": "re, json, datetime, pathlib",
  "ex": "import os\nprint(os.path.join(\"a\", \"b\", \"c.txt\"))",
  "out": "a/b/c.txt",
  "lesson": "py-files"
 },
 {
  "name": "os.getcwd",
  "sig": "os.getcwd()",
  "desc": "Current working directory.",
  "group": "re, json, datetime, pathlib",
  "ex": "import os\nprint(isinstance(os.getcwd(), str))",
  "out": "True",
  "lesson": "py-files"
 },
 {
  "name": "os.listdir",
  "sig": "os.listdir(path)",
  "desc": "Names in a directory.",
  "group": "re, json, datetime, pathlib",
  "ex": "import os\nopen(\"z.txt\", \"w\").close()\nprint(\"z.txt\" in os.listdir(\".\"))",
  "out": "True",
  "lesson": "py-files"
 },
 {
  "name": "sys.argv",
  "sig": "sys.argv",
  "desc": "Command-line arguments of the script.",
  "group": "re, json, datetime, pathlib",
  "ex": "import sys\nprint(type(sys.argv).__name__)",
  "out": "list",
  "lesson": "py-stdlib"
 },
 {
  "name": "__init__",
  "sig": "def __init__(self, ...)",
  "desc": "Initialiser: runs when an object is created.",
  "group": "dunder & classes",
  "ex": "class P:\n    def __init__(self, n):\n        self.n = n\nprint(P(3).n)",
  "out": "3",
  "lesson": "py-classes"
 },
 {
  "name": "__str__",
  "sig": "def __str__(self)",
  "desc": "Text shown by print() / str().",
  "group": "dunder & classes",
  "ex": "class P:\n    def __str__(self):\n        return \"P!\"\nprint(P())",
  "out": "P!",
  "lesson": "py-inheritance"
 },
 {
  "name": "__repr__",
  "sig": "def __repr__(self)",
  "desc": "Unambiguous text for debugging.",
  "group": "dunder & classes",
  "ex": "class P:\n    def __repr__(self):\n        return \"P()\"\nprint([P()])",
  "out": "[P()]",
  "lesson": "py-inheritance"
 },
 {
  "name": "__eq__",
  "sig": "def __eq__(self, other)",
  "desc": "Defines ==.",
  "group": "dunder & classes",
  "ex": "class P:\n    def __init__(self, n):\n        self.n = n\n    def __eq__(self, o):\n        return self.n == o.n\nprint(P(1) == P(1))",
  "out": "True",
  "lesson": "py-inheritance"
 },
 {
  "name": "__lt__",
  "sig": "def __lt__(self, other)",
  "desc": "Defines < (enables sorting).",
  "group": "dunder & classes",
  "ex": "class P:\n    def __init__(self, n):\n        self.n = n\n    def __lt__(self, o):\n        return self.n < o.n\nprint(sorted([P(2), P(1)])[0].n)",
  "out": "1",
  "lesson": "py-inheritance"
 },
 {
  "name": "__add__",
  "sig": "def __add__(self, other)",
  "desc": "Defines +.",
  "group": "dunder & classes",
  "ex": "class V:\n    def __init__(self, x):\n        self.x = x\n    def __add__(self, o):\n        return V(self.x + o.x)\nprint((V(1) + V(2)).x)",
  "out": "3",
  "lesson": "py-inheritance"
 },
 {
  "name": "__len__",
  "sig": "def __len__(self)",
  "desc": "Defines len(obj).",
  "group": "dunder & classes",
  "ex": "class B:\n    def __len__(self):\n        return 3\nprint(len(B()))",
  "out": "3",
  "lesson": "py-inheritance"
 },
 {
  "name": "__getitem__",
  "sig": "def __getitem__(self, key)",
  "desc": "Defines obj[key] (and iteration fallback).",
  "group": "dunder & classes",
  "ex": "class B:\n    def __getitem__(self, i):\n        return i * 2\nprint(B()[4])",
  "out": "8",
  "lesson": "py-inheritance"
 },
 {
  "name": "__iter__",
  "sig": "def __iter__(self)",
  "desc": "Makes an object iterable.",
  "group": "dunder & classes",
  "ex": "class C:\n    def __iter__(self):\n        yield 1\n        yield 2\nprint(list(C()))",
  "out": "[1, 2]",
  "lesson": "py-loops"
 },
 {
  "name": "__call__",
  "sig": "def __call__(self, ...)",
  "desc": "Makes an instance callable like a function.",
  "group": "dunder & classes",
  "ex": "class Adder:\n    def __init__(self, n):\n        self.n = n\n    def __call__(self, x):\n        return x + self.n\nprint(Adder(5)(1))",
  "out": "6",
  "lesson": "py-functions"
 },
 {
  "name": "__enter__",
  "sig": "def __enter__ / __exit__",
  "desc": "Make an object a context manager.",
  "group": "dunder & classes",
  "ex": "class T:\n    def __enter__(self):\n        print(\"in\")\n        return self\n    def __exit__(self, *a):\n        print(\"out\")\nwith T():\n    print(\"body\")",
  "out": "in\nbody\nout",
  "lesson": "py-files"
 },
 {
  "name": "__slots__",
  "sig": "__slots__ = (\"a\", \"b\")",
  "desc": "Restrict attributes to save memory.",
  "group": "dunder & classes",
  "ex": "class P:\n    __slots__ = (\"a\",)\ntry:\n    P().b = 1\nexcept AttributeError:\n    print(\"no b\")",
  "out": "no b",
  "lesson": "py-functions"
 },
 {
  "name": "dataclasses.dataclass",
  "sig": "@dataclass",
  "desc": "Auto-generate __init__, __repr__, __eq__.",
  "group": "dunder & classes",
  "ex": "from dataclasses import dataclass\n@dataclass\nclass P:\n    x: int\n    y: int = 0\nprint(P(1), P(1) == P(1))",
  "out": "P(x=1, y=0) True",
  "lesson": "py-classes"
 },
 {
  "name": "abc.ABC",
  "sig": "class Base(ABC)",
  "desc": "Declare an abstract base class.",
  "group": "dunder & classes",
  "ex": "from abc import ABC, abstractmethod\nclass S(ABC):\n    @abstractmethod\n    def area(self): ...\ntry:\n    S()\nexcept TypeError:\n    print(\"abstract\")",
  "out": "abstract",
  "lesson": "py-inheritance"
 },
 {
  "name": "enum.Enum",
  "sig": "class C(Enum)",
  "desc": "A set of named constants.",
  "group": "dunder & classes",
  "ex": "from enum import Enum\nclass C(Enum):\n    RED = 1\n    BLUE = 2\nprint(C.RED.name, C(2))",
  "out": "RED C.BLUE",
  "lesson": "py-classes"
 },
 {
  "name": "contextlib.contextmanager",
  "sig": "@contextmanager",
  "desc": "Build a context manager from a generator.",
  "group": "dunder & classes",
  "ex": "from contextlib import contextmanager\n@contextmanager\ndef box():\n    print(\"open\")\n    yield\n    print(\"close\")\nwith box():\n    print(\"inside\")",
  "out": "open\ninside\nclose",
  "lesson": "py-files"
 },
 {
  "name": "typing.Optional",
  "sig": "Optional[T]",
  "desc": "A type hint meaning T or None.",
  "group": "dunder & classes",
  "ex": "from typing import Optional\ndef f(x: Optional[int] = None) -> int:\n    return x or 0\nprint(f(), f.__annotations__[\"x\"])",
  "out": "0 typing.Optional[int]",
  "lesson": "py-functions"
 },
 {
  "name": "asyncio.run",
  "sig": "asyncio.run(coro)",
  "desc": "Run an async function to completion.",
  "group": "dunder & classes",
  "ex": "import asyncio\nasync def hi():\n    await asyncio.sleep(0)\n    return \"done\"\nprint(asyncio.run(hi()))",
  "out": "done",
  "lesson": "py-functions"
 },
 {
  "name": "heapq.heappush",
  "sig": "heapq.heappush(heap, x)",
  "desc": "Push onto a min-heap (use with heappop).",
  "group": "dunder & classes",
  "ex": "import heapq\nh = []\nfor n in [5, 1, 3]:\n    heapq.heappush(h, n)\nprint(heapq.heappop(h), heapq.heappop(h))",
  "out": "1 3",
  "lesson": "py-lists"
 },
 {
  "name": "bisect.bisect_left",
  "sig": "bisect.bisect_left(a, x)",
  "desc": "Insertion point in a sorted list.",
  "group": "dunder & classes",
  "ex": "import bisect\nprint(bisect.bisect_left([1, 3, 5, 7], 5))",
  "out": "2",
  "lesson": "py-lists"
 }
];
})(typeof window !== 'undefined' ? window : globalThis);
