// GENERATED by tools/build-reference.js from tools/reference-src/r.js. Do not edit by hand.
(function (root) {
  'use strict';
  const LP = (root.LP = root.LP || {});
  (LP.reference = LP.reference || {}).r = [
 {
  "name": "c",
  "sig": "c(...)",
  "desc": "Combine values into a vector.",
  "group": "Vectors",
  "ex": "c(1, 2, 3)",
  "out": "[1] 1 2 3",
  "lesson": "r-vectors"
 },
 {
  "name": "length",
  "sig": "length(x)",
  "desc": "Number of elements.",
  "group": "Vectors",
  "ex": "length(c(\"a\", \"b\", \"c\"))",
  "out": "[1] 3",
  "lesson": "r-vectors"
 },
 {
  "name": "seq",
  "sig": "seq(from, to, by, length.out)",
  "desc": "Generate a sequence.",
  "group": "Vectors",
  "ex": "seq(0, 1, by = 0.25)",
  "out": "[1] 0.00 0.25 0.50 0.75 1.00",
  "lesson": "r-vectors"
 },
 {
  "name": "seq_len",
  "sig": "seq_len(n)",
  "desc": "The integers 1..n (safe for n = 0).",
  "group": "Vectors",
  "ex": "seq_len(4)",
  "out": "[1] 1 2 3 4",
  "lesson": "r-iteration"
 },
 {
  "name": "seq_along",
  "sig": "seq_along(x)",
  "desc": "Indices of x.",
  "group": "Vectors",
  "ex": "seq_along(c(\"a\", \"b\"))",
  "out": "[1] 1 2",
  "lesson": "r-iteration"
 },
 {
  "name": "rep",
  "sig": "rep(x, times, each)",
  "desc": "Repeat values.",
  "group": "Vectors",
  "ex": "rep(c(\"a\", \"b\"), times = 2, each = 2)",
  "out": "[1] \"a\" \"a\" \"b\" \"b\" \"a\" \"a\" \"b\" \"b\"",
  "lesson": "r-vectors"
 },
 {
  "name": "rev",
  "sig": "rev(x)",
  "desc": "Reverse.",
  "group": "Vectors",
  "ex": "rev(1:4)",
  "out": "[1] 4 3 2 1",
  "lesson": "r-vectors"
 },
 {
  "name": "sort",
  "sig": "sort(x, decreasing = FALSE)",
  "desc": "Sorted copy.",
  "group": "Vectors",
  "ex": "sort(c(3, 1, 2), decreasing = TRUE)",
  "out": "[1] 3 2 1",
  "lesson": "r-vectors"
 },
 {
  "name": "order",
  "sig": "order(..., decreasing = FALSE)",
  "desc": "Permutation that sorts (use to reorder rows).",
  "group": "Vectors",
  "ex": "order(c(30, 10, 20))",
  "out": "[1] 2 3 1",
  "lesson": "r-dataframes"
 },
 {
  "name": "rank",
  "sig": "rank(x)",
  "desc": "Ranks of the values (ties averaged).",
  "group": "Vectors",
  "ex": "rank(c(10, 30, 20, 20))",
  "out": "[1] 1.0 4.0 2.5 2.5",
  "lesson": "r-stats"
 },
 {
  "name": "which",
  "sig": "which(cond)",
  "desc": "Indices where TRUE.",
  "group": "Vectors",
  "ex": "which(c(5, 12, 7, 20) > 6)",
  "out": "[1] 2 3 4",
  "lesson": "r-vectors"
 },
 {
  "name": "which.max",
  "sig": "which.max(x)",
  "desc": "Index of the largest value.",
  "group": "Vectors",
  "ex": "which.max(c(3, 9, 2))",
  "out": "[1] 2",
  "lesson": "r-vectors"
 },
 {
  "name": "which.min",
  "sig": "which.min(x)",
  "desc": "Index of the smallest value.",
  "group": "Vectors",
  "ex": "which.min(c(3, 9, 2))",
  "out": "[1] 3",
  "lesson": "r-vectors"
 },
 {
  "name": "any",
  "sig": "any(...)",
  "desc": "Is at least one TRUE?",
  "group": "Vectors",
  "ex": "any(c(1, 5) > 4)",
  "out": "[1] TRUE",
  "lesson": "r-vectors"
 },
 {
  "name": "all",
  "sig": "all(...)",
  "desc": "Are all TRUE?",
  "group": "Vectors",
  "ex": "all(c(1, 5) > 0)",
  "out": "[1] TRUE",
  "lesson": "r-vectors"
 },
 {
  "name": "ifelse",
  "sig": "ifelse(test, yes, no)",
  "desc": "Vectorised if/else.",
  "group": "Vectors",
  "ex": "ifelse(c(1, 5, 10) > 4, \"big\", \"small\")",
  "out": "[1] \"small\" \"big\"   \"big\"",
  "lesson": "r-functions"
 },
 {
  "name": "unique",
  "sig": "unique(x)",
  "desc": "Distinct values.",
  "group": "Vectors",
  "ex": "unique(c(1, 2, 2, 3, 1))",
  "out": "[1] 1 2 3",
  "lesson": "r-vectors"
 },
 {
  "name": "duplicated",
  "sig": "duplicated(x)",
  "desc": "TRUE for repeats.",
  "group": "Vectors",
  "ex": "duplicated(c(\"a\", \"b\", \"a\"))",
  "out": "[1] FALSE FALSE  TRUE",
  "lesson": "r-dataframes"
 },
 {
  "name": "head",
  "sig": "head(x, n = 6)",
  "desc": "First n elements/rows.",
  "group": "Vectors",
  "ex": "head(letters, 3)",
  "out": "[1] \"a\" \"b\" \"c\"",
  "lesson": "r-dataframes"
 },
 {
  "name": "tail",
  "sig": "tail(x, n = 6)",
  "desc": "Last n elements/rows.",
  "group": "Vectors",
  "ex": "tail(letters, 3)",
  "out": "[1] \"x\" \"y\" \"z\"",
  "lesson": "r-dataframes"
 },
 {
  "name": "append",
  "sig": "append(x, values, after)",
  "desc": "Insert values into a vector.",
  "group": "Vectors",
  "ex": "append(1:3, 99, after = 1)",
  "out": "[1]  1 99  2  3",
  "lesson": "r-vectors"
 },
 {
  "name": "setdiff",
  "sig": "setdiff(x, y)",
  "desc": "Elements of x not in y.",
  "group": "Vectors",
  "ex": "setdiff(1:5, c(2, 4))",
  "out": "[1] 1 3 5",
  "lesson": "r-vectors"
 },
 {
  "name": "union",
  "sig": "union(x, y)",
  "desc": "All distinct elements.",
  "group": "Vectors",
  "ex": "union(c(1, 2), c(2, 3))",
  "out": "[1] 1 2 3",
  "lesson": "r-vectors"
 },
 {
  "name": "intersect",
  "sig": "intersect(x, y)",
  "desc": "Elements in both.",
  "group": "Vectors",
  "ex": "intersect(1:5, 4:8)",
  "out": "[1] 4 5",
  "lesson": "r-vectors"
 },
 {
  "name": "%in%",
  "sig": "x %in% table",
  "desc": "Membership test.",
  "group": "Vectors",
  "ex": "c(\"a\", \"z\") %in% letters[1:3]",
  "out": "[1]  TRUE FALSE",
  "lesson": "r-vectors"
 },
 {
  "name": "match",
  "sig": "match(x, table)",
  "desc": "Position of each x in table.",
  "group": "Vectors",
  "ex": "match(c(\"b\", \"z\"), c(\"a\", \"b\"))",
  "out": "[1]  2 NA",
  "lesson": "r-vectors"
 },
 {
  "name": "names",
  "sig": "names(x)",
  "desc": "Get or set element names.",
  "group": "Vectors",
  "ex": "x <- c(a = 1, b = 2)\nnames(x)",
  "out": "[1] \"a\" \"b\"",
  "lesson": "r-vectors"
 },
 {
  "name": "is.na",
  "sig": "is.na(x)",
  "desc": "Missing-value test.",
  "group": "Vectors",
  "ex": "is.na(c(1, NA, 3))",
  "out": "[1] FALSE  TRUE FALSE",
  "lesson": "r-stats"
 },
 {
  "name": "vector",
  "sig": "vector(mode, length)",
  "desc": "Create an empty vector of a type.",
  "group": "Vectors",
  "ex": "vector(\"numeric\", 3)",
  "out": "[1] 0 0 0",
  "lesson": "r-vectors"
 },
 {
  "name": "numeric",
  "sig": "numeric(n)",
  "desc": "A zero-filled numeric vector (preallocate!).",
  "group": "Vectors",
  "ex": "numeric(3)",
  "out": "[1] 0 0 0",
  "lesson": "r-functions"
 },
 {
  "name": "character",
  "sig": "character(n)",
  "desc": "A vector of empty strings.",
  "group": "Vectors",
  "ex": "character(2)",
  "out": "[1] \"\" \"\"",
  "lesson": "r-vectors"
 },
 {
  "name": "logical",
  "sig": "logical(n)",
  "desc": "A vector of FALSE.",
  "group": "Vectors",
  "ex": "logical(2)",
  "out": "[1] FALSE FALSE",
  "lesson": "r-vectors"
 },
 {
  "name": "integer",
  "sig": "integer(n)",
  "desc": "A zero-filled integer vector.",
  "group": "Vectors",
  "ex": "integer(2)",
  "out": "[1] 0 0",
  "lesson": "r-vectors"
 },
 {
  "name": "typeof",
  "sig": "typeof(x)",
  "desc": "Internal type.",
  "group": "Vectors",
  "ex": "typeof(1L); typeof(1); typeof(\"a\")",
  "out": "[1] \"integer\"\n[1] \"double\"\n[1] \"character\"",
  "lesson": "r-vectors"
 },
 {
  "name": "class",
  "sig": "class(x)",
  "desc": "The class(es) of an object.",
  "group": "Vectors",
  "ex": "class(1:2); class(mtcars)",
  "out": "[1] \"integer\"\n[1] \"data.frame\"",
  "lesson": "r-s3"
 },
 {
  "name": "is.numeric",
  "sig": "is.numeric(x)",
  "desc": "Test for numeric.",
  "group": "Vectors",
  "ex": "is.numeric(1L); is.numeric(\"1\")",
  "out": "[1] TRUE\n[1] FALSE",
  "lesson": "r-vectors"
 },
 {
  "name": "as.numeric",
  "sig": "as.numeric(x)",
  "desc": "Convert to numeric.",
  "group": "Vectors",
  "ex": "as.numeric(c(\"1.5\", \"2\"))",
  "out": "[1] 1.5 2.0",
  "lesson": "r-vectors"
 },
 {
  "name": "as.integer",
  "sig": "as.integer(x)",
  "desc": "Convert to integer (truncates).",
  "group": "Vectors",
  "ex": "as.integer(3.9)",
  "out": "[1] 3",
  "lesson": "r-vectors"
 },
 {
  "name": "as.character",
  "sig": "as.character(x)",
  "desc": "Convert to text.",
  "group": "Vectors",
  "ex": "as.character(c(1, 2.5))",
  "out": "[1] \"1\"   \"2.5\"",
  "lesson": "r-vectors"
 },
 {
  "name": "as.logical",
  "sig": "as.logical(x)",
  "desc": "Convert to TRUE/FALSE.",
  "group": "Vectors",
  "ex": "as.logical(c(\"TRUE\", \"no\", \"T\"))",
  "out": "[1] TRUE   NA TRUE",
  "lesson": "r-vectors"
 },
 {
  "name": "identical",
  "sig": "identical(x, y)",
  "desc": "Exactly the same?",
  "group": "Vectors",
  "ex": "identical(c(1, 2), c(1, 2))",
  "out": "[1] TRUE",
  "lesson": "r-vectors"
 },
 {
  "name": "all.equal",
  "sig": "all.equal(x, y)",
  "desc": "Equal within tolerance (use for floats).",
  "group": "Vectors",
  "ex": "isTRUE(all.equal(0.1 + 0.2, 0.3))",
  "out": "[1] TRUE",
  "lesson": "r-vectors"
 },
 {
  "name": "cumsum",
  "sig": "cumsum(x)",
  "desc": "Running total.",
  "group": "Vectors",
  "ex": "cumsum(1:5)",
  "out": "[1]  1  3  6 10 15",
  "lesson": "r-stats"
 },
 {
  "name": "cumprod",
  "sig": "cumprod(x)",
  "desc": "Running product.",
  "group": "Vectors",
  "ex": "cumprod(1:5)",
  "out": "[1]   1   2   6  24 120",
  "lesson": "r-stats"
 },
 {
  "name": "cummax",
  "sig": "cummax(x)",
  "desc": "Running maximum.",
  "group": "Vectors",
  "ex": "cummax(c(1, 3, 2, 5, 4))",
  "out": "[1] 1 3 3 5 5",
  "lesson": "r-functions"
 },
 {
  "name": "cummin",
  "sig": "cummin(x)",
  "desc": "Running minimum.",
  "group": "Vectors",
  "ex": "cummin(c(5, 3, 4, 1))",
  "out": "[1] 5 3 3 1",
  "lesson": "r-functions"
 },
 {
  "name": "diff",
  "sig": "diff(x, lag = 1)",
  "desc": "Differences between neighbours.",
  "group": "Vectors",
  "ex": "diff(c(1, 4, 9, 16))",
  "out": "[1] 3 5 7",
  "lesson": "r-stats"
 },
 {
  "name": "outer",
  "sig": "outer(X, Y, FUN)",
  "desc": "Apply a function to all pairs.",
  "group": "Vectors",
  "ex": "outer(1:3, 1:3)",
  "out": "     [,1] [,2] [,3]\n[1,]    1    2    3\n[2,]    2    4    6\n[3,]    3    6    9",
  "lesson": "r-functions"
 },
 {
  "name": "sum",
  "sig": "sum(..., na.rm = FALSE)",
  "desc": "Total.",
  "group": "Math & summary",
  "ex": "sum(1:10)",
  "out": "[1] 55",
  "lesson": "r-stats"
 },
 {
  "name": "mean",
  "sig": "mean(x, na.rm = FALSE)",
  "desc": "Arithmetic mean.",
  "group": "Math & summary",
  "ex": "mean(c(1, 2, 3, NA), na.rm = TRUE)",
  "out": "[1] 2",
  "lesson": "r-stats"
 },
 {
  "name": "median",
  "sig": "median(x)",
  "desc": "Middle value.",
  "group": "Math & summary",
  "ex": "median(c(1, 3, 2, 100))",
  "out": "[1] 2.5",
  "lesson": "r-stats"
 },
 {
  "name": "var",
  "sig": "var(x)",
  "desc": "Sample variance.",
  "group": "Math & summary",
  "ex": "var(c(1, 2, 3, 4))",
  "out": "[1] 1.666667",
  "lesson": "r-stats"
 },
 {
  "name": "sd",
  "sig": "sd(x)",
  "desc": "Sample standard deviation.",
  "group": "Math & summary",
  "ex": "round(sd(c(2, 4, 4, 4, 5, 5, 7, 9)), 4)",
  "out": "[1] 2.1381",
  "lesson": "r-stats"
 },
 {
  "name": "min",
  "sig": "min(...)",
  "desc": "Smallest value.",
  "group": "Math & summary",
  "ex": "min(4, 2, 8)",
  "out": "[1] 2",
  "lesson": "r-stats"
 },
 {
  "name": "max",
  "sig": "max(...)",
  "desc": "Largest value.",
  "group": "Math & summary",
  "ex": "max(4, 2, 8)",
  "out": "[1] 8",
  "lesson": "r-stats"
 },
 {
  "name": "range",
  "sig": "range(x)",
  "desc": "Smallest and largest.",
  "group": "Math & summary",
  "ex": "range(c(5, 1, 9))",
  "out": "[1] 1 9",
  "lesson": "r-stats"
 },
 {
  "name": "pmin",
  "sig": "pmin(a, b)",
  "desc": "Element-wise minimum.",
  "group": "Math & summary",
  "ex": "pmin(c(1, 5), c(3, 2))",
  "out": "[1] 1 2",
  "lesson": "r-stats"
 },
 {
  "name": "pmax",
  "sig": "pmax(a, b)",
  "desc": "Element-wise maximum.",
  "group": "Math & summary",
  "ex": "pmax(c(1, 5), c(3, 2))",
  "out": "[1] 3 5",
  "lesson": "r-stats"
 },
 {
  "name": "quantile",
  "sig": "quantile(x, probs)",
  "desc": "Percentiles.",
  "group": "Math & summary",
  "ex": "quantile(1:9, c(0.25, 0.5, 0.75))",
  "out": "25% 50% 75% \n  3   5   7",
  "lesson": "r-stats"
 },
 {
  "name": "IQR",
  "sig": "IQR(x)",
  "desc": "Interquartile range.",
  "group": "Math & summary",
  "ex": "IQR(1:9)",
  "out": "[1] 4",
  "lesson": "r-stats"
 },
 {
  "name": "summary",
  "sig": "summary(object)",
  "desc": "Quick summary of a vector, data frame or model.",
  "group": "Math & summary",
  "ex": "summary(c(1, 2, 3, 4, 100))",
  "out": "   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n      1       2       3      22       4     100",
  "lesson": "r-stats"
 },
 {
  "name": "fivenum",
  "sig": "fivenum(x)",
  "desc": "Tukey five-number summary.",
  "group": "Math & summary",
  "ex": "fivenum(1:9)",
  "out": "[1] 1 3 5 7 9",
  "lesson": "r-stats"
 },
 {
  "name": "scale",
  "sig": "scale(x)",
  "desc": "Centre and scale (z-scores).",
  "group": "Math & summary",
  "ex": "round(as.vector(scale(c(1, 2, 3))), 3)",
  "out": "[1] -1  0  1",
  "lesson": "r-stats"
 },
 {
  "name": "cor",
  "sig": "cor(x, y)",
  "desc": "Correlation.",
  "group": "Math & summary",
  "ex": "round(cor(mtcars$mpg, mtcars$wt), 4)",
  "out": "[1] -0.8677",
  "lesson": "r-stats"
 },
 {
  "name": "cov",
  "sig": "cov(x, y)",
  "desc": "Covariance.",
  "group": "Math & summary",
  "ex": "cov(1:5, c(2, 4, 6, 8, 10))",
  "out": "[1] 5",
  "lesson": "r-stats"
 },
 {
  "name": "table",
  "sig": "table(x, y)",
  "desc": "Frequency counts.",
  "group": "Math & summary",
  "ex": "table(c(\"a\", \"b\", \"a\", \"c\", \"a\"))",
  "out": "\na b c \n3 1 1",
  "lesson": "r-groups"
 },
 {
  "name": "prop.table",
  "sig": "prop.table(t)",
  "desc": "Proportions from a table.",
  "group": "Math & summary",
  "ex": "prop.table(table(c(\"a\", \"b\", \"a\", \"a\")))",
  "out": "\n   a    b \n0.75 0.25",
  "lesson": "r-groups"
 },
 {
  "name": "tabulate",
  "sig": "tabulate(bin)",
  "desc": "Count positive integers fast.",
  "group": "Math & summary",
  "ex": "tabulate(c(1, 2, 2, 5))",
  "out": "[1] 1 2 0 0 1",
  "lesson": "r-groups"
 },
 {
  "name": "round",
  "sig": "round(x, digits)",
  "desc": "Round (half to even).",
  "group": "Math & summary",
  "ex": "round(c(2.5, 3.5, 3.14159), 2)",
  "out": "[1] 2.50 3.50 3.14",
  "lesson": "r-stats"
 },
 {
  "name": "signif",
  "sig": "signif(x, digits)",
  "desc": "Significant digits.",
  "group": "Math & summary",
  "ex": "signif(123456, 2)",
  "out": "[1] 120000",
  "lesson": "r-stats"
 },
 {
  "name": "floor",
  "sig": "floor(x)",
  "desc": "Round down.",
  "group": "Math & summary",
  "ex": "floor(-1.5)",
  "out": "[1] -2",
  "lesson": "r-stats"
 },
 {
  "name": "ceiling",
  "sig": "ceiling(x)",
  "desc": "Round up.",
  "group": "Math & summary",
  "ex": "ceiling(1.2)",
  "out": "[1] 2",
  "lesson": "r-stats"
 },
 {
  "name": "trunc",
  "sig": "trunc(x)",
  "desc": "Drop the fraction.",
  "group": "Math & summary",
  "ex": "trunc(-2.7)",
  "out": "[1] -2",
  "lesson": "r-stats"
 },
 {
  "name": "abs",
  "sig": "abs(x)",
  "desc": "Absolute value.",
  "group": "Math & summary",
  "ex": "abs(c(-2, 3))",
  "out": "[1] 2 3",
  "lesson": "r-stats"
 },
 {
  "name": "sqrt",
  "sig": "sqrt(x)",
  "desc": "Square root.",
  "group": "Math & summary",
  "ex": "sqrt(c(4, 9))",
  "out": "[1] 2 3",
  "lesson": "r-stats"
 },
 {
  "name": "exp",
  "sig": "exp(x)",
  "desc": "e^x.",
  "group": "Math & summary",
  "ex": "round(exp(1), 5)",
  "out": "[1] 2.71828",
  "lesson": "r-stats"
 },
 {
  "name": "log",
  "sig": "log(x, base)",
  "desc": "Logarithm.",
  "group": "Math & summary",
  "ex": "log(8, base = 2)",
  "out": "[1] 3",
  "lesson": "r-stats"
 },
 {
  "name": "log10",
  "sig": "log10(x)",
  "desc": "Base-10 log.",
  "group": "Math & summary",
  "ex": "log10(1000)",
  "out": "[1] 3",
  "lesson": "r-stats"
 },
 {
  "name": "%%",
  "sig": "x %% y",
  "desc": "Modulo.",
  "group": "Math & summary",
  "ex": "17 %% 5",
  "out": "[1] 2",
  "lesson": "r-functions"
 },
 {
  "name": "%/%",
  "sig": "x %/% y",
  "desc": "Integer division.",
  "group": "Math & summary",
  "ex": "17 %/% 5",
  "out": "[1] 3",
  "lesson": "r-functions"
 },
 {
  "name": "choose",
  "sig": "choose(n, k)",
  "desc": "Binomial coefficient.",
  "group": "Math & summary",
  "ex": "choose(5, 2)",
  "out": "[1] 10",
  "lesson": "r-inference"
 },
 {
  "name": "factorial",
  "sig": "factorial(n)",
  "desc": "n!",
  "group": "Math & summary",
  "ex": "factorial(5)",
  "out": "[1] 120",
  "lesson": "r-inference"
 },
 {
  "name": "prod",
  "sig": "prod(x)",
  "desc": "Product.",
  "group": "Math & summary",
  "ex": "prod(1:5)",
  "out": "[1] 120",
  "lesson": "r-stats"
 },
 {
  "name": "rowSums",
  "sig": "rowSums(m)",
  "desc": "Row totals.",
  "group": "Math & summary",
  "ex": "rowSums(matrix(1:6, 2))",
  "out": "[1]  9 12",
  "lesson": "r-dataframes"
 },
 {
  "name": "colMeans",
  "sig": "colMeans(m)",
  "desc": "Column means.",
  "group": "Math & summary",
  "ex": "colMeans(matrix(1:6, 2))",
  "out": "[1] 1.5 3.5 5.5",
  "lesson": "r-dataframes"
 },
 {
  "name": "paste",
  "sig": "paste(..., sep = \" \", collapse)",
  "desc": "Join with separator (space by default).",
  "group": "Strings",
  "ex": "paste(\"a\", \"b\", sep = \"-\")",
  "out": "[1] \"a-b\"",
  "lesson": "r-strings"
 },
 {
  "name": "paste0",
  "sig": "paste0(...)",
  "desc": "Join with no separator.",
  "group": "Strings",
  "ex": "paste0(\"id\", 1:3)",
  "out": "[1] \"id1\" \"id2\" \"id3\"",
  "lesson": "r-strings"
 },
 {
  "name": "nchar",
  "sig": "nchar(x)",
  "desc": "Number of characters.",
  "group": "Strings",
  "ex": "nchar(c(\"a\", \"abc\", \"\"))",
  "out": "[1] 1 3 0",
  "lesson": "r-strings"
 },
 {
  "name": "toupper",
  "sig": "toupper(x)",
  "desc": "Upper-case.",
  "group": "Strings",
  "ex": "toupper(\"hi\")",
  "out": "[1] \"HI\"",
  "lesson": "r-strings"
 },
 {
  "name": "tolower",
  "sig": "tolower(x)",
  "desc": "Lower-case.",
  "group": "Strings",
  "ex": "tolower(\"HI\")",
  "out": "[1] \"hi\"",
  "lesson": "r-strings"
 },
 {
  "name": "substr",
  "sig": "substr(x, start, stop)",
  "desc": "Extract by position.",
  "group": "Strings",
  "ex": "substr(\"abcdef\", 2, 4)",
  "out": "[1] \"bcd\"",
  "lesson": "r-strings"
 },
 {
  "name": "substring",
  "sig": "substring(x, first, last)",
  "desc": "Vectorised substr.",
  "group": "Strings",
  "ex": "substring(\"abcdef\", 1:3, 3:5)",
  "out": "[1] \"abc\" \"bcd\" \"cde\"",
  "lesson": "r-strings"
 },
 {
  "name": "strsplit",
  "sig": "strsplit(x, split)",
  "desc": "Split text (returns a list).",
  "group": "Strings",
  "ex": "strsplit(\"a,b,c\", \",\")[[1]]",
  "out": "[1] \"a\" \"b\" \"c\"",
  "lesson": "r-strings"
 },
 {
  "name": "gsub",
  "sig": "gsub(pattern, repl, x)",
  "desc": "Replace all matches (regex).",
  "group": "Strings",
  "ex": "gsub(\"[aeiou]\", \"_\", \"education\")",
  "out": "[1] \"_d_c_t__n\"",
  "lesson": "r-strings"
 },
 {
  "name": "sub",
  "sig": "sub(pattern, repl, x)",
  "desc": "Replace the first match.",
  "group": "Strings",
  "ex": "sub(\"a\", \"A\", \"banana\")",
  "out": "[1] \"bAnana\"",
  "lesson": "r-strings"
 },
 {
  "name": "grepl",
  "sig": "grepl(pattern, x)",
  "desc": "Does it match? (logical)",
  "group": "Strings",
  "ex": "grepl(\"^a\", c(\"apple\", \"banana\"))",
  "out": "[1]  TRUE FALSE",
  "lesson": "r-strings"
 },
 {
  "name": "grep",
  "sig": "grep(pattern, x, value = FALSE)",
  "desc": "Indices (or values) of matches.",
  "group": "Strings",
  "ex": "grep(\"an\", c(\"apple\", \"banana\", \"mango\"), value = TRUE)",
  "out": "[1] \"banana\" \"mango\"",
  "lesson": "r-strings"
 },
 {
  "name": "regmatches",
  "sig": "regmatches(x, m)",
  "desc": "Extract the matched text.",
  "group": "Strings",
  "ex": "x <- \"a1b22c333\"\nregmatches(x, gregexpr(\"[0-9]+\", x))[[1]]",
  "out": "[1] \"1\"   \"22\"  \"333\"",
  "lesson": "r-strings"
 },
 {
  "name": "regexpr",
  "sig": "regexpr(pattern, x)",
  "desc": "Position of the first match.",
  "group": "Strings",
  "ex": "as.integer(regexpr(\"na\", \"banana\"))",
  "out": "[1] 3",
  "lesson": "r-strings"
 },
 {
  "name": "gregexpr",
  "sig": "gregexpr(pattern, x)",
  "desc": "Positions of all matches.",
  "group": "Strings",
  "ex": "as.integer(gregexpr(\"a\", \"banana\")[[1]])",
  "out": "[1] 2 4 6",
  "lesson": "r-strings"
 },
 {
  "name": "sprintf",
  "sig": "sprintf(fmt, ...)",
  "desc": "C-style formatting.",
  "group": "Strings",
  "ex": "sprintf(\"%s is %.1f%%\", \"rate\", 12.345)",
  "out": "[1] \"rate is 12.3%\"",
  "lesson": "r-strings"
 },
 {
  "name": "format",
  "sig": "format(x, nsmall, width, big.mark)",
  "desc": "Format for display.",
  "group": "Strings",
  "ex": "format(1234567.891, big.mark = \",\", nsmall = 2)",
  "out": "[1] \"1,234,567.89\"",
  "lesson": "r-strings"
 },
 {
  "name": "formatC",
  "sig": "formatC(x, width, flag, format)",
  "desc": "Flexible number formatting.",
  "group": "Strings",
  "ex": "formatC(7, width = 3, flag = \"0\")",
  "out": "[1] \"007\"",
  "lesson": "r-strings"
 },
 {
  "name": "trimws",
  "sig": "trimws(x)",
  "desc": "Trim whitespace.",
  "group": "Strings",
  "ex": "trimws(\"  hi  \")",
  "out": "[1] \"hi\"",
  "lesson": "r-strings"
 },
 {
  "name": "startsWith",
  "sig": "startsWith(x, prefix)",
  "desc": "Prefix test.",
  "group": "Strings",
  "ex": "startsWith(c(\"apple\", \"pear\"), \"ap\")",
  "out": "[1]  TRUE FALSE",
  "lesson": "r-strings"
 },
 {
  "name": "endsWith",
  "sig": "endsWith(x, suffix)",
  "desc": "Suffix test.",
  "group": "Strings",
  "ex": "endsWith(\"file.csv\", \".csv\")",
  "out": "[1] TRUE",
  "lesson": "r-strings"
 },
 {
  "name": "chartr",
  "sig": "chartr(old, new, x)",
  "desc": "Translate characters.",
  "group": "Strings",
  "ex": "chartr(\"abc\", \"xyz\", \"aabbcc\")",
  "out": "[1] \"xxyyzz\"",
  "lesson": "r-strings"
 },
 {
  "name": "casefold",
  "sig": "casefold(x, upper = FALSE)",
  "desc": "Change case.",
  "group": "Strings",
  "ex": "casefold(\"Hi\", upper = TRUE)",
  "out": "[1] \"HI\"",
  "lesson": "r-strings"
 },
 {
  "name": "reverse a string",
  "sig": "paste(rev(strsplit(x, \"\")[[1]]), collapse = \"\")",
  "desc": "Reverse a string.",
  "group": "Strings",
  "ex": "paste(rev(strsplit(\"stressed\", \"\")[[1]]), collapse = \"\")",
  "out": "[1] \"desserts\"",
  "lesson": "r-strings"
 },
 {
  "name": "toString",
  "sig": "toString(x)",
  "desc": "Collapse to a comma-separated string.",
  "group": "Strings",
  "ex": "toString(1:4)",
  "out": "[1] \"1, 2, 3, 4\"",
  "lesson": "r-strings"
 },
 {
  "name": "shQuote",
  "sig": "shQuote(x)",
  "desc": "Quote for the shell.",
  "group": "Strings",
  "ex": "shQuote(\"it works\")",
  "out": "[1] \"'it works'\"",
  "lesson": "r-strings"
 },
 {
  "name": "sQuote",
  "sig": "sQuote(x, q = FALSE)",
  "desc": "Single-quote text.",
  "group": "Strings",
  "ex": "sQuote(\"x\", FALSE)",
  "out": "[1] \"'x'\"",
  "lesson": "r-strings"
 },
 {
  "name": "strtoi",
  "sig": "strtoi(x, base)",
  "desc": "Text to integer in a base.",
  "group": "Strings",
  "ex": "strtoi(\"ff\", base = 16L)",
  "out": "[1] 255",
  "lesson": "r-strings"
 },
 {
  "name": "letters",
  "sig": "letters / LETTERS / month.name / pi",
  "desc": "Built-in character constants.",
  "group": "Strings",
  "ex": "head(letters, 3); month.name[1:2]",
  "out": "[1] \"a\" \"b\" \"c\"\n[1] \"January\"  \"February\"",
  "lesson": "r-strings"
 },
 {
  "name": "basename",
  "sig": "basename(path)",
  "desc": "File name part of a path.",
  "group": "Strings",
  "ex": "basename(\"a/b/c.txt\")",
  "out": "[1] \"c.txt\"",
  "lesson": "r-io"
 },
 {
  "name": "file.path",
  "sig": "file.path(...)",
  "desc": "Build a path.",
  "group": "Strings",
  "ex": "file.path(\"data\", \"x.csv\")",
  "out": "[1] \"data/x.csv\"",
  "lesson": "r-io"
 },
 {
  "name": "tools::toTitleCase",
  "sig": "tools::toTitleCase(x)",
  "desc": "Title Case.",
  "group": "Strings",
  "ex": "tools::toTitleCase(\"a tale of two cities\")",
  "out": "[1] \"a Tale of Two Cities\"",
  "lesson": "r-strings"
 },
 {
  "name": "factor",
  "sig": "factor(x, levels, labels)",
  "desc": "A categorical variable.",
  "group": "Factors & dates",
  "ex": "factor(c(\"lo\", \"hi\", \"lo\"), levels = c(\"lo\", \"hi\"))",
  "out": "[1] lo hi lo\nLevels: lo hi",
  "lesson": "r-vectors"
 },
 {
  "name": "levels",
  "sig": "levels(f)",
  "desc": "The categories.",
  "group": "Factors & dates",
  "ex": "levels(factor(c(\"b\", \"a\", \"b\")))",
  "out": "[1] \"a\" \"b\"",
  "lesson": "r-vectors"
 },
 {
  "name": "nlevels",
  "sig": "nlevels(f)",
  "desc": "Number of categories.",
  "group": "Factors & dates",
  "ex": "nlevels(factor(c(\"b\", \"a\", \"b\")))",
  "out": "[1] 2",
  "lesson": "r-vectors"
 },
 {
  "name": "droplevels",
  "sig": "droplevels(f)",
  "desc": "Remove unused levels.",
  "group": "Factors & dates",
  "ex": "levels(droplevels(factor(c(\"a\", \"b\"))[1]))",
  "out": "[1] \"a\"",
  "lesson": "r-vectors"
 },
 {
  "name": "cut",
  "sig": "cut(x, breaks, labels)",
  "desc": "Bin numbers into categories.",
  "group": "Factors & dates",
  "ex": "cut(c(1, 5, 10), breaks = c(0, 3, 7, 12), labels = c(\"low\", \"mid\", \"high\"))",
  "out": "[1] low  mid  high\nLevels: low mid high",
  "lesson": "r-vectors"
 },
 {
  "name": "relevel",
  "sig": "relevel(f, ref)",
  "desc": "Change the reference level.",
  "group": "Factors & dates",
  "ex": "levels(relevel(factor(c(\"a\", \"b\", \"c\")), ref = \"c\"))",
  "out": "[1] \"c\" \"a\" \"b\"",
  "lesson": "r-vectors"
 },
 {
  "name": "as.Date",
  "sig": "as.Date(x, format)",
  "desc": "Parse dates.",
  "group": "Factors & dates",
  "ex": "as.Date(\"2024-03-09\") + 30",
  "out": "[1] \"2024-04-08\"",
  "lesson": "r-dataframes"
 },
 {
  "name": "format.Date",
  "sig": "format(date, \"%d %B %Y\")",
  "desc": "Format a date.",
  "group": "Factors & dates",
  "ex": "format(as.Date(\"2024-03-09\"), \"%d %B %Y\")",
  "out": "[1] \"09 March 2024\"",
  "lesson": "r-dataframes"
 },
 {
  "name": "difftime",
  "sig": "difftime(a, b, units)",
  "desc": "Difference between dates/times.",
  "group": "Factors & dates",
  "ex": "difftime(as.Date(\"2024-03-09\"), as.Date(\"2024-03-01\"), units = \"days\")",
  "out": "Time difference of 8 days",
  "lesson": "r-dataframes"
 },
 {
  "name": "seq.Date",
  "sig": "seq(date, by, length.out)",
  "desc": "A sequence of dates.",
  "group": "Factors & dates",
  "ex": "seq(as.Date(\"2024-01-31\"), by = \"month\", length.out = 3)",
  "out": "[1] \"2024-01-31\" \"2024-03-02\" \"2024-03-31\"",
  "lesson": "r-dataframes"
 },
 {
  "name": "weekdays",
  "sig": "weekdays(date)",
  "desc": "Day names.",
  "group": "Factors & dates",
  "ex": "weekdays(as.Date(\"2024-03-09\"))",
  "out": "[1] \"Saturday\"",
  "lesson": "r-dataframes"
 },
 {
  "name": "months",
  "sig": "months(date)",
  "desc": "Month names.",
  "group": "Factors & dates",
  "ex": "months(as.Date(\"2024-03-09\"))",
  "out": "[1] \"March\"",
  "lesson": "r-dataframes"
 },
 {
  "name": "ISOdate",
  "sig": "ISOdate(y, m, d)",
  "desc": "Build a date-time.",
  "group": "Factors & dates",
  "ex": "format(ISOdate(2024, 3, 9), \"%Y-%m-%d\")",
  "out": "[1] \"2024-03-09\"",
  "lesson": "r-dataframes"
 },
 {
  "name": "as.POSIXct",
  "sig": "as.POSIXct(x, tz)",
  "desc": "Parse date-times.",
  "group": "Factors & dates",
  "ex": "format(as.POSIXct(\"2024-03-09 13:45:00\", tz = \"UTC\"), \"%H:%M\")",
  "out": "[1] \"13:45\"",
  "lesson": "r-dataframes"
 },
 {
  "name": "strftime",
  "sig": "strftime(x, format)",
  "desc": "Format a time.",
  "group": "Factors & dates",
  "ex": "strftime(as.Date(\"2024-03-09\"), \"%A\")",
  "out": "[1] \"Saturday\"",
  "lesson": "r-dataframes"
 },
 {
  "name": "list",
  "sig": "list(...)",
  "desc": "A container for anything.",
  "group": "Lists, apply & functional",
  "ex": "str(list(a = 1, b = \"x\"))",
  "out": "List of 2\n $ a: num 1\n $ b: chr \"x\"",
  "lesson": "r-vectors"
 },
 {
  "name": "unlist",
  "sig": "unlist(x)",
  "desc": "Flatten a list into a vector.",
  "group": "Lists, apply & functional",
  "ex": "unlist(list(a = 1, b = list(c = 2, d = 3)))",
  "out": "  a b.c b.d \n  1   2   3",
  "lesson": "r-vectors"
 },
 {
  "name": "lapply",
  "sig": "lapply(X, FUN)",
  "desc": "Apply to each element; returns a list.",
  "group": "Lists, apply & functional",
  "ex": "str(lapply(1:2, function(i) i^2))",
  "out": "List of 2\n $ : num 1\n $ : num 4",
  "lesson": "r-iteration"
 },
 {
  "name": "sapply",
  "sig": "sapply(X, FUN)",
  "desc": "Apply and simplify to a vector.",
  "group": "Lists, apply & functional",
  "ex": "sapply(1:4, function(i) i^2)",
  "out": "[1]  1  4  9 16",
  "lesson": "r-iteration"
 },
 {
  "name": "vapply",
  "sig": "vapply(X, FUN, FUN.VALUE)",
  "desc": "Like sapply with a checked result type.",
  "group": "Lists, apply & functional",
  "ex": "vapply(c(\"a\", \"bb\"), nchar, integer(1))",
  "out": " a bb \n 1  2",
  "lesson": "r-iteration"
 },
 {
  "name": "mapply",
  "sig": "mapply(FUN, ...)",
  "desc": "Apply over several vectors at once.",
  "group": "Lists, apply & functional",
  "ex": "mapply(function(a, b) a + b, 1:3, 4:6)",
  "out": "[1] 5 7 9",
  "lesson": "r-iteration"
 },
 {
  "name": "Map",
  "sig": "Map(f, ...)",
  "desc": "Like mapply, always a list.",
  "group": "Lists, apply & functional",
  "ex": "str(Map(function(a, b) a * b, 1:2, 3:4))",
  "out": "List of 2\n $ : int 3\n $ : int 8",
  "lesson": "r-iteration"
 },
 {
  "name": "Filter",
  "sig": "Filter(f, x)",
  "desc": "Keep elements where f is TRUE.",
  "group": "Lists, apply & functional",
  "ex": "Filter(function(n) n %% 2 == 0, 1:10)",
  "out": "[1]  2  4  6  8 10",
  "lesson": "r-iteration"
 },
 {
  "name": "Reduce",
  "sig": "Reduce(f, x, accumulate)",
  "desc": "Fold a vector with a function.",
  "group": "Lists, apply & functional",
  "ex": "Reduce(`+`, 1:5, accumulate = TRUE)",
  "out": "[1]  1  3  6 10 15",
  "lesson": "r-iteration"
 },
 {
  "name": "Position",
  "sig": "Position(f, x)",
  "desc": "Index of the first TRUE.",
  "group": "Lists, apply & functional",
  "ex": "Position(function(n) n > 3, c(1, 5, 2, 8))",
  "out": "[1] 2",
  "lesson": "r-iteration"
 },
 {
  "name": "Find",
  "sig": "Find(f, x)",
  "desc": "First element where f is TRUE.",
  "group": "Lists, apply & functional",
  "ex": "Find(function(n) n > 3, c(1, 5, 2, 8))",
  "out": "[1] 5",
  "lesson": "r-iteration"
 },
 {
  "name": "do.call",
  "sig": "do.call(f, args)",
  "desc": "Call a function with a list of arguments.",
  "group": "Lists, apply & functional",
  "ex": "do.call(rbind, list(1:2, 3:4))",
  "out": "     [,1] [,2]\n[1,]    1    2\n[2,]    3    4",
  "lesson": "r-functions"
 },
 {
  "name": "Recall",
  "sig": "Recall(...)",
  "desc": "Call the current function recursively.",
  "group": "Lists, apply & functional",
  "ex": "(function(n) if (n <= 1) 1 else n * Recall(n - 1))(5)",
  "out": "[1] 120",
  "lesson": "r-iteration"
 },
 {
  "name": "Vectorize",
  "sig": "Vectorize(f)",
  "desc": "Make a scalar function work on vectors.",
  "group": "Lists, apply & functional",
  "ex": "f <- Vectorize(function(a, b) if (a > b) a else b)\nf(1:3, c(2, 2, 2))",
  "out": "[1] 2 2 3",
  "lesson": "r-functions"
 },
 {
  "name": "tapply",
  "sig": "tapply(X, INDEX, FUN)",
  "desc": "Apply by group.",
  "group": "Lists, apply & functional",
  "ex": "tapply(c(1, 2, 3, 4), c(\"a\", \"b\", \"a\", \"b\"), sum)",
  "out": "a b \n4 6",
  "lesson": "r-groups"
 },
 {
  "name": "apply",
  "sig": "apply(X, MARGIN, FUN)",
  "desc": "Apply over matrix rows (1) or columns (2).",
  "group": "Lists, apply & functional",
  "ex": "apply(matrix(1:6, 2), 1, sum)",
  "out": "[1]  9 12",
  "lesson": "r-dataframes"
 },
 {
  "name": "split",
  "sig": "split(x, f)",
  "desc": "Split by group.",
  "group": "Lists, apply & functional",
  "ex": "str(split(1:6, c(\"a\", \"b\", \"a\", \"b\", \"a\", \"b\")))",
  "out": "List of 2\n $ a: int [1:3] 1 3 5\n $ b: int [1:3] 2 4 6",
  "lesson": "r-groups"
 },
 {
  "name": "rapply",
  "sig": "rapply(object, f)",
  "desc": "Recursively apply to a nested list.",
  "group": "Lists, apply & functional",
  "ex": "unlist(rapply(list(1, list(2, 3)), function(x) x * 10, how = \"list\"))",
  "out": "[1] 10 20 30",
  "lesson": "r-iteration"
 },
 {
  "name": "setNames",
  "sig": "setNames(x, names)",
  "desc": "Name a vector in one call.",
  "group": "Lists, apply & functional",
  "ex": "setNames(1:3, c(\"a\", \"b\", \"c\"))",
  "out": "a b c \n1 2 3",
  "lesson": "r-vectors"
 },
 {
  "name": "stack",
  "sig": "stack(list)",
  "desc": "List to long data frame.",
  "group": "Lists, apply & functional",
  "ex": "stack(list(a = 1:2, b = 3))",
  "out": "  values ind\n1      1   a\n2      2   a\n3      3   b",
  "lesson": "r-dataframes"
 },
 {
  "name": "array",
  "sig": "array(data, dim)",
  "desc": "N-dimensional array.",
  "group": "Lists, apply & functional",
  "ex": "dim(array(1:24, c(2, 3, 4)))",
  "out": "[1] 2 3 4",
  "lesson": "r-dataframes"
 },
 {
  "name": "lengths",
  "sig": "lengths(x)",
  "desc": "Length of every list element.",
  "group": "Lists, apply & functional",
  "ex": "lengths(list(1:3, \"a\", NULL))",
  "out": "[1] 3 1 0",
  "lesson": "r-vectors"
 },
 {
  "name": "if / else",
  "sig": "if (cond) a else b",
  "desc": "Conditional expression.",
  "group": "Control flow & functions",
  "ex": "x <- 5\nif (x > 3) \"big\" else \"small\"",
  "out": "[1] \"big\"",
  "lesson": "r-functions"
 },
 {
  "name": "switch",
  "sig": "switch(x, a = ..., b = ...)",
  "desc": "Choose by name or number.",
  "group": "Control flow & functions",
  "ex": "switch(\"b\", a = \"first\", b = \"second\", \"other\")",
  "out": "[1] \"second\"",
  "lesson": "r-functions"
 },
 {
  "name": "for",
  "sig": "for (i in x) { ... }",
  "desc": "Loop over elements.",
  "group": "Control flow & functions",
  "ex": "for (i in 1:3) cat(i, \"\")\ncat(\"\\n\")",
  "out": "1 2 3",
  "lesson": "r-iteration"
 },
 {
  "name": "while",
  "sig": "while (cond) { ... }",
  "desc": "Loop while TRUE.",
  "group": "Control flow & functions",
  "ex": "i <- 1\nwhile (i < 20) i <- i * 2\ni",
  "out": "[1] 32",
  "lesson": "r-iteration"
 },
 {
  "name": "repeat",
  "sig": "repeat { ... break }",
  "desc": "Loop until break.",
  "group": "Control flow & functions",
  "ex": "n <- 0\nrepeat { n <- n + 1; if (n == 4) break }\nn",
  "out": "[1] 4",
  "lesson": "r-functions"
 },
 {
  "name": "function",
  "sig": "function(args) body",
  "desc": "Define a function.",
  "group": "Control flow & functions",
  "ex": "sq <- function(x, p = 2) x^p\nsq(3)",
  "out": "[1] 9",
  "lesson": "r-functions"
 },
 {
  "name": "return",
  "sig": "return(value)",
  "desc": "Return early.",
  "group": "Control flow & functions",
  "ex": "f <- function(x) { if (x < 0) return(\"neg\"); \"ok\" }\nf(-1)",
  "out": "[1] \"neg\"",
  "lesson": "r-functions"
 },
 {
  "name": "missing",
  "sig": "missing(arg)",
  "desc": "Was the argument supplied?",
  "group": "Control flow & functions",
  "ex": "f <- function(a, b) if (missing(b)) \"no b\" else \"b given\"\nf(1)",
  "out": "[1] \"no b\"",
  "lesson": "r-functions"
 },
 {
  "name": "match.arg",
  "sig": "match.arg(arg)",
  "desc": "Validate against allowed choices.",
  "group": "Control flow & functions",
  "ex": "f <- function(type = c(\"mean\", \"median\")) match.arg(type)\nf(\"med\")",
  "out": "[1] \"median\"",
  "lesson": "r-functions"
 },
 {
  "name": "on.exit",
  "sig": "on.exit(expr)",
  "desc": "Run cleanup when the function ends.",
  "group": "Control flow & functions",
  "ex": "f <- function() { on.exit(cat(\"bye\\n\")); cat(\"hi\\n\") }\nf()",
  "out": "hi\nbye",
  "lesson": "r-functions"
 },
 {
  "name": "stopifnot",
  "sig": "stopifnot(...)",
  "desc": "Error unless every condition is TRUE.",
  "group": "Control flow & functions",
  "ex": "tryCatch(stopifnot(1 == 2), error = function(e) conditionMessage(e))",
  "out": "[1] \"1 == 2 is not TRUE\"",
  "lesson": "r-errors"
 },
 {
  "name": "stop",
  "sig": "stop(msg)",
  "desc": "Signal an error.",
  "group": "Control flow & functions",
  "ex": "tryCatch(stop(\"boom\"), error = function(e) conditionMessage(e))",
  "out": "[1] \"boom\"",
  "lesson": "r-errors"
 },
 {
  "name": "warning",
  "sig": "warning(msg)",
  "desc": "Signal a warning.",
  "group": "Control flow & functions",
  "ex": "withCallingHandlers(warning(\"careful\"), warning = function(w) { cat(\"caught:\", conditionMessage(w), \"\\n\"); invokeRestart(\"muffleWarning\") })",
  "out": "caught: careful",
  "lesson": "r-errors"
 },
 {
  "name": "tryCatch",
  "sig": "tryCatch(expr, error =, finally =)",
  "desc": "Handle conditions.",
  "group": "Control flow & functions",
  "ex": "tryCatch(log(-1), warning = function(w) \"NaN warning\", finally = cat(\"done\\n\"))",
  "out": "done\n[1] \"NaN warning\"",
  "lesson": "r-errors"
 },
 {
  "name": "try",
  "sig": "try(expr, silent = TRUE)",
  "desc": "Run and swallow errors.",
  "group": "Control flow & functions",
  "ex": "r <- try(stop(\"x\"), silent = TRUE)\nclass(r)",
  "out": "[1] \"try-error\"",
  "lesson": "r-errors"
 },
 {
  "name": "message",
  "sig": "message(...)",
  "desc": "Informational message (stderr).",
  "group": "Control flow & functions",
  "ex": "suppressMessages(message(\"hello\"))\n\"ok\"",
  "out": "[1] \"ok\"",
  "lesson": "r-errors"
 },
 {
  "name": "invisible",
  "sig": "invisible(x)",
  "desc": "Return without printing.",
  "group": "Control flow & functions",
  "ex": "f <- function() invisible(5)\nf()\nprint(f())",
  "out": "[1] 5",
  "lesson": "r-functions"
 },
 {
  "name": "nargs",
  "sig": "nargs()",
  "desc": "Number of arguments supplied.",
  "group": "Control flow & functions",
  "ex": "f <- function(...) nargs()\nf(1, 2, 3)",
  "out": "[1] 3",
  "lesson": "r-functions"
 },
 {
  "name": "Sys.time",
  "sig": "Sys.time()",
  "desc": "The current time.",
  "group": "Control flow & functions",
  "ex": "class(Sys.time())",
  "out": "[1] \"POSIXct\" \"POSIXt\"",
  "lesson": "r-dataframes"
 },
 {
  "name": "system.time",
  "sig": "system.time(expr)",
  "desc": "Time an expression.",
  "group": "Control flow & functions",
  "ex": "class(system.time(sum(1:10)))",
  "out": "[1] \"proc_time\"",
  "lesson": "r-functions"
 },
 {
  "name": "quote",
  "sig": "quote(expr)",
  "desc": "Capture code without running it.",
  "group": "Control flow & functions",
  "ex": "e <- quote(x + 1)\neval(e, list(x = 5))",
  "out": "[1] 6",
  "lesson": "r-functions"
 },
 {
  "name": "substitute",
  "sig": "substitute(arg)",
  "desc": "Capture what the caller wrote.",
  "group": "Control flow & functions",
  "ex": "f <- function(x) deparse(substitute(x))\nf(a + b)",
  "out": "[1] \"a + b\"",
  "lesson": "r-functions"
 },
 {
  "name": "bquote",
  "sig": "bquote(expr)",
  "desc": "Quote with .() splicing.",
  "group": "Control flow & functions",
  "ex": "n <- 10\nbquote(x + .(n))",
  "out": "x + 10",
  "lesson": "r-functions"
 },
 {
  "name": "eval",
  "sig": "eval(expr, envir)",
  "desc": "Run captured code.",
  "group": "Control flow & functions",
  "ex": "eval(parse(text = \"1 + 2\"))",
  "out": "[1] 3",
  "lesson": "r-functions"
 },
 {
  "name": "deparse",
  "sig": "deparse(expr)",
  "desc": "Expression to text.",
  "group": "Control flow & functions",
  "ex": "deparse(quote(a * b))",
  "out": "[1] \"a * b\"",
  "lesson": "r-functions"
 },
 {
  "name": "formals",
  "sig": "formals(f)",
  "desc": "A function's arguments.",
  "group": "Control flow & functions",
  "ex": "names(formals(function(a, b = 2) NULL))",
  "out": "[1] \"a\" \"b\"",
  "lesson": "r-functions"
 },
 {
  "name": "body",
  "sig": "body(f)",
  "desc": "A function's code.",
  "group": "Control flow & functions",
  "ex": "body(function(x) x + 1)",
  "out": "x + 1",
  "lesson": "r-functions"
 },
 {
  "name": "environment",
  "sig": "environment(f)",
  "desc": "Where a function was defined.",
  "group": "Control flow & functions",
  "ex": "f <- function() 1\nclass(environment(f))",
  "out": "[1] \"environment\"",
  "lesson": "r-functions"
 },
 {
  "name": "new.env",
  "sig": "new.env()",
  "desc": "Create an environment (a mutable key-value store).",
  "group": "Control flow & functions",
  "ex": "e <- new.env()\nassign(\"k\", 5, envir = e)\nget(\"k\", envir = e)",
  "out": "[1] 5",
  "lesson": "r-functions"
 },
 {
  "name": "assign",
  "sig": "assign(name, value, envir)",
  "desc": "Set a variable by name.",
  "group": "Control flow & functions",
  "ex": "assign(\"v\", 10)\nv",
  "out": "[1] 10",
  "lesson": "r-functions"
 },
 {
  "name": "get",
  "sig": "get(name, envir)",
  "desc": "Read a variable by name.",
  "group": "Control flow & functions",
  "ex": "val <- 4\nget(\"val\")",
  "out": "[1] 4",
  "lesson": "r-functions"
 },
 {
  "name": "exists",
  "sig": "exists(name)",
  "desc": "Is a name defined?",
  "group": "Control flow & functions",
  "ex": "exists(\"definitely_not_defined_xyz\")",
  "out": "[1] FALSE",
  "lesson": "r-functions"
 },
 {
  "name": "<<-",
  "sig": "x <<- value",
  "desc": "Assign in an enclosing environment (closures).",
  "group": "Control flow & functions",
  "ex": "counter <- function() { n <- 0; function() { n <<- n + 1; n } }\nc1 <- counter()\nc1(); c1()",
  "out": "[1] 1\n[1] 2",
  "lesson": "r-functions"
 },
 {
  "name": "local",
  "sig": "local({ ... })",
  "desc": "Run code in a private scope.",
  "group": "Control flow & functions",
  "ex": "local({ a <- 2; a * 3 })",
  "out": "[1] 6",
  "lesson": "r-functions"
 },
 {
  "name": "Negate",
  "sig": "Negate(f)",
  "desc": "Invert a predicate.",
  "group": "Control flow & functions",
  "ex": "Filter(Negate(is.na), c(1, NA, 3))",
  "out": "[1] 1 3",
  "lesson": "r-iteration"
 },
 {
  "name": "identity",
  "sig": "identity(x)",
  "desc": "Returns its argument.",
  "group": "Control flow & functions",
  "ex": "identity(5)",
  "out": "[1] 5",
  "lesson": "r-iteration"
 },
 {
  "name": "is.function",
  "sig": "is.function(x)",
  "desc": "Is it a function?",
  "group": "Control flow & functions",
  "ex": "is.function(sum)",
  "out": "[1] TRUE",
  "lesson": "r-functions"
 },
 {
  "name": "Sys.getenv",
  "sig": "Sys.getenv(name)",
  "desc": "Read an environment variable.",
  "group": "Control flow & functions",
  "ex": "nchar(Sys.getenv(\"HOME\")) > 0",
  "out": "[1] TRUE",
  "lesson": "r-io"
 },
 {
  "name": "Sys.setenv",
  "sig": "Sys.setenv(NAME = value)",
  "desc": "Set an environment variable.",
  "group": "Control flow & functions",
  "ex": "Sys.setenv(MY_VAR = \"hi\")\nSys.getenv(\"MY_VAR\")",
  "out": "[1] \"hi\"",
  "lesson": "r-io"
 },
 {
  "name": "set.seed",
  "sig": "set.seed(n)",
  "desc": "Make random numbers reproducible.",
  "group": "Control flow & functions",
  "ex": "set.seed(1)\nrunif(2) == { set.seed(1); runif(2) }",
  "out": "[1] TRUE TRUE",
  "lesson": "r-inference"
 },
 {
  "name": "data.frame",
  "sig": "data.frame(..., stringsAsFactors)",
  "desc": "Create a table of equal-length columns.",
  "group": "Data frames & matrices",
  "ex": "data.frame(x = 1:3, y = c(\"a\", \"b\", \"c\"))",
  "out": "  x y\n1 1 a\n2 2 b\n3 3 c",
  "lesson": "r-dataframes"
 },
 {
  "name": "nrow",
  "sig": "nrow(df)",
  "desc": "Number of rows.",
  "group": "Data frames & matrices",
  "ex": "nrow(mtcars)",
  "out": "[1] 32",
  "lesson": "r-dataframes"
 },
 {
  "name": "ncol",
  "sig": "ncol(df)",
  "desc": "Number of columns.",
  "group": "Data frames & matrices",
  "ex": "ncol(mtcars)",
  "out": "[1] 11",
  "lesson": "r-dataframes"
 },
 {
  "name": "dim",
  "sig": "dim(x)",
  "desc": "Rows and columns.",
  "group": "Data frames & matrices",
  "ex": "dim(mtcars)",
  "out": "[1] 32 11",
  "lesson": "r-dataframes"
 },
 {
  "name": "colnames",
  "sig": "colnames(x)",
  "desc": "Column names.",
  "group": "Data frames & matrices",
  "ex": "head(colnames(mtcars), 3)",
  "out": "[1] \"mpg\"  \"cyl\"  \"disp\"",
  "lesson": "r-dataframes"
 },
 {
  "name": "rownames",
  "sig": "rownames(x)",
  "desc": "Row names.",
  "group": "Data frames & matrices",
  "ex": "head(rownames(mtcars), 2)",
  "out": "[1] \"Mazda RX4\"     \"Mazda RX4 Wag\"",
  "lesson": "r-dataframes"
 },
 {
  "name": "str",
  "sig": "str(x)",
  "desc": "Compact structure display.",
  "group": "Data frames & matrices",
  "ex": "str(data.frame(a = 1:2, b = c(\"x\", \"y\")))",
  "out": "'data.frame':\t2 obs. of  2 variables:\n $ a: int  1 2\n $ b: chr  \"x\" \"y\"",
  "lesson": "r-dataframes"
 },
 {
  "name": "subset",
  "sig": "subset(df, cond, select)",
  "desc": "Filter rows and pick columns.",
  "group": "Data frames & matrices",
  "ex": "subset(mtcars, mpg > 30, select = c(mpg, cyl))",
  "out": "                mpg cyl\nFiat 128       32.4   4\nHonda Civic    30.4   4\nToyota Corolla 33.9   4\nLotus Europa   30.4   4",
  "lesson": "r-dataframes"
 },
 {
  "name": "with",
  "sig": "with(data, expr)",
  "desc": "Evaluate using columns as variables.",
  "group": "Data frames & matrices",
  "ex": "with(mtcars, mean(mpg[cyl == 4]))",
  "out": "[1] 26.66364",
  "lesson": "r-dataframes"
 },
 {
  "name": "within",
  "sig": "within(df, { ... })",
  "desc": "Add or change columns.",
  "group": "Data frames & matrices",
  "ex": "head(within(mtcars[1:3, 1:2], kpl <- round(mpg * 0.425, 1)), 2)",
  "out": "              mpg cyl kpl\nMazda RX4      21   6 8.9\nMazda RX4 Wag  21   6 8.9",
  "lesson": "r-dataframes"
 },
 {
  "name": "transform",
  "sig": "transform(df, new = ...)",
  "desc": "Add columns.",
  "group": "Data frames & matrices",
  "ex": "transform(data.frame(a = 1:2), b = a * 10)",
  "out": "  a  b\n1 1 10\n2 2 20",
  "lesson": "r-dataframes"
 },
 {
  "name": "merge",
  "sig": "merge(x, y, by)",
  "desc": "Join two data frames.",
  "group": "Data frames & matrices",
  "ex": "merge(data.frame(id = 1:3, a = c(\"x\", \"y\", \"z\")), data.frame(id = c(1, 3), b = c(TRUE, FALSE)))",
  "out": "  id a     b\n1  1 x  TRUE\n2  3 z FALSE",
  "lesson": "r-dataframes"
 },
 {
  "name": "rbind",
  "sig": "rbind(...)",
  "desc": "Stack rows.",
  "group": "Data frames & matrices",
  "ex": "rbind(data.frame(a = 1, b = \"x\"), data.frame(a = 2, b = \"y\"))",
  "out": "  a b\n1 1 x\n2 2 y",
  "lesson": "r-dataframes"
 },
 {
  "name": "cbind",
  "sig": "cbind(...)",
  "desc": "Bind columns.",
  "group": "Data frames & matrices",
  "ex": "cbind(a = 1:2, b = 3:4)",
  "out": "     a b\n[1,] 1 3\n[2,] 2 4",
  "lesson": "r-dataframes"
 },
 {
  "name": "aggregate",
  "sig": "aggregate(y ~ g, data, FUN)",
  "desc": "Summarise by group.",
  "group": "Data frames & matrices",
  "ex": "aggregate(mpg ~ cyl, data = mtcars, FUN = mean)",
  "out": "  cyl      mpg\n1   4 26.66364\n2   6 19.74286\n3   8 15.10000",
  "lesson": "r-groups"
 },
 {
  "name": "order (sort rows)",
  "sig": "df[order(df$x), ]",
  "desc": "Sort rows by a column.",
  "group": "Data frames & matrices",
  "ex": "head(mtcars[order(-mtcars$mpg), c(\"mpg\", \"cyl\")], 3)",
  "out": "                mpg cyl\nToyota Corolla 33.9   4\nFiat 128       32.4   4\nHonda Civic    30.4   4",
  "lesson": "r-dataframes"
 },
 {
  "name": "complete.cases",
  "sig": "complete.cases(df)",
  "desc": "Rows with no missing values.",
  "group": "Data frames & matrices",
  "ex": "sum(complete.cases(data.frame(a = c(1, NA), b = c(1, 2))))",
  "out": "[1] 1",
  "lesson": "r-dataframes"
 },
 {
  "name": "na.omit",
  "sig": "na.omit(x)",
  "desc": "Drop missing values/rows.",
  "group": "Data frames & matrices",
  "ex": "na.omit(c(1, NA, 3))[1:2]",
  "out": "[1] 1 3",
  "lesson": "r-dataframes"
 },
 {
  "name": "colSums",
  "sig": "colSums(x)",
  "desc": "Column totals.",
  "group": "Data frames & matrices",
  "ex": "colSums(is.na(data.frame(a = c(1, NA), b = c(NA, NA))))",
  "out": "a b \n1 2",
  "lesson": "r-dataframes"
 },
 {
  "name": "expand.grid",
  "sig": "expand.grid(...)",
  "desc": "All combinations as a data frame.",
  "group": "Data frames & matrices",
  "ex": "nrow(expand.grid(a = 1:3, b = c(\"x\", \"y\")))",
  "out": "[1] 6",
  "lesson": "r-dataframes"
 },
 {
  "name": "reshape",
  "sig": "reshape(data, direction, ...)",
  "desc": "Wide to long and back.",
  "group": "Data frames & matrices",
  "ex": "w <- data.frame(id = 1:2, t1 = c(5, 6), t2 = c(7, 8))\nl <- reshape(w, direction = \"long\", varying = c(\"t1\", \"t2\"), v.names = \"val\", timevar = \"time\", idvar = \"id\")\nnrow(l)",
  "out": "[1] 4",
  "lesson": "r-dataframes"
 },
 {
  "name": "unsplit",
  "sig": "unsplit(value, f)",
  "desc": "Reverse of split().",
  "group": "Data frames & matrices",
  "ex": "unsplit(split(1:4, c(1, 2, 1, 2)), c(1, 2, 1, 2))",
  "out": "[1] 1 2 3 4",
  "lesson": "r-groups"
 },
 {
  "name": "matrix",
  "sig": "matrix(data, nrow, ncol, byrow)",
  "desc": "Create a matrix.",
  "group": "Data frames & matrices",
  "ex": "matrix(1:6, nrow = 2, byrow = TRUE)",
  "out": "     [,1] [,2] [,3]\n[1,]    1    2    3\n[2,]    4    5    6",
  "lesson": "r-dataframes"
 },
 {
  "name": "t",
  "sig": "t(m)",
  "desc": "Transpose.",
  "group": "Data frames & matrices",
  "ex": "t(matrix(1:6, 2))",
  "out": "     [,1] [,2]\n[1,]    1    2\n[2,]    3    4\n[3,]    5    6",
  "lesson": "r-dataframes"
 },
 {
  "name": "%*%",
  "sig": "a %*% b",
  "desc": "Matrix multiplication.",
  "group": "Data frames & matrices",
  "ex": "matrix(1:4, 2) %*% matrix(1:4, 2)",
  "out": "     [,1] [,2]\n[1,]    7   15\n[2,]   10   22",
  "lesson": "r-dataframes"
 },
 {
  "name": "solve",
  "sig": "solve(a, b)",
  "desc": "Inverse / solve linear systems.",
  "group": "Data frames & matrices",
  "ex": "solve(matrix(c(2, 0, 0, 2), 2))",
  "out": "     [,1] [,2]\n[1,]  0.5  0.0\n[2,]  0.0  0.5",
  "lesson": "r-dataframes"
 },
 {
  "name": "diag",
  "sig": "diag(x)",
  "desc": "Diagonal / identity matrix.",
  "group": "Data frames & matrices",
  "ex": "diag(2)",
  "out": "     [,1] [,2]\n[1,]    1    0\n[2,]    0    1",
  "lesson": "r-dataframes"
 },
 {
  "name": "det",
  "sig": "det(m)",
  "desc": "Determinant.",
  "group": "Data frames & matrices",
  "ex": "det(matrix(c(1, 2, 3, 4), 2))",
  "out": "[1] -2",
  "lesson": "r-dataframes"
 },
 {
  "name": "crossprod",
  "sig": "crossprod(x)",
  "desc": "t(x) %*% x, faster.",
  "group": "Data frames & matrices",
  "ex": "crossprod(matrix(1:4, 2))",
  "out": "     [,1] [,2]\n[1,]    5   11\n[2,]   11   25",
  "lesson": "r-dataframes"
 },
 {
  "name": "eigen",
  "sig": "eigen(m)",
  "desc": "Eigenvalues and vectors.",
  "group": "Data frames & matrices",
  "ex": "round(eigen(matrix(c(2, 0, 0, 3), 2))$values, 3)",
  "out": "[1] 3 2",
  "lesson": "r-dataframes"
 },
 {
  "name": "sweep",
  "sig": "sweep(x, MARGIN, STATS)",
  "desc": "Subtract/divide by a summary per row or column.",
  "group": "Data frames & matrices",
  "ex": "sweep(matrix(1:6, 2), 2, c(1, 2, 3))",
  "out": "     [,1] [,2] [,3]\n[1,]    0    1    2\n[2,]    1    2    3",
  "lesson": "r-dataframes"
 },
 {
  "name": "dimnames",
  "sig": "dimnames(x)",
  "desc": "Row and column names together.",
  "group": "Data frames & matrices",
  "ex": "m <- matrix(1:4, 2, dimnames = list(c(\"a\", \"b\"), c(\"x\", \"y\")))\ndimnames(m)",
  "out": "[[1]]\n[1] \"a\" \"b\"\n\n[[2]]\n[1] \"x\" \"y\"",
  "lesson": "r-dataframes"
 },
 {
  "name": "row.names",
  "sig": "row.names(df)",
  "desc": "Row names of a data frame.",
  "group": "Data frames & matrices",
  "ex": "row.names(data.frame(x = 1:2))",
  "out": "[1] \"1\" \"2\"",
  "lesson": "r-dataframes"
 },
 {
  "name": "sapply(df)",
  "sig": "sapply(df, class)",
  "desc": "Column types.",
  "group": "Data frames & matrices",
  "ex": "sapply(data.frame(a = 1:2, b = c(\"x\", \"y\")), class)",
  "out": "          a           b \n  \"integer\" \"character\"",
  "lesson": "r-dataframes"
 },
 {
  "name": "Reduce(merge)",
  "sig": "Reduce(function(a, b) merge(a, b, by = \"id\"), list)",
  "desc": "Join many tables.",
  "group": "Data frames & matrices",
  "ex": "ds <- list(data.frame(id = 1:2, a = 3:4), data.frame(id = 1:2, b = 5:6))\nReduce(function(a, b) merge(a, b, by = \"id\"), ds)",
  "out": "  id a b\n1  1 3 5\n2  2 4 6",
  "lesson": "r-dataframes"
 },
 {
  "name": "read.csv",
  "sig": "read.csv(file, text = )",
  "desc": "Read CSV data into a data frame.",
  "group": "Input / output",
  "ex": "read.csv(text = \"a,b\\n1,x\\n2,y\")",
  "out": "  a b\n1 1 x\n2 2 y",
  "lesson": "r-io"
 },
 {
  "name": "write.csv",
  "sig": "write.csv(x, file, row.names)",
  "desc": "Write a data frame as CSV.",
  "group": "Input / output",
  "ex": "write.csv(data.frame(a = 1:2, b = c(\"x\", \"y\")), row.names = FALSE)",
  "out": "\"a\",\"b\"\n1,\"x\"\n2,\"y\"",
  "lesson": "r-io"
 },
 {
  "name": "readLines",
  "sig": "readLines(con)",
  "desc": "Read lines of text.",
  "group": "Input / output",
  "ex": "readLines(textConnection(\"one\\ntwo\"))",
  "out": "[1] \"one\" \"two\"",
  "lesson": "r-io"
 },
 {
  "name": "writeLines",
  "sig": "writeLines(text, con)",
  "desc": "Write lines of text.",
  "group": "Input / output",
  "ex": "writeLines(c(\"a\", \"b\"))",
  "out": "a\nb",
  "lesson": "r-io"
 },
 {
  "name": "cat",
  "sig": "cat(..., sep)",
  "desc": "Print raw text (no quotes, no [1]).",
  "group": "Input / output",
  "ex": "cat(\"x =\", 3, \"\\n\")",
  "out": "x = 3",
  "lesson": "r-hello"
 },
 {
  "name": "print",
  "sig": "print(x)",
  "desc": "Print an object.",
  "group": "Input / output",
  "ex": "print(c(a = 1, b = 2))",
  "out": "a b \n1 2",
  "lesson": "r-hello"
 },
 {
  "name": "textConnection",
  "sig": "textConnection(text)",
  "desc": "Treat a string as a file.",
  "group": "Input / output",
  "ex": "readLines(textConnection(\"a b\"))",
  "out": "[1] \"a b\"",
  "lesson": "r-io"
 },
 {
  "name": "tempfile",
  "sig": "tempfile()",
  "desc": "A temporary file path.",
  "group": "Input / output",
  "ex": "is.character(tempfile())",
  "out": "[1] TRUE",
  "lesson": "r-io"
 },
 {
  "name": "file.exists",
  "sig": "file.exists(path)",
  "desc": "Does the file exist?",
  "group": "Input / output",
  "ex": "file.exists(\"/definitely/not/here\")",
  "out": "[1] FALSE",
  "lesson": "r-io"
 },
 {
  "name": "saveRDS",
  "sig": "saveRDS(obj, file) / readRDS(file)",
  "desc": "Save and load any R object.",
  "group": "Input / output",
  "ex": "f <- tempfile()\nsaveRDS(list(a = 1), f)\nreadRDS(f)$a",
  "out": "[1] 1",
  "lesson": "r-io"
 },
 {
  "name": "dput",
  "sig": "dput(x)",
  "desc": "Print R code that recreates x.",
  "group": "Input / output",
  "ex": "dput(list(a = 1:3))",
  "out": "list(a = 1:3)",
  "lesson": "r-io"
 },
 {
  "name": "capture.output",
  "sig": "capture.output(expr)",
  "desc": "Capture printed output as text.",
  "group": "Input / output",
  "ex": "capture.output(print(1:3))",
  "out": "[1] \"[1] 1 2 3\"",
  "lesson": "r-io"
 },
 {
  "name": "scan",
  "sig": "scan(text = , what =)",
  "desc": "Read values from text.",
  "group": "Input / output",
  "ex": "scan(text = \"1 2 3\", quiet = TRUE)",
  "out": "[1] 1 2 3",
  "lesson": "r-io"
 },
 {
  "name": "sink",
  "sig": "sink(file)",
  "desc": "Divert output to a file.",
  "group": "Input / output",
  "ex": "f <- tempfile()\nsink(f)\nprint(\"hidden\")\nsink()\nreadLines(f)",
  "out": "[1] \"[1] \\\"hidden\\\"\"",
  "lesson": "r-io"
 },
 {
  "name": "readline",
  "sig": "readline(prompt)",
  "desc": "Read a line interactively (needs a terminal).",
  "group": "Input / output",
  "ex": "interactive()",
  "out": "[1] FALSE",
  "lesson": "r-io"
 },
 {
  "name": "Sys.Date",
  "sig": "Sys.Date()",
  "desc": "Today's date.",
  "group": "Input / output",
  "ex": "class(Sys.Date())",
  "out": "[1] \"Date\"",
  "lesson": "r-dataframes"
 },
 {
  "name": "file.remove",
  "sig": "file.remove(path)",
  "desc": "Delete a file.",
  "group": "Input / output",
  "ex": "f <- tempfile()\nwriteLines(\"x\", f)\nfile.remove(f)",
  "out": "[1] TRUE",
  "lesson": "r-io"
 },
 {
  "name": "unlink",
  "sig": "unlink(path)",
  "desc": "Delete files or folders.",
  "group": "Input / output",
  "ex": "f <- tempfile()\nwriteLines(\"x\", f)\nunlink(f)\nfile.exists(f)",
  "out": "[1] FALSE",
  "lesson": "r-io"
 },
 {
  "name": "dir.create",
  "sig": "dir.create(path)",
  "desc": "Create a directory.",
  "group": "Input / output",
  "ex": "d <- file.path(tempdir(), \"newdir\")\ndir.create(d)\ndir.exists(d)",
  "out": "[1] TRUE",
  "lesson": "r-io"
 },
 {
  "name": "list.files",
  "sig": "list.files(path)",
  "desc": "Names of files in a folder.",
  "group": "Input / output",
  "ex": "d <- tempfile(); dir.create(d); writeLines(\"a\", file.path(d, \"a.txt\"))\nlist.files(d)",
  "out": "[1] \"a.txt\"",
  "lesson": "r-io"
 },
 {
  "name": "rnorm",
  "sig": "rnorm(n, mean, sd)",
  "desc": "Random normal draws.",
  "group": "Distributions & simulation",
  "ex": "set.seed(1)\nround(rnorm(3), 4)",
  "out": "[1] -0.6265  0.1836 -0.8356",
  "lesson": "r-inference"
 },
 {
  "name": "dnorm",
  "sig": "dnorm(x, mean, sd)",
  "desc": "Normal density.",
  "group": "Distributions & simulation",
  "ex": "round(dnorm(0), 5)",
  "out": "[1] 0.39894",
  "lesson": "r-inference"
 },
 {
  "name": "pnorm",
  "sig": "pnorm(q, mean, sd)",
  "desc": "Normal cumulative probability.",
  "group": "Distributions & simulation",
  "ex": "round(pnorm(1.96), 4)",
  "out": "[1] 0.975",
  "lesson": "r-inference"
 },
 {
  "name": "qnorm",
  "sig": "qnorm(p, mean, sd)",
  "desc": "Normal quantile.",
  "group": "Distributions & simulation",
  "ex": "round(qnorm(0.975), 4)",
  "out": "[1] 1.96",
  "lesson": "r-inference"
 },
 {
  "name": "runif",
  "sig": "runif(n, min, max)",
  "desc": "Uniform random numbers.",
  "group": "Distributions & simulation",
  "ex": "set.seed(2)\nlength(runif(5))",
  "out": "[1] 5",
  "lesson": "r-inference"
 },
 {
  "name": "dbinom",
  "sig": "dbinom(x, size, prob)",
  "desc": "Binomial probability mass.",
  "group": "Distributions & simulation",
  "ex": "dbinom(3, 10, 0.5)",
  "out": "[1] 0.1171875",
  "lesson": "r-inference"
 },
 {
  "name": "pbinom",
  "sig": "pbinom(q, size, prob)",
  "desc": "Binomial cumulative probability.",
  "group": "Distributions & simulation",
  "ex": "pbinom(3, 10, 0.5)",
  "out": "[1] 0.171875",
  "lesson": "r-inference"
 },
 {
  "name": "rbinom",
  "sig": "rbinom(n, size, prob)",
  "desc": "Binomial random draws.",
  "group": "Distributions & simulation",
  "ex": "set.seed(3)\nlength(rbinom(4, 10, 0.5))",
  "out": "[1] 4",
  "lesson": "r-inference"
 },
 {
  "name": "dpois",
  "sig": "dpois(x, lambda)",
  "desc": "Poisson mass.",
  "group": "Distributions & simulation",
  "ex": "round(dpois(2, 3), 4)",
  "out": "[1] 0.224",
  "lesson": "r-inference"
 },
 {
  "name": "ppois",
  "sig": "ppois(q, lambda)",
  "desc": "Poisson cumulative probability.",
  "group": "Distributions & simulation",
  "ex": "round(ppois(2, 3), 4)",
  "out": "[1] 0.4232",
  "lesson": "r-inference"
 },
 {
  "name": "rpois",
  "sig": "rpois(n, lambda)",
  "desc": "Poisson random draws.",
  "group": "Distributions & simulation",
  "ex": "set.seed(4)\nlength(rpois(3, 2))",
  "out": "[1] 3",
  "lesson": "r-inference"
 },
 {
  "name": "dexp",
  "sig": "dexp(x, rate)",
  "desc": "Exponential density.",
  "group": "Distributions & simulation",
  "ex": "round(dexp(1, 2), 4)",
  "out": "[1] 0.2707",
  "lesson": "r-inference"
 },
 {
  "name": "pexp",
  "sig": "pexp(q, rate)",
  "desc": "Exponential cumulative probability.",
  "group": "Distributions & simulation",
  "ex": "round(pexp(1, 2), 4)",
  "out": "[1] 0.8647",
  "lesson": "r-inference"
 },
 {
  "name": "pt",
  "sig": "pt(q, df)",
  "desc": "Student t cumulative probability.",
  "group": "Distributions & simulation",
  "ex": "round(pt(2, 10), 4)",
  "out": "[1] 0.9633",
  "lesson": "r-inference"
 },
 {
  "name": "qt",
  "sig": "qt(p, df)",
  "desc": "Student t quantile.",
  "group": "Distributions & simulation",
  "ex": "round(qt(0.975, 10), 4)",
  "out": "[1] 2.2281",
  "lesson": "r-inference"
 },
 {
  "name": "pchisq",
  "sig": "pchisq(q, df)",
  "desc": "Chi-squared cumulative probability.",
  "group": "Distributions & simulation",
  "ex": "round(pchisq(3.84, 1), 4)",
  "out": "[1] 0.95",
  "lesson": "r-inference"
 },
 {
  "name": "sample",
  "sig": "sample(x, size, replace)",
  "desc": "Random sample from a vector.",
  "group": "Distributions & simulation",
  "ex": "set.seed(42)\nlength(sample(1:6, 10, replace = TRUE))",
  "out": "[1] 10",
  "lesson": "r-inference"
 },
 {
  "name": "replicate",
  "sig": "replicate(n, expr)",
  "desc": "Repeat an experiment.",
  "group": "Distributions & simulation",
  "ex": "set.seed(1)\nlength(replicate(100, mean(rnorm(5))))",
  "out": "[1] 100",
  "lesson": "r-inference"
 },
 {
  "name": "sample.int",
  "sig": "sample.int(n, size)",
  "desc": "Random integers 1..n.",
  "group": "Distributions & simulation",
  "ex": "set.seed(5)\nlength(sample.int(10, 3))",
  "out": "[1] 3",
  "lesson": "r-inference"
 },
 {
  "name": "density",
  "sig": "density(x)",
  "desc": "Kernel density estimate.",
  "group": "Distributions & simulation",
  "ex": "class(density(c(1, 2, 3, 4)))",
  "out": "[1] \"density\"",
  "lesson": "r-inference"
 },
 {
  "name": "ecdf",
  "sig": "ecdf(x)",
  "desc": "Empirical cumulative distribution function.",
  "group": "Distributions & simulation",
  "ex": "e <- ecdf(c(1, 2, 2, 3))\ne(2)",
  "out": "[1] 0.75",
  "lesson": "r-inference"
 },
 {
  "name": "t.test",
  "sig": "t.test(x, y) / t.test(y ~ g, data)",
  "desc": "Student/Welch t-test.",
  "group": "Tests & models",
  "ex": "round(t.test(extra ~ group, data = sleep)$p.value, 4)",
  "out": "[1] 0.0794",
  "lesson": "r-inference"
 },
 {
  "name": "chisq.test",
  "sig": "chisq.test(table)",
  "desc": "Chi-squared test of independence.",
  "group": "Tests & models",
  "ex": "round(suppressWarnings(chisq.test(table(mtcars$cyl, mtcars$am)))$p.value, 4)",
  "out": "[1] 0.0126",
  "lesson": "r-inference"
 },
 {
  "name": "cor.test",
  "sig": "cor.test(x, y)",
  "desc": "Test a correlation.",
  "group": "Tests & models",
  "ex": "round(cor.test(mtcars$mpg, mtcars$wt)$estimate, 4)",
  "out": "    cor \n-0.8677",
  "lesson": "r-inference"
 },
 {
  "name": "prop.test",
  "sig": "prop.test(x, n)",
  "desc": "Test a proportion.",
  "group": "Tests & models",
  "ex": "round(prop.test(45, 100)$p.value, 4)",
  "out": "[1] 0.3681",
  "lesson": "r-inference"
 },
 {
  "name": "wilcox.test",
  "sig": "wilcox.test(x, y)",
  "desc": "Rank-sum test.",
  "group": "Tests & models",
  "ex": "round(suppressWarnings(wilcox.test(mpg ~ am, data = mtcars))$p.value, 5)",
  "out": "[1] 0.00187",
  "lesson": "r-inference"
 },
 {
  "name": "shapiro.test",
  "sig": "shapiro.test(x)",
  "desc": "Normality test.",
  "group": "Tests & models",
  "ex": "round(shapiro.test(mtcars$mpg)$p.value, 4)",
  "out": "[1] 0.1229",
  "lesson": "r-inference"
 },
 {
  "name": "binom.test",
  "sig": "binom.test(x, n, p)",
  "desc": "Exact binomial test.",
  "group": "Tests & models",
  "ex": "round(binom.test(7, 10, 0.5)$p.value, 4)",
  "out": "[1] 0.3438",
  "lesson": "r-inference"
 },
 {
  "name": "fisher.test",
  "sig": "fisher.test(table)",
  "desc": "Fisher's exact test.",
  "group": "Tests & models",
  "ex": "round(fisher.test(matrix(c(3, 1, 1, 3), 2))$p.value, 4)",
  "out": "[1] 0.4857",
  "lesson": "r-inference"
 },
 {
  "name": "var.test",
  "sig": "var.test(x, y)",
  "desc": "Compare two variances.",
  "group": "Tests & models",
  "ex": "round(var.test(extra ~ group, data = sleep)$p.value, 4)",
  "out": "[1] 0.7427",
  "lesson": "r-inference"
 },
 {
  "name": "aov",
  "sig": "aov(y ~ g, data)",
  "desc": "One-way ANOVA.",
  "group": "Tests & models",
  "ex": "round(summary(aov(weight ~ group, data = PlantGrowth))[[1]][[\"F value\"]][1], 4)",
  "out": "[1] 4.8461",
  "lesson": "r-inference"
 },
 {
  "name": "TukeyHSD",
  "sig": "TukeyHSD(aov)",
  "desc": "All pairwise comparisons.",
  "group": "Tests & models",
  "ex": "round(TukeyHSD(aov(weight ~ group, data = PlantGrowth))$group[, \"p adj\"], 4)",
  "out": "trt1-ctrl trt2-ctrl trt2-trt1 \n   0.3909    0.1980    0.0120",
  "lesson": "r-inference"
 },
 {
  "name": "kruskal.test",
  "sig": "kruskal.test(y ~ g, data)",
  "desc": "Rank-based ANOVA.",
  "group": "Tests & models",
  "ex": "round(kruskal.test(weight ~ group, data = PlantGrowth)$p.value, 4)",
  "out": "[1] 0.0184",
  "lesson": "r-inference"
 },
 {
  "name": "p.adjust",
  "sig": "p.adjust(p, method)",
  "desc": "Multiple-testing correction.",
  "group": "Tests & models",
  "ex": "p.adjust(c(0.01, 0.02, 0.04), method = \"bonferroni\")",
  "out": "[1] 0.03 0.06 0.12",
  "lesson": "r-inference"
 },
 {
  "name": "anova",
  "sig": "anova(m1, m2)",
  "desc": "Compare nested models.",
  "group": "Tests & models",
  "ex": "round(anova(lm(mpg ~ wt, mtcars), lm(mpg ~ wt + hp, mtcars))[[\"Pr(>F)\"]][2], 5)",
  "out": "[1] 0.00145",
  "lesson": "r-inference"
 },
 {
  "name": "lm",
  "sig": "lm(y ~ x, data)",
  "desc": "Linear model.",
  "group": "Tests & models",
  "ex": "round(coef(lm(mpg ~ wt, data = mtcars)), 3)",
  "out": "(Intercept)          wt \n     37.285      -5.344",
  "lesson": "r-lm"
 },
 {
  "name": "coef",
  "sig": "coef(model)",
  "desc": "Model coefficients.",
  "group": "Tests & models",
  "ex": "round(coef(lm(mpg ~ wt, data = mtcars))[[\"wt\"]], 3)",
  "out": "[1] -5.344",
  "lesson": "r-lm"
 },
 {
  "name": "predict",
  "sig": "predict(model, newdata)",
  "desc": "Predictions.",
  "group": "Tests & models",
  "ex": "round(unname(predict(lm(mpg ~ wt, data = mtcars), data.frame(wt = 3))), 3)",
  "out": "[1] 21.252",
  "lesson": "r-lm"
 },
 {
  "name": "residuals",
  "sig": "residuals(model)",
  "desc": "Observed minus fitted.",
  "group": "Tests & models",
  "ex": "round(mean(residuals(lm(mpg ~ wt, data = mtcars))), 6)",
  "out": "[1] 0",
  "lesson": "r-lm"
 },
 {
  "name": "fitted",
  "sig": "fitted(model)",
  "desc": "Fitted values.",
  "group": "Tests & models",
  "ex": "length(fitted(lm(mpg ~ wt, data = mtcars)))",
  "out": "[1] 32",
  "lesson": "r-lm"
 },
 {
  "name": "confint",
  "sig": "confint(model)",
  "desc": "Confidence intervals for coefficients.",
  "group": "Tests & models",
  "ex": "round(confint(lm(mpg ~ wt, data = mtcars))[\"wt\", ], 3)",
  "out": " 2.5 % 97.5 % \n-6.486 -4.203",
  "lesson": "r-lm"
 },
 {
  "name": "glm",
  "sig": "glm(y ~ x, family, data)",
  "desc": "Generalised linear model.",
  "group": "Tests & models",
  "ex": "round(coef(glm(am ~ wt, data = mtcars, family = binomial)), 3)",
  "out": "(Intercept)          wt \n     12.040      -4.024",
  "lesson": "r-lm"
 },
 {
  "name": "AIC",
  "sig": "AIC(model)",
  "desc": "Akaike information criterion.",
  "group": "Tests & models",
  "ex": "round(AIC(glm(am ~ wt, data = mtcars, family = binomial)), 3)",
  "out": "[1] 23.176",
  "lesson": "r-lm"
 },
 {
  "name": "deviance",
  "sig": "deviance(model)",
  "desc": "Model deviance.",
  "group": "Tests & models",
  "ex": "round(deviance(glm(am ~ wt, data = mtcars, family = binomial)), 3)",
  "out": "[1] 19.176",
  "lesson": "r-lm"
 },
 {
  "name": "nls",
  "sig": "nls(formula, data, start)",
  "desc": "Nonlinear least squares.",
  "group": "Tests & models",
  "ex": "x <- 1:6\ny <- c(2.7, 3.6, 4.9, 6.7, 9.1, 12.2)\nround(coef(nls(y ~ a * exp(b * x), start = list(a = 1, b = 0.1))), 3)",
  "out": "    a     b \n1.986 0.303",
  "lesson": "r-lm"
 },
 {
  "name": "optim",
  "sig": "optim(par, fn)",
  "desc": "General optimisation.",
  "group": "Tests & models",
  "ex": "round(optim(c(0, 0), function(p) (p[1] - 1)^2 + (p[2] + 2)^2, method = \"BFGS\")$par, 3)",
  "out": "[1]  1 -2",
  "lesson": "r-lm"
 },
 {
  "name": "optimize",
  "sig": "optimize(f, interval)",
  "desc": "One-dimensional minimum.",
  "group": "Tests & models",
  "ex": "round(optimize(function(x) (x - 3)^2, c(0, 10))$minimum, 3)",
  "out": "[1] 3",
  "lesson": "r-lm"
 },
 {
  "name": "uniroot",
  "sig": "uniroot(f, interval)",
  "desc": "Find a root.",
  "group": "Tests & models",
  "ex": "round(uniroot(function(x) x^2 - 2, c(0, 2))$root, 3)",
  "out": "[1] 1.414",
  "lesson": "r-lm"
 },
 {
  "name": "integrate",
  "sig": "integrate(f, lower, upper)",
  "desc": "Numerical integral.",
  "group": "Tests & models",
  "ex": "round(integrate(dnorm, -1.96, 1.96)$value, 4)",
  "out": "[1] 0.95",
  "lesson": "r-lm"
 },
 {
  "name": "D",
  "sig": "D(expr, name)",
  "desc": "Symbolic derivative.",
  "group": "Tests & models",
  "ex": "D(quote(x^2 + 3 * x), \"x\")",
  "out": "2 * x + 3",
  "lesson": "r-lm"
 },
 {
  "name": "model.matrix",
  "sig": "model.matrix(~ g, data)",
  "desc": "The design matrix of a model.",
  "group": "Tests & models",
  "ex": "dim(model.matrix(~ group, data = PlantGrowth))",
  "out": "[1] 30  3",
  "lesson": "r-inference"
 },
 {
  "name": "UseMethod",
  "sig": "UseMethod(\"generic\")",
  "desc": "Dispatch an S3 generic on the class of the first argument.",
  "group": "OOP: S3, S4, Reference classes",
  "ex": "speak <- function(x, ...) UseMethod(\"speak\")\nspeak.dog <- function(x, ...) \"Woof\"\nspeak(structure(list(), class = \"dog\"))",
  "out": "[1] \"Woof\"",
  "lesson": "r-s3"
 },
 {
  "name": "NextMethod",
  "sig": "NextMethod()",
  "desc": "Call the next S3 method up the class chain.",
  "group": "OOP: S3, S4, Reference classes",
  "ex": "hi <- function(x) UseMethod(\"hi\")\nhi.animal <- function(x) \"animal\"\nhi.dog <- function(x) paste(\"dog >\", NextMethod())\nhi(structure(1, class = c(\"dog\", \"animal\")))",
  "out": "[1] \"dog > animal\"",
  "lesson": "r-s3"
 },
 {
  "name": "structure",
  "sig": "structure(.Data, class = )",
  "desc": "Attach attributes (e.g. a class) to an object.",
  "group": "OOP: S3, S4, Reference classes",
  "ex": "class(structure(list(), class = \"thing\"))",
  "out": "[1] \"thing\"",
  "lesson": "r-s3"
 },
 {
  "name": "inherits",
  "sig": "inherits(x, what)",
  "desc": "Is x of the class (or inherits from it)?",
  "group": "OOP: S3, S4, Reference classes",
  "ex": "inherits(structure(1, class = c(\"a\", \"b\")), \"b\")",
  "out": "[1] TRUE",
  "lesson": "r-s3"
 },
 {
  "name": "unclass",
  "sig": "unclass(x)",
  "desc": "Remove the class attribute.",
  "group": "OOP: S3, S4, Reference classes",
  "ex": "unclass(structure(5, class = \"money\"))",
  "out": "[1] 5",
  "lesson": "r-s3"
 },
 {
  "name": "print.myclass",
  "sig": "print.myclass <- function(x, ...)",
  "desc": "Custom printing for your S3 class.",
  "group": "OOP: S3, S4, Reference classes",
  "ex": "print.temp <- function(x, ...) cat(x, \"degrees\\n\")\nprint(structure(21, class = \"temp\"))",
  "out": "21 degrees",
  "lesson": "r-s3"
 },
 {
  "name": "format.myclass",
  "sig": "format.myclass <- function(x, ...)",
  "desc": "Custom format() for your class.",
  "group": "OOP: S3, S4, Reference classes",
  "ex": "format.temp <- function(x, ...) paste0(unclass(x), \"°C\")\nformat(structure(21, class = \"temp\"))",
  "out": "[1] \"21\\302\\260C\"",
  "lesson": "r-s3"
 },
 {
  "name": "Ops.myclass",
  "sig": "Ops.myclass <- function(e1, e2)",
  "desc": "Overload operators for an S3 class.",
  "group": "OOP: S3, S4, Reference classes",
  "ex": "Ops.money <- function(e1, e2) { v <- get(.Generic)(unclass(e1), unclass(e2)); if (.Generic %in% c(\"+\", \"-\")) structure(v, class = \"money\") else v }\nunclass(structure(2, class = \"money\") + structure(3, class = \"money\"))",
  "out": "[1] 5",
  "lesson": "r-s3"
 },
 {
  "name": "methods",
  "sig": "methods(generic)",
  "desc": "List the methods of an S3 generic.",
  "group": "OOP: S3, S4, Reference classes",
  "ex": "head(as.character(methods(class = \"Date\")), 3)",
  "out": "[1] \"+.Date\"    \"-.Date\"    \"Axis.Date\"",
  "lesson": "r-s3"
 },
 {
  "name": "setClass",
  "sig": "setClass(name, representation, contains)",
  "desc": "Define an S4 class.",
  "group": "OOP: S3, S4, Reference classes",
  "ex": "setClass(\"P\", representation(n = \"numeric\"))\nnew(\"P\", n = 3)@n",
  "out": "[1] 3",
  "lesson": "r-s4"
 },
 {
  "name": "new",
  "sig": "new(\"Class\", ...)",
  "desc": "Create an S4 object.",
  "group": "OOP: S3, S4, Reference classes",
  "ex": "setClass(\"Q\", representation(a = \"character\"))\nnew(\"Q\", a = \"x\")@a",
  "out": "[1] \"x\"",
  "lesson": "r-s4"
 },
 {
  "name": "setGeneric",
  "sig": "setGeneric(name, def)",
  "desc": "Declare an S4 generic function.",
  "group": "OOP: S3, S4, Reference classes",
  "ex": "setGeneric(\"area\", function(shape) standardGeneric(\"area\"))",
  "out": "[1] \"area\"",
  "lesson": "r-s4"
 },
 {
  "name": "setMethod",
  "sig": "setMethod(name, signature, def)",
  "desc": "Define an S4 method.",
  "group": "OOP: S3, S4, Reference classes",
  "ex": "setClass(\"Sq\", representation(s = \"numeric\"))\nsetGeneric(\"area\", function(shape) standardGeneric(\"area\"))\nsetMethod(\"area\", \"Sq\", function(shape) shape@s^2)\narea(new(\"Sq\", s = 3))",
  "out": "[1] \"area\"\n[1] 9",
  "lesson": "r-s4"
 },
 {
  "name": "setValidity",
  "sig": "setValidity(class, fn)",
  "desc": "Add validity checking to an S4 class.",
  "group": "OOP: S3, S4, Reference classes",
  "ex": "setClass(\"Pos\", representation(v = \"numeric\"))\nsetValidity(\"Pos\", function(object) if (object@v < 0) \"negative\" else TRUE)\ntryCatch(new(\"Pos\", v = -1), error = function(e) \"invalid\")",
  "out": "Class \"Pos\" [in \".GlobalEnv\"]\n\nSlots:\n              \nName:        v\nClass: numeric\n[1] \"invalid\"",
  "lesson": "r-s4"
 },
 {
  "name": "callNextMethod",
  "sig": "callNextMethod()",
  "desc": "Call the parent S4 method.",
  "group": "OOP: S3, S4, Reference classes",
  "ex": "setClass(\"A\", representation(x = \"numeric\"))\nsetClass(\"B\", contains = \"A\")\nsetGeneric(\"desc\", function(o) standardGeneric(\"desc\"))\nsetMethod(\"desc\", \"A\", function(o) \"A\")\nsetMethod(\"desc\", \"B\", function(o) paste(\"B >\", callNextMethod()))\ndesc(new(\"B\", x = 1))",
  "out": "[1] \"desc\"\n[1] \"B > A\"",
  "lesson": "r-s4"
 },
 {
  "name": "isVirtualClass",
  "sig": "setClass(\"Base\", representation(\"VIRTUAL\"))",
  "desc": "Define an abstract S4 class.",
  "group": "OOP: S3, S4, Reference classes",
  "ex": "setClass(\"Shape\", representation(\"VIRTUAL\"))\nisVirtualClass(\"Shape\")",
  "out": "[1] TRUE",
  "lesson": "r-s4"
 },
 {
  "name": "is",
  "sig": "is(object, \"Class\")",
  "desc": "Is an object of an S4 class (or subclass)?",
  "group": "OOP: S3, S4, Reference classes",
  "ex": "setClass(\"A\", representation(x = \"numeric\"))\nsetClass(\"B\", contains = \"A\")\nis(new(\"B\", x = 1), \"A\")",
  "out": "[1] TRUE",
  "lesson": "r-s4"
 },
 {
  "name": "slotNames",
  "sig": "slotNames(\"Class\")",
  "desc": "The slots of an S4 class.",
  "group": "OOP: S3, S4, Reference classes",
  "ex": "setClass(\"Pt\", representation(x = \"numeric\", y = \"numeric\"))\nslotNames(\"Pt\")",
  "out": "[1] \"x\" \"y\"",
  "lesson": "r-s4"
 },
 {
  "name": "setRefClass",
  "sig": "setRefClass(name, fields, methods)",
  "desc": "Define a Reference (R5) class: mutable objects with methods.",
  "group": "OOP: S3, S4, Reference classes",
  "ex": "Acc <- setRefClass(\"Acc\", fields = list(bal = \"numeric\"), methods = list(add = function(x) { bal <<- bal + x; invisible(.self) }))\na <- Acc$new(bal = 10)\na$add(5)\na$bal",
  "out": "[1] 15",
  "lesson": "r-s4"
 },
 {
  "name": "callSuper",
  "sig": "callSuper(...)",
  "desc": "Call the parent method inside a Reference class.",
  "group": "OOP: S3, S4, Reference classes",
  "ex": "P <- setRefClass(\"P\", fields = list(), methods = list(hi = function() \"P\"))\nC <- setRefClass(\"C\", contains = \"P\", methods = list(hi = function() paste(\"C >\", callSuper())))\nC$new()$hi()",
  "out": "[1] \"C > P\"",
  "lesson": "r-s4"
 }
];
})(typeof window !== 'undefined' ? window : globalThis);
