// [name, signature, description, example (prints), lesson id]
module.exports = {
  'Built-in functions': [
    ['abs', 'abs(x)', 'Absolute value of a number.', 'print(abs(-7.5))', 'py-numbers'],
    ['aiter', 'aiter(async_iterable)', 'Return an asynchronous iterator (used with async for).', 'import asyncio\nasync def gen():\n    yield 1\nasync def main():\n    it = aiter(gen())\n    print(await anext(it))\nasyncio.run(main())', 'py-advanced'],
    ['all', 'all(iterable)', 'True if every element is truthy (True for an empty iterable).', 'print(all([1, 2, 3]), all([1, 0]), all([]))', 'py-loops'],
    ['anext', 'anext(async_iterator)', 'Get the next item from an async iterator (awaitable).', 'import asyncio\nasync def gen():\n    yield "a"\nasync def main():\n    print(await anext(gen()))\nasyncio.run(main())', 'py-advanced'],
    ['any', 'any(iterable)', 'True if at least one element is truthy.', 'print(any([0, 0, 3]), any([]))', 'py-loops'],
    ['ascii', 'ascii(obj)', 'Like repr() but escapes non-ASCII characters.', 'print(ascii("café"))', 'py-strings'],
    ['bin', 'bin(n)', 'Binary string of an integer.', 'print(bin(10))', 'py-numbers'],
    ['bool', 'bool(x)', 'Convert to True/False using truthiness rules.', 'print(bool(0), bool("a"), bool([]))', 'py-conditions'],
    ['breakpoint', 'breakpoint()', 'Drop into the debugger at this line (interactive; not for scripts under test).', 'print("use breakpoint() in a real terminal to debug")', 'py-testing'],
    ['bytearray', 'bytearray(source)', 'A mutable sequence of bytes.', 'b = bytearray(b"abc")\nb[0] = 65\nprint(b)', 'py-files'],
    ['bytes', 'bytes(source)', 'An immutable sequence of bytes.', 'print(bytes([72, 105]), "Hi".encode())', 'py-files'],
    ['callable', 'callable(obj)', 'True if the object can be called like a function.', 'print(callable(len), callable(5))', 'py-functions'],
    ['chr', 'chr(i)', 'Character for a Unicode code point.', 'print(chr(97), chr(8364))', 'py-strings'],
    ['classmethod', '@classmethod', 'Decorator: method receives the class (cls) instead of an instance.', 'class A:\n    @classmethod\n    def make(cls):\n        return cls()\nprint(type(A.make()).__name__)', 'py-properties'],
    ['compile', 'compile(source, filename, mode)', 'Compile source text into a code object.', 'code = compile("1 + 2", "<s>", "eval")\nprint(eval(code))', 'py-advanced'],
    ['complex', 'complex(real, imag)', 'A complex number.', 'print(complex(1, 2) * 2)', 'py-numbers'],
    ['delattr', 'delattr(obj, name)', 'Delete an attribute from an object.', 'class A:\n    x = 1\na = A()\na.y = 2\ndelattr(a, "y")\nprint(hasattr(a, "y"))', 'py-classes'],
    ['dict', 'dict(**kwargs)', 'Create a dictionary.', 'print(dict(a=1, b=2), dict([("x", 1)]))', 'py-dicts'],
    ['dir', 'dir(obj)', 'List the names an object defines.', 'print([n for n in dir("") if n.startswith("up")])', 'py-classes'],
    ['divmod', 'divmod(a, b)', 'Quotient and remainder together.', 'print(divmod(17, 5))', 'py-numbers'],
    ['enumerate', 'enumerate(iterable, start=0)', 'Pair each item with a counter.', 'print(list(enumerate("ab", start=1)))', 'py-loops'],
    ['eval', 'eval(expr)', 'Evaluate a Python expression given as a string.', 'print(eval("2 ** 8"))', 'py-advanced'],
    ['exec', 'exec(code)', 'Execute Python statements given as a string.', 'exec("x = 5\\nprint(x * 2)")', 'py-advanced'],
    ['filter', 'filter(func, iterable)', 'Keep items for which func is true.', 'print(list(filter(lambda n: n % 2, range(8))))', 'py-lambda'],
    ['float', 'float(x)', 'Convert to a floating-point number.', 'print(float("3.5"), float(2))', 'py-numbers'],
    ['format', 'format(value, spec)', 'Format a value with a format spec.', 'print(format(3.14159, ".2f"), format(255, "x"))', 'py-strings'],
    ['frozenset', 'frozenset(iterable)', 'An immutable set.', 'print(frozenset([1, 2, 2, 3]) == frozenset({1, 2, 3}))', 'py-tuples-sets'],
    ['getattr', 'getattr(obj, name, default)', 'Read an attribute by name.', 'class A:\n    x = 5\nprint(getattr(A, "x"), getattr(A, "nope", "default"))', 'py-classes'],
    ['globals', 'globals()', 'Dictionary of the module-level names.', 'y = 3\nprint(globals()["y"])', 'py-scope'],
    ['hasattr', 'hasattr(obj, name)', 'True if the object has that attribute.', 'print(hasattr("abc", "upper"), hasattr(5, "upper"))', 'py-classes'],
    ['hash', 'hash(obj)', 'Integer hash of a hashable object.', 'print(hash(5), hash("a") == hash("a"))', 'py-dicts'],
    ['help', 'help(obj)', 'Show documentation for an object (interactive).', 'print(len.__doc__.splitlines()[0])', 'py-functions'],
    ['hex', 'hex(n)', 'Hexadecimal string of an integer.', 'print(hex(255))', 'py-numbers'],
    ['id', 'id(obj)', 'Identity number of an object (unique while it lives).', 'a = [1]\nb = a\nprint(id(a) == id(b), id(a) == id([1]))', 'py-mutability'],
    ['input', 'input(prompt)', 'Read a line from the user as text.', 'import io, sys\nsys.stdin = io.StringIO("Ada\\n")\nprint("Hi,", input("name? "))', 'py-hello'],
    ['int', 'int(x, base=10)', 'Convert to an integer.', 'print(int("42"), int(3.9), int("ff", 16))', 'py-numbers'],
    ['isinstance', 'isinstance(obj, cls)', 'True if obj is an instance of cls (or a subclass).', 'print(isinstance(5, int), isinstance(True, int), isinstance("a", (int, float)))', 'py-inheritance'],
    ['issubclass', 'issubclass(cls, parent)', 'True if cls inherits from parent.', 'print(issubclass(bool, int), issubclass(int, str))', 'py-inheritance'],
    ['iter', 'iter(iterable)', 'Get an iterator from an iterable.', 'it = iter([1, 2])\nprint(next(it), next(it))', 'py-iteration'],
    ['len', 'len(obj)', 'Number of items.', 'print(len("hello"), len([1, 2, 3]), len({}))', 'py-lists'],
    ['list', 'list(iterable)', 'Create a list.', 'print(list("abc"), list(range(3)))', 'py-lists'],
    ['locals', 'locals()', 'Dictionary of the local names.', 'def f(a):\n    b = 2\n    return sorted(locals())\nprint(f(1))', 'py-scope'],
    ['map', 'map(func, *iterables)', 'Apply func to each item.', 'print(list(map(str.upper, ["a", "b"])), list(map(pow, [2, 3], [3, 2])))', 'py-lambda'],
    ['max', 'max(iterable, key=None, default=...)', 'Largest item.', 'print(max([3, 9, 2]), max(["aa", "b"], key=len))', 'py-lists'],
    ['memoryview', 'memoryview(obj)', 'View over binary data without copying.', 'm = memoryview(b"abc")\nprint(m[0], bytes(m[1:]))', 'py-advanced'],
    ['min', 'min(iterable, key=None, default=...)', 'Smallest item.', 'print(min([3, 9, 2]), min([], default=0))', 'py-lists'],
    ['next', 'next(iterator, default)', 'Next item of an iterator.', 'it = iter("a")\nprint(next(it), next(it, "done"))', 'py-iteration'],
    ['object', 'object()', 'Base class of every class.', 'print(isinstance(5, object), object.__name__)', 'py-inheritance'],
    ['oct', 'oct(n)', 'Octal string of an integer.', 'print(oct(8))', 'py-numbers'],
    ['open', 'open(path, mode="r")', 'Open a file (use with for automatic closing).', 'with open("hello.txt", "w") as f:\n    f.write("hi")\nwith open("hello.txt") as f:\n    print(f.read())', 'py-files'],
    ['ord', 'ord(ch)', 'Code point of a character.', 'print(ord("a"))', 'py-strings'],
    ['pow', 'pow(base, exp, mod=None)', 'Power, optionally modulo.', 'print(pow(2, 10), pow(2, 10, 1000))', 'py-numbers'],
    ['print', 'print(*values, sep=" ", end="\\n")', 'Write values to the output.', 'print("a", "b", sep="-", end="!\\n")', 'py-hello'],
    ['property', '@property', 'Decorator: access a method like an attribute.', 'class C:\n    @property\n    def area(self):\n        return 6\nprint(C().area)', 'py-properties'],
    ['range', 'range(start, stop, step)', 'A lazy sequence of integers.', 'print(list(range(2, 10, 3)), len(range(100)))', 'py-loops'],
    ['repr', 'repr(obj)', 'Developer-friendly text for an object.', 'print(repr("hi"), repr([1, "a"]))', 'py-strings'],
    ['reversed', 'reversed(seq)', 'Iterate in reverse.', 'print(list(reversed([1, 2, 3])))', 'py-lists'],
    ['round', 'round(x, ndigits)', 'Round (ties go to the even number).', 'print(round(2.5), round(3.5), round(3.14159, 2))', 'py-numbers'],
    ['set', 'set(iterable)', 'An unordered collection of unique items.', 'print(sorted(set([3, 1, 3, 2])))', 'py-tuples-sets'],
    ['setattr', 'setattr(obj, name, value)', 'Set an attribute by name.', 'class A: pass\na = A()\nsetattr(a, "x", 9)\nprint(a.x)', 'py-classes'],
    ['slice', 'slice(start, stop, step)', 'A slice object (what a[1:3] builds).', 's = slice(1, 4)\nprint([0, 1, 2, 3, 4][s])', 'py-lists'],
    ['sorted', 'sorted(iterable, key=None, reverse=False)', 'A new sorted list.', 'print(sorted(["b", "A", "c"], key=str.lower, reverse=True))', 'py-lambda'],
    ['staticmethod', '@staticmethod', 'Decorator: method that needs neither self nor cls.', 'class M:\n    @staticmethod\n    def add(a, b):\n        return a + b\nprint(M.add(2, 3))', 'py-properties'],
    ['str', 'str(obj)', 'Convert to text.', 'print(str(12) + "!", str([1, 2]))', 'py-strings'],
    ['sum', 'sum(iterable, start=0)', 'Add up the items.', 'print(sum([1, 2, 3]), sum([[1], [2]], []))', 'py-lists'],
    ['super', 'super()', 'Access the parent class from a subclass.', 'class A:\n    def hi(self):\n        return "A"\nclass B(A):\n    def hi(self):\n        return super().hi() + "B"\nprint(B().hi())', 'py-inheritance'],
    ['tuple', 'tuple(iterable)', 'An immutable sequence.', 'print(tuple([1, 2, 3]), (1,) + (2,))', 'py-tuples-sets'],
    ['type', 'type(obj)', 'The class of an object (or, with 3 args, create a class).', 'print(type(5).__name__, type("a") is str)', 'py-classes'],
    ['vars', 'vars(obj)', 'The __dict__ of an object.', 'class A:\n    def __init__(self):\n        self.x = 1\nprint(vars(A()))', 'py-classes'],
    ['zip', 'zip(*iterables)', 'Pair up items from several iterables.', 'print(list(zip("ab", [1, 2, 3])))', 'py-lambda'],
    ['__import__', '__import__(name)', 'The function behind import (use import instead).', 'print(__import__("math").pi)', 'py-stdlib'],
    ['True', 'True', 'Boolean true (equals 1).', 'print(True + True)', 'py-conditions'],
    ['False', 'False', 'Boolean false (equals 0).', 'print(False == 0)', 'py-conditions'],
    ['None', 'None', 'The "nothing" value; test with is None.', 'x = None\nprint(x is None)', 'py-functions'],
    ['Ellipsis', '... / Ellipsis', 'A placeholder object, often used in slices and stubs.', 'print(... is Ellipsis)', 'py-typing'],
    ['NotImplemented', 'NotImplemented', 'Return from a dunder method to say "I do not handle this operand".', 'class A:\n    def __eq__(self, o):\n        return NotImplemented\nprint(A() == 1)', 'py-polymorphism'],
  ],
  'str methods': [
    ['str.capitalize', 's.capitalize()', 'First letter upper, rest lower.', 'print("hELLO wORLD".capitalize())', 'py-strings'],
    ['str.casefold', 's.casefold()', 'Aggressive lower() for caseless comparison.', 'print("Straße".casefold() == "STRASSE".casefold())', 'py-strings'],
    ['str.center', 's.center(width, fill=" ")', 'Centre in a field.', 'print("[" + "hi".center(6, "*") + "]")', 'py-strings'],
    ['str.count', 's.count(sub)', 'Number of non-overlapping occurrences.', 'print("banana".count("an"))', 'py-strings'],
    ['str.encode', 's.encode(encoding="utf-8")', 'Convert to bytes.', 'print("é".encode())', 'py-files'],
    ['str.endswith', 's.endswith(suffix)', 'True if it ends with the suffix (or a tuple of suffixes).', 'print("a.py".endswith((".py", ".txt")))', 'py-strings'],
    ['str.expandtabs', 's.expandtabs(tabsize=8)', 'Replace tabs with spaces.', 'print("a\\tb".expandtabs(4))', 'py-strings'],
    ['str.find', 's.find(sub)', 'Index of the first match, or -1.', 'print("hello".find("l"), "hello".find("z"))', 'py-strings'],
    ['str.format', 's.format(*args, **kwargs)', 'Fill {} placeholders.', 'print("{} is {:.1f}".format("pi", 3.14159))', 'py-strings'],
    ['str.format_map', 's.format_map(mapping)', 'format() taking a dict.', 'print("{a}-{b}".format_map({"a": 1, "b": 2}))', 'py-strings'],
    ['str.index', 's.index(sub)', 'Like find but raises ValueError when absent.', 'print("hello".index("e"))', 'py-strings'],
    ['str.isalnum', 's.isalnum()', 'Letters and digits only?', 'print("abc123".isalnum(), "a b".isalnum())', 'py-strings'],
    ['str.isalpha', 's.isalpha()', 'Letters only?', 'print("abc".isalpha(), "ab1".isalpha())', 'py-strings'],
    ['str.isascii', 's.isascii()', 'All ASCII characters?', 'print("abc".isascii(), "é".isascii())', 'py-strings'],
    ['str.isdecimal', 's.isdecimal()', 'Decimal digits only?', 'print("123".isdecimal(), "1.5".isdecimal())', 'py-strings'],
    ['str.isdigit', 's.isdigit()', 'Digits only?', 'print("123".isdigit(), "".isdigit())', 'py-strings'],
    ['str.isidentifier', 's.isidentifier()', 'A valid Python name?', 'print("my_var".isidentifier(), "2x".isidentifier())', 'py-strings'],
    ['str.islower', 's.islower()', 'All cased letters lower-case?', 'print("abc".islower(), "Abc".islower())', 'py-strings'],
    ['str.isnumeric', 's.isnumeric()', 'Numeric characters only?', 'print("½".isnumeric(), "x".isnumeric())', 'py-strings'],
    ['str.isprintable', 's.isprintable()', 'No control characters?', 'print("abc".isprintable(), "a\\nb".isprintable())', 'py-strings'],
    ['str.isspace', 's.isspace()', 'Whitespace only?', 'print("  \\t".isspace(), "".isspace())', 'py-strings'],
    ['str.istitle', 's.istitle()', 'Title-cased?', 'print("Hello World".istitle(), "hello".istitle())', 'py-strings'],
    ['str.isupper', 's.isupper()', 'All cased letters upper-case?', 'print("ABC".isupper(), "AbC".isupper())', 'py-strings'],
    ['str.join', 'sep.join(iterable)', 'Glue strings together with a separator.', 'print("-".join(["a", "b", "c"]))', 'py-strings'],
    ['str.ljust', 's.ljust(width, fill=" ")', 'Left-align in a field.', 'print("[" + "ab".ljust(5, ".") + "]")', 'py-strings'],
    ['str.lower', 's.lower()', 'Lower-case copy.', 'print("HeLLo".lower())', 'py-strings'],
    ['str.lstrip', 's.lstrip(chars=None)', 'Remove leading whitespace/characters.', 'print("  hi ".lstrip() + "|", "xxhi".lstrip("x"))', 'py-strings'],
    ['str.maketrans', 'str.maketrans(x, y)', 'Build a translation table for translate().', 'print("hello".translate(str.maketrans("el", "ip")))', 'py-strings'],
    ['str.partition', 's.partition(sep)', 'Split into (before, sep, after) at the first sep.', 'print("a=b=c".partition("="))', 'py-strings'],
    ['str.removeprefix', 's.removeprefix(prefix)', 'Drop a prefix if present.', 'print("test_x".removeprefix("test_"))', 'py-strings'],
    ['str.removesuffix', 's.removesuffix(suffix)', 'Drop a suffix if present.', 'print("file.py".removesuffix(".py"))', 'py-strings'],
    ['str.replace', 's.replace(old, new, count=-1)', 'Replace occurrences.', 'print("a-b-c".replace("-", "+", 1))', 'py-strings'],
    ['str.rfind', 's.rfind(sub)', 'Index of the last match, or -1.', 'print("hello".rfind("l"))', 'py-strings'],
    ['str.rindex', 's.rindex(sub)', 'Last match index; ValueError if absent.', 'print("hello".rindex("l"))', 'py-strings'],
    ['str.rjust', 's.rjust(width, fill=" ")', 'Right-align in a field.', 'print("[" + "7".rjust(3, "0") + "]")', 'py-strings'],
    ['str.rpartition', 's.rpartition(sep)', 'Like partition but at the last sep.', 'print("a=b=c".rpartition("="))', 'py-strings'],
    ['str.rsplit', 's.rsplit(sep, maxsplit)', 'Split from the right.', 'print("a.b.c".rsplit(".", 1))', 'py-strings'],
    ['str.rstrip', 's.rstrip(chars=None)', 'Remove trailing whitespace/characters.', 'print("hi\\n".rstrip() + "|")', 'py-strings'],
    ['str.split', 's.split(sep=None, maxsplit=-1)', 'Split into a list.', 'print("a b  c".split(), "a,b".split(","))', 'py-strings'],
    ['str.splitlines', 's.splitlines()', 'Split on line breaks.', 'print("a\\nb\\r\\nc".splitlines())', 'py-strings'],
    ['str.startswith', 's.startswith(prefix)', 'True if it starts with the prefix.', 'print("hello".startswith("he"))', 'py-strings'],
    ['str.strip', 's.strip(chars=None)', 'Remove whitespace/characters at both ends.', 'print("  hi  ".strip() + "|", "--x--".strip("-"))', 'py-strings'],
    ['str.swapcase', 's.swapcase()', 'Swap upper and lower case.', 'print("Hello".swapcase())', 'py-strings'],
    ['str.title', 's.title()', 'Title Case Every Word.', 'print("hello big world".title())', 'py-strings'],
    ['str.translate', 's.translate(table)', 'Map characters through a table.', 'print("abc".translate({ord("a"): "A"}))', 'py-strings'],
    ['str.upper', 's.upper()', 'Upper-case copy.', 'print("hi".upper())', 'py-strings'],
    ['str.zfill', 's.zfill(width)', 'Pad with leading zeros.', 'print("42".zfill(5), "-7".zfill(4))', 'py-strings'],
  ],
  'list methods': [
    ['list.append', 'a.append(x)', 'Add one item to the end.', 'a = [1]\na.append(2)\nprint(a)', 'py-lists'],
    ['list.clear', 'a.clear()', 'Remove every item.', 'a = [1, 2]\na.clear()\nprint(a)', 'py-lists'],
    ['list.copy', 'a.copy()', 'A shallow copy.', 'a = [1, [2]]\nb = a.copy()\nb[0] = 9\nprint(a, b)', 'py-mutability'],
    ['list.count', 'a.count(x)', 'How many times x appears.', 'print([1, 2, 1, 1].count(1))', 'py-lists'],
    ['list.extend', 'a.extend(iterable)', 'Append every item of an iterable.', 'a = [1]\na.extend([2, 3])\nprint(a)', 'py-lists'],
    ['list.index', 'a.index(x)', 'Position of the first x (ValueError if absent).', 'print(["a", "b"].index("b"))', 'py-lists'],
    ['list.insert', 'a.insert(i, x)', 'Insert x before position i.', 'a = [1, 3]\na.insert(1, 2)\nprint(a)', 'py-lists'],
    ['list.pop', 'a.pop(i=-1)', 'Remove and return an item.', 'a = [1, 2, 3]\nprint(a.pop(), a.pop(0), a)', 'py-lists'],
    ['list.remove', 'a.remove(x)', 'Remove the first x.', 'a = [1, 2, 1]\na.remove(1)\nprint(a)', 'py-lists'],
    ['list.reverse', 'a.reverse()', 'Reverse in place.', 'a = [1, 2, 3]\na.reverse()\nprint(a)', 'py-lists'],
    ['list.sort', 'a.sort(key=None, reverse=False)', 'Sort in place (returns None).', 'a = ["bb", "a", "ccc"]\na.sort(key=len, reverse=True)\nprint(a)', 'py-lambda'],
  ],
  'dict methods': [
    ['dict.clear', 'd.clear()', 'Remove all items.', 'd = {"a": 1}\nd.clear()\nprint(d)', 'py-dicts'],
    ['dict.copy', 'd.copy()', 'A shallow copy.', 'd = {"a": 1}\ne = d.copy()\ne["a"] = 2\nprint(d, e)', 'py-dicts'],
    ['dict.fromkeys', 'dict.fromkeys(keys, value=None)', 'New dict with the same value for every key.', 'print(dict.fromkeys(["a", "b"], 0))', 'py-dicts'],
    ['dict.get', 'd.get(key, default=None)', 'Value for key, or default (no KeyError).', 'd = {"a": 1}\nprint(d.get("a"), d.get("z", 0))', 'py-dicts'],
    ['dict.items', 'd.items()', 'View of (key, value) pairs.', 'print(list({"a": 1, "b": 2}.items()))', 'py-dicts'],
    ['dict.keys', 'd.keys()', 'View of the keys.', 'print(list({"a": 1, "b": 2}.keys()))', 'py-dicts'],
    ['dict.pop', 'd.pop(key, default)', 'Remove and return a value.', 'd = {"a": 1}\nprint(d.pop("a"), d.pop("z", "none"), d)', 'py-dicts'],
    ['dict.popitem', 'd.popitem()', 'Remove and return the last (key, value).', 'd = {"a": 1, "b": 2}\nprint(d.popitem(), d)', 'py-dicts'],
    ['dict.setdefault', 'd.setdefault(key, default)', 'Get a key, inserting the default if missing.', 'd = {}\nd.setdefault("k", []).append(1)\nprint(d)', 'py-dicts'],
    ['dict.update', 'd.update(other)', 'Merge another mapping in.', 'd = {"a": 1}\nd.update({"b": 2}, a=9)\nprint(d)', 'py-dicts'],
    ['dict.values', 'd.values()', 'View of the values.', 'print(sum({"a": 1, "b": 2}.values()))', 'py-dicts'],
  ],
  'set methods': [
    ['set.add', 's.add(x)', 'Add an element.', 's = {1}\ns.add(2)\nprint(sorted(s))', 'py-tuples-sets'],
    ['set.clear', 's.clear()', 'Remove everything.', 's = {1}\ns.clear()\nprint(s)', 'py-tuples-sets'],
    ['set.copy', 's.copy()', 'Shallow copy.', 's = {1, 2}\nt = s.copy()\nt.add(3)\nprint(sorted(s), sorted(t))', 'py-tuples-sets'],
    ['set.difference', 'a.difference(b)  /  a - b', 'Elements in a but not b.', 'print(sorted({1, 2, 3} - {2}))', 'py-tuples-sets'],
    ['set.difference_update', 'a.difference_update(b)', 'Remove b\'s elements from a.', 'a = {1, 2, 3}\na.difference_update({1})\nprint(sorted(a))', 'py-tuples-sets'],
    ['set.discard', 's.discard(x)', 'Remove x if present (no error).', 's = {1}\ns.discard(5)\nprint(s)', 'py-tuples-sets'],
    ['set.intersection', 'a.intersection(b)  /  a & b', 'Elements in both.', 'print(sorted({1, 2, 3} & {2, 3, 4}))', 'py-tuples-sets'],
    ['set.intersection_update', 'a.intersection_update(b)', 'Keep only elements also in b.', 'a = {1, 2, 3}\na.intersection_update({2, 3, 9})\nprint(sorted(a))', 'py-tuples-sets'],
    ['set.isdisjoint', 'a.isdisjoint(b)', 'No elements in common?', 'print({1, 2}.isdisjoint({3}))', 'py-tuples-sets'],
    ['set.issubset', 'a.issubset(b)  /  a <= b', 'Every element of a is in b?', 'print({1}.issubset({1, 2}))', 'py-tuples-sets'],
    ['set.issuperset', 'a.issuperset(b)  /  a >= b', 'a contains every element of b?', 'print({1, 2}.issuperset({1}))', 'py-tuples-sets'],
    ['set.pop', 's.pop()', 'Remove and return an arbitrary element.', 's = {7}\nprint(s.pop(), s)', 'py-tuples-sets'],
    ['set.remove', 's.remove(x)', 'Remove x (KeyError if absent).', 's = {1, 2}\ns.remove(1)\nprint(s)', 'py-tuples-sets'],
    ['set.symmetric_difference', 'a.symmetric_difference(b)  /  a ^ b', 'Elements in exactly one of the two.', 'print(sorted({1, 2} ^ {2, 3}))', 'py-tuples-sets'],
    ['set.union', 'a.union(b)  /  a | b', 'Elements in either.', 'print(sorted({1} | {2}))', 'py-tuples-sets'],
    ['set.update', 's.update(iterable)', 'Add many elements.', 's = {1}\ns.update([2, 3])\nprint(sorted(s))', 'py-tuples-sets'],
  ],
  'tuple methods': [
    ['tuple.count', 't.count(x)', 'How many times x appears.', 'print((1, 2, 1).count(1))', 'py-tuples-sets'],
    ['tuple.index', 't.index(x)', 'Position of x.', 'print(("a", "b").index("b"))', 'py-tuples-sets'],
  ],
  'math': [
    ['math.ceil', 'math.ceil(x)', 'Round up to an integer.', 'import math\nprint(math.ceil(2.1))', 'py-stdlib'],
    ['math.comb', 'math.comb(n, k)', 'Number of ways to choose k of n.', 'import math\nprint(math.comb(5, 2))', 'py-stdlib'],
    ['math.cos', 'math.cos(x)', 'Cosine (radians).', 'import math\nprint(round(math.cos(math.pi), 3))', 'py-stdlib'],
    ['math.degrees', 'math.degrees(x)', 'Radians to degrees.', 'import math\nprint(math.degrees(math.pi))', 'py-stdlib'],
    ['math.e', 'math.e', 'Euler\'s number.', 'import math\nprint(round(math.e, 5))', 'py-stdlib'],
    ['math.exp', 'math.exp(x)', 'e to the power x.', 'import math\nprint(round(math.exp(1), 5))', 'py-stdlib'],
    ['math.factorial', 'math.factorial(n)', 'n!', 'import math\nprint(math.factorial(5))', 'py-stdlib'],
    ['math.floor', 'math.floor(x)', 'Round down to an integer.', 'import math\nprint(math.floor(-2.1))', 'py-stdlib'],
    ['math.gcd', 'math.gcd(a, b)', 'Greatest common divisor.', 'import math\nprint(math.gcd(12, 18))', 'py-stdlib'],
    ['math.hypot', 'math.hypot(*coords)', 'Euclidean distance.', 'import math\nprint(math.hypot(3, 4))', 'py-stdlib'],
    ['math.inf', 'math.inf', 'Positive infinity.', 'import math\nprint(math.inf > 10**100)', 'py-stdlib'],
    ['math.isclose', 'math.isclose(a, b)', 'Are two floats nearly equal?', 'import math\nprint(0.1 + 0.2 == 0.3, math.isclose(0.1 + 0.2, 0.3))', 'py-numbers'],
    ['math.isqrt', 'math.isqrt(n)', 'Integer square root.', 'import math\nprint(math.isqrt(17))', 'py-stdlib'],
    ['math.lcm', 'math.lcm(a, b)', 'Least common multiple.', 'import math\nprint(math.lcm(4, 6))', 'py-stdlib'],
    ['math.log', 'math.log(x, base=e)', 'Logarithm.', 'import math\nprint(math.log(8, 2), math.log(math.e))', 'py-stdlib'],
    ['math.log10', 'math.log10(x)', 'Base-10 logarithm.', 'import math\nprint(math.log10(1000))', 'py-stdlib'],
    ['math.perm', 'math.perm(n, k)', 'Ordered arrangements of k from n.', 'import math\nprint(math.perm(5, 2))', 'py-stdlib'],
    ['math.pi', 'math.pi', 'The constant pi.', 'import math\nprint(round(math.pi, 5))', 'py-stdlib'],
    ['math.radians', 'math.radians(x)', 'Degrees to radians.', 'import math\nprint(round(math.radians(180), 5))', 'py-stdlib'],
    ['math.sin', 'math.sin(x)', 'Sine (radians).', 'import math\nprint(round(math.sin(math.pi / 2), 3))', 'py-stdlib'],
    ['math.sqrt', 'math.sqrt(x)', 'Square root.', 'import math\nprint(math.sqrt(16))', 'py-stdlib'],
    ['math.tan', 'math.tan(x)', 'Tangent (radians).', 'import math\nprint(round(math.tan(math.pi / 4), 3))', 'py-stdlib'],
    ['math.trunc', 'math.trunc(x)', 'Drop the fractional part.', 'import math\nprint(math.trunc(-2.7))', 'py-stdlib'],
  ],
  'random & statistics': [
    ['random.seed', 'random.seed(n)', 'Make random numbers reproducible.', 'import random\nrandom.seed(1)\na = random.random()\nrandom.seed(1)\nprint(a == random.random())', 'py-stdlib'],
    ['random.random', 'random.random()', 'Float in [0, 1).', 'import random\nrandom.seed(3)\nprint(0 <= random.random() < 1)', 'py-stdlib'],
    ['random.randint', 'random.randint(a, b)', 'Integer in [a, b] inclusive.', 'import random\nrandom.seed(3)\nprint(1 <= random.randint(1, 6) <= 6)', 'py-stdlib'],
    ['random.choice', 'random.choice(seq)', 'One random item.', 'import random\nrandom.seed(3)\nprint(random.choice("abc") in "abc")', 'py-stdlib'],
    ['random.choices', 'random.choices(pop, k=n)', 'k items, with replacement.', 'import random\nrandom.seed(3)\nprint(len(random.choices([1, 2], k=5)))', 'py-stdlib'],
    ['random.sample', 'random.sample(pop, k)', 'k distinct items.', 'import random\nrandom.seed(3)\nprint(len(set(random.sample(range(10), 4))))', 'py-stdlib'],
    ['random.shuffle', 'random.shuffle(list)', 'Shuffle a list in place.', 'import random\nrandom.seed(3)\na = [1, 2, 3, 4]\nrandom.shuffle(a)\nprint(sorted(a))', 'py-stdlib'],
    ['random.uniform', 'random.uniform(a, b)', 'Float between a and b.', 'import random\nrandom.seed(3)\nprint(2 <= random.uniform(2, 3) <= 3)', 'py-stdlib'],
    ['statistics.mean', 'statistics.mean(data)', 'Arithmetic mean.', 'import statistics\nprint(statistics.mean([1, 2, 3, 4]))', 'py-stdlib'],
    ['statistics.median', 'statistics.median(data)', 'Middle value.', 'import statistics\nprint(statistics.median([1, 3, 2, 10]))', 'py-stdlib'],
    ['statistics.mode', 'statistics.mode(data)', 'Most common value.', 'import statistics\nprint(statistics.mode([1, 2, 2, 3]))', 'py-stdlib'],
    ['statistics.stdev', 'statistics.stdev(data)', 'Sample standard deviation.', 'import statistics\nprint(round(statistics.stdev([2, 4, 4, 4, 5, 5, 7, 9]), 4))', 'py-stdlib'],
    ['statistics.pstdev', 'statistics.pstdev(data)', 'Population standard deviation.', 'import statistics\nprint(statistics.pstdev([2, 4, 4, 4, 5, 5, 7, 9]))', 'py-stdlib'],
    ['statistics.variance', 'statistics.variance(data)', 'Sample variance.', 'import statistics\nprint(statistics.variance([1, 2, 3, 4]))', 'py-stdlib'],
  ],
  'collections & itertools & functools': [
    ['collections.Counter', 'Counter(iterable)', 'Count occurrences.', 'from collections import Counter\nc = Counter("banana")\nprint(c.most_common(2))', 'py-collections'],
    ['collections.defaultdict', 'defaultdict(factory)', 'A dict with automatic default values.', 'from collections import defaultdict\nd = defaultdict(list)\nd["a"].append(1)\nprint(dict(d))', 'py-collections'],
    ['collections.deque', 'deque(iterable, maxlen)', 'Fast appends/pops at both ends.', 'from collections import deque\nd = deque([1, 2, 3], maxlen=3)\nd.append(4)\nd.appendleft(0)\nprint(list(d))', 'py-datastructs'],
    ['collections.namedtuple', 'namedtuple(name, fields)', 'A tuple with named fields.', 'from collections import namedtuple\nP = namedtuple("P", "x y")\np = P(1, 2)\nprint(p.x, p)', 'py-collections'],
    ['collections.OrderedDict', 'OrderedDict()', 'A dict with order-aware operations (e.g. move_to_end).', 'from collections import OrderedDict\nd = OrderedDict(a=1, b=2)\nd.move_to_end("a")\nprint(list(d))', 'py-collections'],
    ['itertools.chain', 'chain(*iterables)', 'Iterate several iterables as one.', 'from itertools import chain\nprint(list(chain([1], "ab")))', 'py-itertools'],
    ['itertools.combinations', 'combinations(it, r)', 'All r-sized combinations.', 'from itertools import combinations\nprint(list(combinations("abc", 2)))', 'py-itertools'],
    ['itertools.count', 'count(start, step)', 'Endless counter.', 'from itertools import count, islice\nprint(list(islice(count(5, 2), 3)))', 'py-itertools'],
    ['itertools.cycle', 'cycle(iterable)', 'Repeat forever.', 'from itertools import cycle, islice\nprint(list(islice(cycle("ab"), 5)))', 'py-itertools'],
    ['itertools.groupby', 'groupby(it, key)', 'Group consecutive equal keys (sort first).', 'from itertools import groupby\nprint([(k, len(list(g))) for k, g in groupby("aabccc")])', 'py-itertools'],
    ['itertools.islice', 'islice(it, stop)', 'Slice any iterator.', 'from itertools import islice\nprint(list(islice(range(100), 3)))', 'py-itertools'],
    ['itertools.permutations', 'permutations(it, r)', 'All orderings.', 'from itertools import permutations\nprint(len(list(permutations("abc"))))', 'py-itertools'],
    ['itertools.product', 'product(*its)', 'Cartesian product.', 'from itertools import product\nprint(list(product("ab", [1, 2])))', 'py-itertools'],
    ['itertools.accumulate', 'accumulate(it, func)', 'Running totals.', 'from itertools import accumulate\nprint(list(accumulate([1, 2, 3, 4])))', 'py-itertools'],
    ['functools.reduce', 'reduce(func, it, init)', 'Fold a sequence into one value.', 'from functools import reduce\nprint(reduce(lambda a, b: a * b, [1, 2, 3, 4]))', 'py-lambda'],
    ['functools.lru_cache', '@lru_cache(maxsize)', 'Memoise a function\'s results.', 'from functools import lru_cache\n@lru_cache(maxsize=None)\ndef fib(n):\n    return n if n < 2 else fib(n - 1) + fib(n - 2)\nprint(fib(50))', 'py-recursion'],
    ['functools.partial', 'partial(func, *args)', 'Pre-fill some arguments.', 'from functools import partial\ndouble = partial(pow, exp=2)\nprint(double(5))', 'py-lambda'],
    ['functools.wraps', '@wraps(func)', 'Keep a decorated function\'s name and docstring.', 'from functools import wraps\ndef deco(f):\n    @wraps(f)\n    def inner(*a):\n        return f(*a)\n    return inner\n@deco\ndef hi():\n    "doc"\nprint(hi.__name__)', 'py-decorators'],
  ],
  're, json, datetime, pathlib': [
    ['re.findall', 're.findall(pattern, text)', 'All matches as a list.', 'import re\nprint(re.findall(r"\\d+", "a1 b22 c333"))', 'py-regex'],
    ['re.match', 're.match(pattern, text)', 'Match at the start of the text.', 'import re\nm = re.match(r"(\\w+)@(\\w+)", "ada@lab")\nprint(m.groups())', 'py-regex'],
    ['re.search', 're.search(pattern, text)', 'First match anywhere.', 'import re\nprint(re.search(r"\\d+", "ab12cd").group())', 'py-regex'],
    ['re.sub', 're.sub(pattern, repl, text)', 'Replace matches.', 'import re\nprint(re.sub(r"\\s+", " ", "a   b \\n c"))', 'py-regex'],
    ['re.split', 're.split(pattern, text)', 'Split on a pattern.', 'import re\nprint(re.split(r"[,;]\\s*", "a, b;c"))', 'py-regex'],
    ['re.compile', 're.compile(pattern)', 'Pre-compile a pattern for reuse.', 'import re\nr = re.compile(r"^\\d{3}$")\nprint(bool(r.match("123")), bool(r.match("12")))', 'py-regex'],
    ['re.fullmatch', 're.fullmatch(pattern, text)', 'The whole string must match.', 'import re\nprint(bool(re.fullmatch(r"\\d+", "123")), bool(re.fullmatch(r"\\d+", "12a")))', 'py-regex'],
    ['json.dumps', 'json.dumps(obj, indent=None)', 'Python object to a JSON string.', 'import json\nprint(json.dumps({"a": [1, True, None]}))', 'py-files'],
    ['json.loads', 'json.loads(text)', 'JSON string to a Python object.', 'import json\nprint(json.loads(\'{"a": [1, 2]}\')["a"])', 'py-files'],
    ['json.dump', 'json.dump(obj, file)', 'Write JSON to an open file.', 'import json\nwith open("d.json", "w") as f:\n    json.dump({"x": 1}, f)\nprint(open("d.json").read())', 'py-files'],
    ['json.load', 'json.load(file)', 'Read JSON from an open file.', 'import json\nwith open("d2.json", "w") as f:\n    f.write(\'{"x": 2}\')\nprint(json.load(open("d2.json")))', 'py-files'],
    ['datetime.date', 'date(year, month, day)', 'A calendar date.', 'from datetime import date\nd = date(2024, 2, 29)\nprint(d.weekday(), d.isoformat())', 'py-stdlib'],
    ['datetime.timedelta', 'timedelta(days=, hours=...)', 'A span of time.', 'from datetime import date, timedelta\nprint(date(2024, 1, 31) + timedelta(days=30))', 'py-stdlib'],
    ['datetime.datetime', 'datetime(y, m, d, h, mi, s)', 'A date and time.', 'from datetime import datetime\nd = datetime(2024, 5, 17, 13, 45)\nprint(d.strftime("%d %b %Y %H:%M"))', 'py-stdlib'],
    ['datetime.strptime', 'datetime.strptime(text, fmt)', 'Parse text into a datetime.', 'from datetime import datetime\nprint(datetime.strptime("2024-03-09", "%Y-%m-%d").year)', 'py-stdlib'],
    ['pathlib.Path', 'Path(path)', 'Object-oriented file paths.', 'from pathlib import Path\np = Path("a") / "b.txt"\nprint(p.name, p.suffix, p.parent)', 'py-files'],
    ['os.path.join', 'os.path.join(a, b)', 'Join path parts with the right separator.', 'import os\nprint(os.path.join("a", "b", "c.txt"))', 'py-files'],
    ['os.getcwd', 'os.getcwd()', 'Current working directory.', 'import os\nprint(isinstance(os.getcwd(), str))', 'py-files'],
    ['os.listdir', 'os.listdir(path)', 'Names in a directory.', 'import os\nopen("z.txt", "w").close()\nprint("z.txt" in os.listdir("."))', 'py-files'],
    ['sys.argv', 'sys.argv', 'Command-line arguments of the script.', 'import sys\nprint(type(sys.argv).__name__)', 'py-stdlib'],
  ],
  'dunder & classes': [
    ['__init__', 'def __init__(self, ...)', 'Initialiser: runs when an object is created.', 'class P:\n    def __init__(self, n):\n        self.n = n\nprint(P(3).n)', 'py-classes'],
    ['__str__', 'def __str__(self)', 'Text shown by print() / str().', 'class P:\n    def __str__(self):\n        return "P!"\nprint(P())', 'py-polymorphism'],
    ['__repr__', 'def __repr__(self)', 'Unambiguous text for debugging.', 'class P:\n    def __repr__(self):\n        return "P()"\nprint([P()])', 'py-polymorphism'],
    ['__eq__', 'def __eq__(self, other)', 'Defines ==.', 'class P:\n    def __init__(self, n):\n        self.n = n\n    def __eq__(self, o):\n        return self.n == o.n\nprint(P(1) == P(1))', 'py-polymorphism'],
    ['__lt__', 'def __lt__(self, other)', 'Defines < (enables sorting).', 'class P:\n    def __init__(self, n):\n        self.n = n\n    def __lt__(self, o):\n        return self.n < o.n\nprint(sorted([P(2), P(1)])[0].n)', 'py-polymorphism'],
    ['__add__', 'def __add__(self, other)', 'Defines +.', 'class V:\n    def __init__(self, x):\n        self.x = x\n    def __add__(self, o):\n        return V(self.x + o.x)\nprint((V(1) + V(2)).x)', 'py-polymorphism'],
    ['__len__', 'def __len__(self)', 'Defines len(obj).', 'class B:\n    def __len__(self):\n        return 3\nprint(len(B()))', 'py-polymorphism'],
    ['__getitem__', 'def __getitem__(self, key)', 'Defines obj[key] (and iteration fallback).', 'class B:\n    def __getitem__(self, i):\n        return i * 2\nprint(B()[4])', 'py-polymorphism'],
    ['__iter__', 'def __iter__(self)', 'Makes an object iterable.', 'class C:\n    def __iter__(self):\n        yield 1\n        yield 2\nprint(list(C()))', 'py-generators'],
    ['__call__', 'def __call__(self, ...)', 'Makes an instance callable like a function.', 'class Adder:\n    def __init__(self, n):\n        self.n = n\n    def __call__(self, x):\n        return x + self.n\nprint(Adder(5)(1))', 'py-decorators'],
    ['__enter__', 'def __enter__ / __exit__', 'Make an object a context manager.', 'class T:\n    def __enter__(self):\n        print("in")\n        return self\n    def __exit__(self, *a):\n        print("out")\nwith T():\n    print("body")', 'py-context'],
    ['__slots__', '__slots__ = ("a", "b")', 'Restrict attributes to save memory.', 'class P:\n    __slots__ = ("a",)\ntry:\n    P().b = 1\nexcept AttributeError:\n    print("no b")', 'py-advanced'],
    ['dataclasses.dataclass', '@dataclass', 'Auto-generate __init__, __repr__, __eq__.', 'from dataclasses import dataclass\n@dataclass\nclass P:\n    x: int\n    y: int = 0\nprint(P(1), P(1) == P(1))', 'py-dataclasses'],
    ['abc.ABC', 'class Base(ABC)', 'Declare an abstract base class.', 'from abc import ABC, abstractmethod\nclass S(ABC):\n    @abstractmethod\n    def area(self): ...\ntry:\n    S()\nexcept TypeError:\n    print("abstract")', 'py-abc'],
    ['enum.Enum', 'class C(Enum)', 'A set of named constants.', 'from enum import Enum\nclass C(Enum):\n    RED = 1\n    BLUE = 2\nprint(C.RED.name, C(2))', 'py-dataclasses'],
    ['contextlib.contextmanager', '@contextmanager', 'Build a context manager from a generator.', 'from contextlib import contextmanager\n@contextmanager\ndef box():\n    print("open")\n    yield\n    print("close")\nwith box():\n    print("inside")', 'py-context'],
    ['typing.Optional', 'Optional[T]', 'A type hint meaning T or None.', 'from typing import Optional\ndef f(x: Optional[int] = None) -> int:\n    return x or 0\nprint(f(), f.__annotations__["x"])', 'py-typing'],
    ['asyncio.run', 'asyncio.run(coro)', 'Run an async function to completion.', 'import asyncio\nasync def hi():\n    await asyncio.sleep(0)\n    return "done"\nprint(asyncio.run(hi()))', 'py-advanced'],
    ['heapq.heappush', 'heapq.heappush(heap, x)', 'Push onto a min-heap (use with heappop).', 'import heapq\nh = []\nfor n in [5, 1, 3]:\n    heapq.heappush(h, n)\nprint(heapq.heappop(h), heapq.heappop(h))', 'py-datastructs'],
    ['bisect.bisect_left', 'bisect.bisect_left(a, x)', 'Insertion point in a sorted list.', 'import bisect\nprint(bisect.bisect_left([1, 3, 5, 7], 5))', 'py-search-sort'],
  ],
};
