// [name, signature, description, example (auto-prints), lesson id]. Base R only (packages: base, stats, utils, methods).
module.exports = {
  'Vectors': [
    ['c', 'c(...)', 'Combine values into a vector.', 'c(1, 2, 3)', 'r-vectors'],
    ['length', 'length(x)', 'Number of elements.', 'length(c("a", "b", "c"))', 'r-vectors'],
    ['seq', 'seq(from, to, by, length.out)', 'Generate a sequence.', 'seq(0, 1, by = 0.25)', 'r-vectors'],
    ['seq_len', 'seq_len(n)', 'The integers 1..n (safe for n = 0).', 'seq_len(4)', 'r-iteration'],
    ['seq_along', 'seq_along(x)', 'Indices of x.', 'seq_along(c("a", "b"))', 'r-iteration'],
    ['rep', 'rep(x, times, each)', 'Repeat values.', 'rep(c("a", "b"), times = 2, each = 2)', 'r-vectors'],
    ['rev', 'rev(x)', 'Reverse.', 'rev(1:4)', 'r-vectors'],
    ['sort', 'sort(x, decreasing = FALSE)', 'Sorted copy.', 'sort(c(3, 1, 2), decreasing = TRUE)', 'r-vectors'],
    ['order', 'order(..., decreasing = FALSE)', 'Permutation that sorts (use to reorder rows).', 'order(c(30, 10, 20))', 'r-dataframes'],
    ['rank', 'rank(x)', 'Ranks of the values (ties averaged).', 'rank(c(10, 30, 20, 20))', 'r-stats'],
    ['which', 'which(cond)', 'Indices where TRUE.', 'which(c(5, 12, 7, 20) > 6)', 'r-vectors'],
    ['which.max', 'which.max(x)', 'Index of the largest value.', 'which.max(c(3, 9, 2))', 'r-vectors'],
    ['which.min', 'which.min(x)', 'Index of the smallest value.', 'which.min(c(3, 9, 2))', 'r-vectors'],
    ['any', 'any(...)', 'Is at least one TRUE?', 'any(c(1, 5) > 4)', 'r-vectors'],
    ['all', 'all(...)', 'Are all TRUE?', 'all(c(1, 5) > 0)', 'r-vectors'],
    ['ifelse', 'ifelse(test, yes, no)', 'Vectorised if/else.', 'ifelse(c(1, 5, 10) > 4, "big", "small")', 'r-functions'],
    ['unique', 'unique(x)', 'Distinct values.', 'unique(c(1, 2, 2, 3, 1))', 'r-vectors'],
    ['duplicated', 'duplicated(x)', 'TRUE for repeats.', 'duplicated(c("a", "b", "a"))', 'r-dataframes'],
    ['head', 'head(x, n = 6)', 'First n elements/rows.', 'head(letters, 3)', 'r-dataframes'],
    ['tail', 'tail(x, n = 6)', 'Last n elements/rows.', 'tail(letters, 3)', 'r-dataframes'],
    ['append', 'append(x, values, after)', 'Insert values into a vector.', 'append(1:3, 99, after = 1)', 'r-vectors'],
    ['setdiff', 'setdiff(x, y)', 'Elements of x not in y.', 'setdiff(1:5, c(2, 4))', 'r-vectors'],
    ['union', 'union(x, y)', 'All distinct elements.', 'union(c(1, 2), c(2, 3))', 'r-vectors'],
    ['intersect', 'intersect(x, y)', 'Elements in both.', 'intersect(1:5, 4:8)', 'r-vectors'],
    ['%in%', 'x %in% table', 'Membership test.', 'c("a", "z") %in% letters[1:3]', 'r-vectors'],
    ['match', 'match(x, table)', 'Position of each x in table.', 'match(c("b", "z"), c("a", "b"))', 'r-vectors'],
    ['names', 'names(x)', 'Get or set element names.', 'x <- c(a = 1, b = 2)\nnames(x)', 'r-vectors'],
    ['is.na', 'is.na(x)', 'Missing-value test.', 'is.na(c(1, NA, 3))', 'r-stats'],
    ['vector', 'vector(mode, length)', 'Create an empty vector of a type.', 'vector("numeric", 3)', 'r-vectors'],
    ['numeric', 'numeric(n)', 'A zero-filled numeric vector (preallocate!).', 'numeric(3)', 'r-functions'],
    ['character', 'character(n)', 'A vector of empty strings.', 'character(2)', 'r-vectors'],
    ['logical', 'logical(n)', 'A vector of FALSE.', 'logical(2)', 'r-vectors'],
    ['integer', 'integer(n)', 'A zero-filled integer vector.', 'integer(2)', 'r-vectors'],
    ['typeof', 'typeof(x)', 'Internal type.', 'typeof(1L); typeof(1); typeof("a")', 'r-vectors'],
    ['class', 'class(x)', 'The class(es) of an object.', 'class(1:2); class(mtcars)', 'r-s3'],
    ['is.numeric', 'is.numeric(x)', 'Test for numeric.', 'is.numeric(1L); is.numeric("1")', 'r-vectors'],
    ['as.numeric', 'as.numeric(x)', 'Convert to numeric.', 'as.numeric(c("1.5", "2"))', 'r-vectors'],
    ['as.integer', 'as.integer(x)', 'Convert to integer (truncates).', 'as.integer(3.9)', 'r-vectors'],
    ['as.character', 'as.character(x)', 'Convert to text.', 'as.character(c(1, 2.5))', 'r-vectors'],
    ['as.logical', 'as.logical(x)', 'Convert to TRUE/FALSE.', 'as.logical(c("TRUE", "no", "T"))', 'r-vectors'],
    ['identical', 'identical(x, y)', 'Exactly the same?', 'identical(c(1, 2), c(1, 2))', 'r-vectors'],
    ['all.equal', 'all.equal(x, y)', 'Equal within tolerance (use for floats).', 'isTRUE(all.equal(0.1 + 0.2, 0.3))', 'r-vectors'],
    ['cumsum', 'cumsum(x)', 'Running total.', 'cumsum(1:5)', 'r-stats'],
    ['cumprod', 'cumprod(x)', 'Running product.', 'cumprod(1:5)', 'r-stats'],
    ['cummax', 'cummax(x)', 'Running maximum.', 'cummax(c(1, 3, 2, 5, 4))', 'r-functions'],
    ['cummin', 'cummin(x)', 'Running minimum.', 'cummin(c(5, 3, 4, 1))', 'r-functions'],
    ['diff', 'diff(x, lag = 1)', 'Differences between neighbours.', 'diff(c(1, 4, 9, 16))', 'r-stats'],
    ['outer', 'outer(X, Y, FUN)', 'Apply a function to all pairs.', 'outer(1:3, 1:3)', 'r-functions'],
  ],
  'Math & summary': [
    ['sum', 'sum(..., na.rm = FALSE)', 'Total.', 'sum(1:10)', 'r-stats'],
    ['mean', 'mean(x, na.rm = FALSE)', 'Arithmetic mean.', 'mean(c(1, 2, 3, NA), na.rm = TRUE)', 'r-stats'],
    ['median', 'median(x)', 'Middle value.', 'median(c(1, 3, 2, 100))', 'r-stats'],
    ['var', 'var(x)', 'Sample variance.', 'var(c(1, 2, 3, 4))', 'r-stats'],
    ['sd', 'sd(x)', 'Sample standard deviation.', 'round(sd(c(2, 4, 4, 4, 5, 5, 7, 9)), 4)', 'r-stats'],
    ['min', 'min(...)', 'Smallest value.', 'min(4, 2, 8)', 'r-stats'],
    ['max', 'max(...)', 'Largest value.', 'max(4, 2, 8)', 'r-stats'],
    ['range', 'range(x)', 'Smallest and largest.', 'range(c(5, 1, 9))', 'r-stats'],
    ['pmin', 'pmin(a, b)', 'Element-wise minimum.', 'pmin(c(1, 5), c(3, 2))', 'r-stats'],
    ['pmax', 'pmax(a, b)', 'Element-wise maximum.', 'pmax(c(1, 5), c(3, 2))', 'r-stats'],
    ['quantile', 'quantile(x, probs)', 'Percentiles.', 'quantile(1:9, c(0.25, 0.5, 0.75))', 'r-stats'],
    ['IQR', 'IQR(x)', 'Interquartile range.', 'IQR(1:9)', 'r-stats'],
    ['summary', 'summary(object)', 'Quick summary of a vector, data frame or model.', 'summary(c(1, 2, 3, 4, 100))', 'r-stats'],
    ['fivenum', 'fivenum(x)', 'Tukey five-number summary.', 'fivenum(1:9)', 'r-stats'],
    ['scale', 'scale(x)', 'Centre and scale (z-scores).', 'round(as.vector(scale(c(1, 2, 3))), 3)', 'r-stats'],
    ['cor', 'cor(x, y)', 'Correlation.', 'round(cor(mtcars$mpg, mtcars$wt), 4)', 'r-stats'],
    ['cov', 'cov(x, y)', 'Covariance.', 'cov(1:5, c(2, 4, 6, 8, 10))', 'r-stats'],
    ['table', 'table(x, y)', 'Frequency counts.', 'table(c("a", "b", "a", "c", "a"))', 'r-groups'],
    ['prop.table', 'prop.table(t)', 'Proportions from a table.', 'prop.table(table(c("a", "b", "a", "a")))', 'r-groups'],
    ['tabulate', 'tabulate(bin)', 'Count positive integers fast.', 'tabulate(c(1, 2, 2, 5))', 'r-groups'],
    ['round', 'round(x, digits)', 'Round (half to even).', 'round(c(2.5, 3.5, 3.14159), 2)', 'r-stats'],
    ['signif', 'signif(x, digits)', 'Significant digits.', 'signif(123456, 2)', 'r-stats'],
    ['floor', 'floor(x)', 'Round down.', 'floor(-1.5)', 'r-stats'],
    ['ceiling', 'ceiling(x)', 'Round up.', 'ceiling(1.2)', 'r-stats'],
    ['trunc', 'trunc(x)', 'Drop the fraction.', 'trunc(-2.7)', 'r-stats'],
    ['abs', 'abs(x)', 'Absolute value.', 'abs(c(-2, 3))', 'r-stats'],
    ['sqrt', 'sqrt(x)', 'Square root.', 'sqrt(c(4, 9))', 'r-stats'],
    ['exp', 'exp(x)', 'e^x.', 'round(exp(1), 5)', 'r-stats'],
    ['log', 'log(x, base)', 'Logarithm.', 'log(8, base = 2)', 'r-stats'],
    ['log10', 'log10(x)', 'Base-10 log.', 'log10(1000)', 'r-stats'],
    ['%%', 'x %% y', 'Modulo.', '17 %% 5', 'r-functions'],
    ['%/%', 'x %/% y', 'Integer division.', '17 %/% 5', 'r-functions'],
    ['choose', 'choose(n, k)', 'Binomial coefficient.', 'choose(5, 2)', 'r-inference'],
    ['factorial', 'factorial(n)', 'n!', 'factorial(5)', 'r-inference'],
    ['prod', 'prod(x)', 'Product.', 'prod(1:5)', 'r-stats'],
    ['rowSums', 'rowSums(m)', 'Row totals.', 'rowSums(matrix(1:6, 2))', 'r-dataframes'],
    ['colMeans', 'colMeans(m)', 'Column means.', 'colMeans(matrix(1:6, 2))', 'r-dataframes'],
  ],
  'Strings': [
    ['paste', 'paste(..., sep = " ", collapse)', 'Join with separator (space by default).', 'paste("a", "b", sep = "-")', 'r-strings'],
    ['paste0', 'paste0(...)', 'Join with no separator.', 'paste0("id", 1:3)', 'r-strings'],
    ['nchar', 'nchar(x)', 'Number of characters.', 'nchar(c("a", "abc", ""))', 'r-strings'],
    ['toupper', 'toupper(x)', 'Upper-case.', 'toupper("hi")', 'r-strings'],
    ['tolower', 'tolower(x)', 'Lower-case.', 'tolower("HI")', 'r-strings'],
    ['substr', 'substr(x, start, stop)', 'Extract by position.', 'substr("abcdef", 2, 4)', 'r-strings'],
    ['substring', 'substring(x, first, last)', 'Vectorised substr.', 'substring("abcdef", 1:3, 3:5)', 'r-strings'],
    ['strsplit', 'strsplit(x, split)', 'Split text (returns a list).', 'strsplit("a,b,c", ",")[[1]]', 'r-strings'],
    ['gsub', 'gsub(pattern, repl, x)', 'Replace all matches (regex).', 'gsub("[aeiou]", "_", "education")', 'r-strings'],
    ['sub', 'sub(pattern, repl, x)', 'Replace the first match.', 'sub("a", "A", "banana")', 'r-strings'],
    ['grepl', 'grepl(pattern, x)', 'Does it match? (logical)', 'grepl("^a", c("apple", "banana"))', 'r-strings'],
    ['grep', 'grep(pattern, x, value = FALSE)', 'Indices (or values) of matches.', 'grep("an", c("apple", "banana", "mango"), value = TRUE)', 'r-strings'],
    ['regmatches', 'regmatches(x, m)', 'Extract the matched text.', 'x <- "a1b22c333"\nregmatches(x, gregexpr("[0-9]+", x))[[1]]', 'r-strings'],
    ['regexpr', 'regexpr(pattern, x)', 'Position of the first match.', 'as.integer(regexpr("na", "banana"))', 'r-strings'],
    ['gregexpr', 'gregexpr(pattern, x)', 'Positions of all matches.', 'as.integer(gregexpr("a", "banana")[[1]])', 'r-strings'],
    ['sprintf', 'sprintf(fmt, ...)', 'C-style formatting.', 'sprintf("%s is %.1f%%", "rate", 12.345)', 'r-strings'],
    ['format', 'format(x, nsmall, width, big.mark)', 'Format for display.', 'format(1234567.891, big.mark = ",", nsmall = 2)', 'r-strings'],
    ['formatC', 'formatC(x, width, flag, format)', 'Flexible number formatting.', 'formatC(7, width = 3, flag = "0")', 'r-strings'],
    ['trimws', 'trimws(x)', 'Trim whitespace.', 'trimws("  hi  ")', 'r-strings'],
    ['startsWith', 'startsWith(x, prefix)', 'Prefix test.', 'startsWith(c("apple", "pear"), "ap")', 'r-strings'],
    ['endsWith', 'endsWith(x, suffix)', 'Suffix test.', 'endsWith("file.csv", ".csv")', 'r-strings'],
    ['chartr', 'chartr(old, new, x)', 'Translate characters.', 'chartr("abc", "xyz", "aabbcc")', 'r-strings'],
    ['casefold', 'casefold(x, upper = FALSE)', 'Change case.', 'casefold("Hi", upper = TRUE)', 'r-strings'],
    ['reverse a string', 'paste(rev(strsplit(x, "")[[1]]), collapse = "")', 'Reverse a string.', 'paste(rev(strsplit("stressed", "")[[1]]), collapse = "")', 'r-strings'],
    ['toString', 'toString(x)', 'Collapse to a comma-separated string.', 'toString(1:4)', 'r-strings'],
    ['shQuote', 'shQuote(x)', 'Quote for the shell.', 'shQuote("it works")', 'r-strings'],
    ['sQuote', 'sQuote(x, q = FALSE)', 'Single-quote text.', 'sQuote("x", FALSE)', 'r-strings'],
    ['strtoi', 'strtoi(x, base)', 'Text to integer in a base.', 'strtoi("ff", base = 16L)', 'r-strings'],
    ['letters', 'letters / LETTERS / month.name / pi', 'Built-in character constants.', 'head(letters, 3); month.name[1:2]', 'r-strings'],
    ['basename', 'basename(path)', 'File name part of a path.', 'basename("a/b/c.txt")', 'r-io'],
    ['file.path', 'file.path(...)', 'Build a path.', 'file.path("data", "x.csv")', 'r-io'],
    ['tools::toTitleCase', 'tools::toTitleCase(x)', 'Title Case.', 'tools::toTitleCase("a tale of two cities")', 'r-strings'],
  ],
  'Factors & dates': [
    ['factor', 'factor(x, levels, labels)', 'A categorical variable.', 'factor(c("lo", "hi", "lo"), levels = c("lo", "hi"))', 'r-vectors'],
    ['levels', 'levels(f)', 'The categories.', 'levels(factor(c("b", "a", "b")))', 'r-vectors'],
    ['nlevels', 'nlevels(f)', 'Number of categories.', 'nlevels(factor(c("b", "a", "b")))', 'r-vectors'],
    ['droplevels', 'droplevels(f)', 'Remove unused levels.', 'levels(droplevels(factor(c("a", "b"))[1]))', 'r-vectors'],
    ['cut', 'cut(x, breaks, labels)', 'Bin numbers into categories.', 'cut(c(1, 5, 10), breaks = c(0, 3, 7, 12), labels = c("low", "mid", "high"))', 'r-vectors'],
    ['relevel', 'relevel(f, ref)', 'Change the reference level.', 'levels(relevel(factor(c("a", "b", "c")), ref = "c"))', 'r-vectors'],
    ['as.Date', 'as.Date(x, format)', 'Parse dates.', 'as.Date("2024-03-09") + 30', 'r-dataframes'],
    ['format.Date', 'format(date, "%d %B %Y")', 'Format a date.', 'format(as.Date("2024-03-09"), "%d %B %Y")', 'r-dataframes'],
    ['difftime', 'difftime(a, b, units)', 'Difference between dates/times.', 'difftime(as.Date("2024-03-09"), as.Date("2024-03-01"), units = "days")', 'r-dataframes'],
    ['seq.Date', 'seq(date, by, length.out)', 'A sequence of dates.', 'seq(as.Date("2024-01-31"), by = "month", length.out = 3)', 'r-dataframes'],
    ['weekdays', 'weekdays(date)', 'Day names.', 'weekdays(as.Date("2024-03-09"))', 'r-dataframes'],
    ['months', 'months(date)', 'Month names.', 'months(as.Date("2024-03-09"))', 'r-dataframes'],
    ['ISOdate', 'ISOdate(y, m, d)', 'Build a date-time.', 'format(ISOdate(2024, 3, 9), "%Y-%m-%d")', 'r-dataframes'],
    ['as.POSIXct', 'as.POSIXct(x, tz)', 'Parse date-times.', 'format(as.POSIXct("2024-03-09 13:45:00", tz = "UTC"), "%H:%M")', 'r-dataframes'],
    ['strftime', 'strftime(x, format)', 'Format a time.', 'strftime(as.Date("2024-03-09"), "%A")', 'r-dataframes'],
  ],
  'Lists, apply & functional': [
    ['list', 'list(...)', 'A container for anything.', 'str(list(a = 1, b = "x"))', 'r-vectors'],
    ['unlist', 'unlist(x)', 'Flatten a list into a vector.', 'unlist(list(a = 1, b = list(c = 2, d = 3)))', 'r-vectors'],
    ['lapply', 'lapply(X, FUN)', 'Apply to each element; returns a list.', 'str(lapply(1:2, function(i) i^2))', 'r-iteration'],
    ['sapply', 'sapply(X, FUN)', 'Apply and simplify to a vector.', 'sapply(1:4, function(i) i^2)', 'r-iteration'],
    ['vapply', 'vapply(X, FUN, FUN.VALUE)', 'Like sapply with a checked result type.', 'vapply(c("a", "bb"), nchar, integer(1))', 'r-iteration'],
    ['mapply', 'mapply(FUN, ...)', 'Apply over several vectors at once.', 'mapply(function(a, b) a + b, 1:3, 4:6)', 'r-iteration'],
    ['Map', 'Map(f, ...)', 'Like mapply, always a list.', 'str(Map(function(a, b) a * b, 1:2, 3:4))', 'r-iteration'],
    ['Filter', 'Filter(f, x)', 'Keep elements where f is TRUE.', 'Filter(function(n) n %% 2 == 0, 1:10)', 'r-iteration'],
    ['Reduce', 'Reduce(f, x, accumulate)', 'Fold a vector with a function.', 'Reduce(`+`, 1:5, accumulate = TRUE)', 'r-iteration'],
    ['Position', 'Position(f, x)', 'Index of the first TRUE.', 'Position(function(n) n > 3, c(1, 5, 2, 8))', 'r-iteration'],
    ['Find', 'Find(f, x)', 'First element where f is TRUE.', 'Find(function(n) n > 3, c(1, 5, 2, 8))', 'r-iteration'],
    ['do.call', 'do.call(f, args)', 'Call a function with a list of arguments.', 'do.call(rbind, list(1:2, 3:4))', 'r-functions'],
    ['Recall', 'Recall(...)', 'Call the current function recursively.', '(function(n) if (n <= 1) 1 else n * Recall(n - 1))(5)', 'r-iteration'],
    ['Vectorize', 'Vectorize(f)', 'Make a scalar function work on vectors.', 'f <- Vectorize(function(a, b) if (a > b) a else b)\nf(1:3, c(2, 2, 2))', 'r-functions'],
    ['tapply', 'tapply(X, INDEX, FUN)', 'Apply by group.', 'tapply(c(1, 2, 3, 4), c("a", "b", "a", "b"), sum)', 'r-groups'],
    ['apply', 'apply(X, MARGIN, FUN)', 'Apply over matrix rows (1) or columns (2).', 'apply(matrix(1:6, 2), 1, sum)', 'r-dataframes'],
    ['split', 'split(x, f)', 'Split by group.', 'str(split(1:6, c("a", "b", "a", "b", "a", "b")))', 'r-groups'],
    ['rapply', 'rapply(object, f)', 'Recursively apply to a nested list.', 'unlist(rapply(list(1, list(2, 3)), function(x) x * 10, how = "list"))', 'r-iteration'],
    ['setNames', 'setNames(x, names)', 'Name a vector in one call.', 'setNames(1:3, c("a", "b", "c"))', 'r-vectors'],
    ['stack', 'stack(list)', 'List to long data frame.', 'stack(list(a = 1:2, b = 3))', 'r-dataframes'],
    ['array', 'array(data, dim)', 'N-dimensional array.', 'dim(array(1:24, c(2, 3, 4)))', 'r-dataframes'],
    ['lengths', 'lengths(x)', 'Length of every list element.', 'lengths(list(1:3, "a", NULL))', 'r-vectors'],
  ],
  'Control flow & functions': [
    ['if / else', 'if (cond) a else b', 'Conditional expression.', 'x <- 5\nif (x > 3) "big" else "small"', 'r-functions'],
    ['switch', 'switch(x, a = ..., b = ...)', 'Choose by name or number.', 'switch("b", a = "first", b = "second", "other")', 'r-functions'],
    ['for', 'for (i in x) { ... }', 'Loop over elements.', 'for (i in 1:3) cat(i, "")\ncat("\\n")', 'r-iteration'],
    ['while', 'while (cond) { ... }', 'Loop while TRUE.', 'i <- 1\nwhile (i < 20) i <- i * 2\ni', 'r-iteration'],
    ['repeat', 'repeat { ... break }', 'Loop until break.', 'n <- 0\nrepeat { n <- n + 1; if (n == 4) break }\nn', 'r-functions'],
    ['function', 'function(args) body', 'Define a function.', 'sq <- function(x, p = 2) x^p\nsq(3)', 'r-functions'],
    ['return', 'return(value)', 'Return early.', 'f <- function(x) { if (x < 0) return("neg"); "ok" }\nf(-1)', 'r-functions'],
    ['missing', 'missing(arg)', 'Was the argument supplied?', 'f <- function(a, b) if (missing(b)) "no b" else "b given"\nf(1)', 'r-functions'],
    ['match.arg', 'match.arg(arg)', 'Validate against allowed choices.', 'f <- function(type = c("mean", "median")) match.arg(type)\nf("med")', 'r-functions'],
    ['on.exit', 'on.exit(expr)', 'Run cleanup when the function ends.', 'f <- function() { on.exit(cat("bye\\n")); cat("hi\\n") }\nf()', 'r-functions'],
    ['stopifnot', 'stopifnot(...)', 'Error unless every condition is TRUE.', 'tryCatch(stopifnot(1 == 2), error = function(e) conditionMessage(e))', 'r-errors'],
    ['stop', 'stop(msg)', 'Signal an error.', 'tryCatch(stop("boom"), error = function(e) conditionMessage(e))', 'r-errors'],
    ['warning', 'warning(msg)', 'Signal a warning.', 'withCallingHandlers(warning("careful"), warning = function(w) { cat("caught:", conditionMessage(w), "\\n"); invokeRestart("muffleWarning") })', 'r-errors'],
    ['tryCatch', 'tryCatch(expr, error =, finally =)', 'Handle conditions.', 'tryCatch(log(-1), warning = function(w) "NaN warning", finally = cat("done\\n"))', 'r-errors'],
    ['try', 'try(expr, silent = TRUE)', 'Run and swallow errors.', 'r <- try(stop("x"), silent = TRUE)\nclass(r)', 'r-errors'],
    ['message', 'message(...)', 'Informational message (stderr).', 'suppressMessages(message("hello"))\n"ok"', 'r-errors'],
    ['invisible', 'invisible(x)', 'Return without printing.', 'f <- function() invisible(5)\nf()\nprint(f())', 'r-functions'],
    ['nargs', 'nargs()', 'Number of arguments supplied.', 'f <- function(...) nargs()\nf(1, 2, 3)', 'r-functions'],
    ['Sys.time', 'Sys.time()', 'The current time.', 'class(Sys.time())', 'r-dataframes'],
    ['system.time', 'system.time(expr)', 'Time an expression.', 'class(system.time(sum(1:10)))', 'r-functions'],
    ['quote', 'quote(expr)', 'Capture code without running it.', 'e <- quote(x + 1)\neval(e, list(x = 5))', 'r-functions'],
    ['substitute', 'substitute(arg)', 'Capture what the caller wrote.', 'f <- function(x) deparse(substitute(x))\nf(a + b)', 'r-functions'],
    ['bquote', 'bquote(expr)', 'Quote with .() splicing.', 'n <- 10\nbquote(x + .(n))', 'r-functions'],
    ['eval', 'eval(expr, envir)', 'Run captured code.', 'eval(parse(text = "1 + 2"))', 'r-functions'],
    ['deparse', 'deparse(expr)', 'Expression to text.', 'deparse(quote(a * b))', 'r-functions'],
    ['formals', 'formals(f)', 'A function\'s arguments.', 'names(formals(function(a, b = 2) NULL))', 'r-functions'],
    ['body', 'body(f)', 'A function\'s code.', 'body(function(x) x + 1)', 'r-functions'],
    ['environment', 'environment(f)', 'Where a function was defined.', 'f <- function() 1\nclass(environment(f))', 'r-functions'],
    ['new.env', 'new.env()', 'Create an environment (a mutable key-value store).', 'e <- new.env()\nassign("k", 5, envir = e)\nget("k", envir = e)', 'r-functions'],
    ['assign', 'assign(name, value, envir)', 'Set a variable by name.', 'assign("v", 10)\nv', 'r-functions'],
    ['get', 'get(name, envir)', 'Read a variable by name.', 'val <- 4\nget("val")', 'r-functions'],
    ['exists', 'exists(name)', 'Is a name defined?', 'exists("definitely_not_defined_xyz")', 'r-functions'],
    ['<<-', 'x <<- value', 'Assign in an enclosing environment (closures).', 'counter <- function() { n <- 0; function() { n <<- n + 1; n } }\nc1 <- counter()\nc1(); c1()', 'r-functions'],
    ['local', 'local({ ... })', 'Run code in a private scope.', 'local({ a <- 2; a * 3 })', 'r-functions'],
    ['Negate', 'Negate(f)', 'Invert a predicate.', 'Filter(Negate(is.na), c(1, NA, 3))', 'r-iteration'],
    ['identity', 'identity(x)', 'Returns its argument.', 'identity(5)', 'r-iteration'],
    ['is.function', 'is.function(x)', 'Is it a function?', 'is.function(sum)', 'r-functions'],
    ['Sys.getenv', 'Sys.getenv(name)', 'Read an environment variable.', 'nchar(Sys.getenv("HOME")) > 0', 'r-io'],
    ['Sys.setenv', 'Sys.setenv(NAME = value)', 'Set an environment variable.', 'Sys.setenv(MY_VAR = "hi")\nSys.getenv("MY_VAR")', 'r-io'],
    ['set.seed', 'set.seed(n)', 'Make random numbers reproducible.', 'set.seed(1)\nrunif(2) == { set.seed(1); runif(2) }', 'r-inference'],
  ],
  'Data frames & matrices': [
    ['data.frame', 'data.frame(..., stringsAsFactors)', 'Create a table of equal-length columns.', 'data.frame(x = 1:3, y = c("a", "b", "c"))', 'r-dataframes'],
    ['nrow', 'nrow(df)', 'Number of rows.', 'nrow(mtcars)', 'r-dataframes'],
    ['ncol', 'ncol(df)', 'Number of columns.', 'ncol(mtcars)', 'r-dataframes'],
    ['dim', 'dim(x)', 'Rows and columns.', 'dim(mtcars)', 'r-dataframes'],
    ['colnames', 'colnames(x)', 'Column names.', 'head(colnames(mtcars), 3)', 'r-dataframes'],
    ['rownames', 'rownames(x)', 'Row names.', 'head(rownames(mtcars), 2)', 'r-dataframes'],
    ['str', 'str(x)', 'Compact structure display.', 'str(data.frame(a = 1:2, b = c("x", "y")))', 'r-dataframes'],
    ['subset', 'subset(df, cond, select)', 'Filter rows and pick columns.', 'subset(mtcars, mpg > 30, select = c(mpg, cyl))', 'r-dataframes'],
    ['with', 'with(data, expr)', 'Evaluate using columns as variables.', 'with(mtcars, mean(mpg[cyl == 4]))', 'r-dataframes'],
    ['within', 'within(df, { ... })', 'Add or change columns.', 'head(within(mtcars[1:3, 1:2], kpl <- round(mpg * 0.425, 1)), 2)', 'r-dataframes'],
    ['transform', 'transform(df, new = ...)', 'Add columns.', 'transform(data.frame(a = 1:2), b = a * 10)', 'r-dataframes'],
    ['merge', 'merge(x, y, by)', 'Join two data frames.', 'merge(data.frame(id = 1:3, a = c("x", "y", "z")), data.frame(id = c(1, 3), b = c(TRUE, FALSE)))', 'r-dataframes'],
    ['rbind', 'rbind(...)', 'Stack rows.', 'rbind(data.frame(a = 1, b = "x"), data.frame(a = 2, b = "y"))', 'r-dataframes'],
    ['cbind', 'cbind(...)', 'Bind columns.', 'cbind(a = 1:2, b = 3:4)', 'r-dataframes'],
    ['aggregate', 'aggregate(y ~ g, data, FUN)', 'Summarise by group.', 'aggregate(mpg ~ cyl, data = mtcars, FUN = mean)', 'r-groups'],
    ['order (sort rows)', 'df[order(df$x), ]', 'Sort rows by a column.', 'head(mtcars[order(-mtcars$mpg), c("mpg", "cyl")], 3)', 'r-dataframes'],
    ['complete.cases', 'complete.cases(df)', 'Rows with no missing values.', 'sum(complete.cases(data.frame(a = c(1, NA), b = c(1, 2))))', 'r-dataframes'],
    ['na.omit', 'na.omit(x)', 'Drop missing values/rows.', 'na.omit(c(1, NA, 3))[1:2]', 'r-dataframes'],
    ['colSums', 'colSums(x)', 'Column totals.', 'colSums(is.na(data.frame(a = c(1, NA), b = c(NA, NA))))', 'r-dataframes'],
    ['expand.grid', 'expand.grid(...)', 'All combinations as a data frame.', 'nrow(expand.grid(a = 1:3, b = c("x", "y")))', 'r-dataframes'],
    ['reshape', 'reshape(data, direction, ...)', 'Wide to long and back.', 'w <- data.frame(id = 1:2, t1 = c(5, 6), t2 = c(7, 8))\nl <- reshape(w, direction = "long", varying = c("t1", "t2"), v.names = "val", timevar = "time", idvar = "id")\nnrow(l)', 'r-dataframes'],
    ['unsplit', 'unsplit(value, f)', 'Reverse of split().', 'unsplit(split(1:4, c(1, 2, 1, 2)), c(1, 2, 1, 2))', 'r-groups'],
    ['matrix', 'matrix(data, nrow, ncol, byrow)', 'Create a matrix.', 'matrix(1:6, nrow = 2, byrow = TRUE)', 'r-dataframes'],
    ['t', 't(m)', 'Transpose.', 't(matrix(1:6, 2))', 'r-dataframes'],
    ['%*%', 'a %*% b', 'Matrix multiplication.', 'matrix(1:4, 2) %*% matrix(1:4, 2)', 'r-dataframes'],
    ['solve', 'solve(a, b)', 'Inverse / solve linear systems.', 'solve(matrix(c(2, 0, 0, 2), 2))', 'r-dataframes'],
    ['diag', 'diag(x)', 'Diagonal / identity matrix.', 'diag(2)', 'r-dataframes'],
    ['det', 'det(m)', 'Determinant.', 'det(matrix(c(1, 2, 3, 4), 2))', 'r-dataframes'],
    ['crossprod', 'crossprod(x)', 't(x) %*% x, faster.', 'crossprod(matrix(1:4, 2))', 'r-dataframes'],
    ['eigen', 'eigen(m)', 'Eigenvalues and vectors.', 'round(eigen(matrix(c(2, 0, 0, 3), 2))$values, 3)', 'r-dataframes'],
    ['sweep', 'sweep(x, MARGIN, STATS)', 'Subtract/divide by a summary per row or column.', 'sweep(matrix(1:6, 2), 2, c(1, 2, 3))', 'r-dataframes'],
    ['dimnames', 'dimnames(x)', 'Row and column names together.', 'm <- matrix(1:4, 2, dimnames = list(c("a", "b"), c("x", "y")))\ndimnames(m)', 'r-dataframes'],
    ['row.names', 'row.names(df)', 'Row names of a data frame.', 'row.names(data.frame(x = 1:2))', 'r-dataframes'],
    ['sapply(df)', 'sapply(df, class)', 'Column types.', 'sapply(data.frame(a = 1:2, b = c("x", "y")), class)', 'r-dataframes'],
    ['Reduce(merge)', 'Reduce(function(a, b) merge(a, b, by = "id"), list)', 'Join many tables.', 'ds <- list(data.frame(id = 1:2, a = 3:4), data.frame(id = 1:2, b = 5:6))\nReduce(function(a, b) merge(a, b, by = "id"), ds)', 'r-dataframes'],
  ],
  'Input / output': [
    ['read.csv', 'read.csv(file, text = )', 'Read CSV data into a data frame.', 'read.csv(text = "a,b\\n1,x\\n2,y")', 'r-io'],
    ['write.csv', 'write.csv(x, file, row.names)', 'Write a data frame as CSV.', 'write.csv(data.frame(a = 1:2, b = c("x", "y")), row.names = FALSE)', 'r-io'],
    ['readLines', 'readLines(con)', 'Read lines of text.', 'readLines(textConnection("one\\ntwo"))', 'r-io'],
    ['writeLines', 'writeLines(text, con)', 'Write lines of text.', 'writeLines(c("a", "b"))', 'r-io'],
    ['cat', 'cat(..., sep)', 'Print raw text (no quotes, no [1]).', 'cat("x =", 3, "\\n")', 'r-hello'],
    ['print', 'print(x)', 'Print an object.', 'print(c(a = 1, b = 2))', 'r-hello'],
    ['textConnection', 'textConnection(text)', 'Treat a string as a file.', 'readLines(textConnection("a b"))', 'r-io'],
    ['tempfile', 'tempfile()', 'A temporary file path.', 'is.character(tempfile())', 'r-io'],
    ['file.exists', 'file.exists(path)', 'Does the file exist?', 'file.exists("/definitely/not/here")', 'r-io'],
    ['saveRDS', 'saveRDS(obj, file) / readRDS(file)', 'Save and load any R object.', 'f <- tempfile()\nsaveRDS(list(a = 1), f)\nreadRDS(f)$a', 'r-io'],
    ['dput', 'dput(x)', 'Print R code that recreates x.', 'dput(list(a = 1:3))', 'r-io'],
    ['capture.output', 'capture.output(expr)', 'Capture printed output as text.', 'capture.output(print(1:3))', 'r-io'],
    ['scan', 'scan(text = , what =)', 'Read values from text.', 'scan(text = "1 2 3", quiet = TRUE)', 'r-io'],
    ['sink', 'sink(file)', 'Divert output to a file.', 'f <- tempfile()\nsink(f)\nprint("hidden")\nsink()\nreadLines(f)', 'r-io'],
    ['readline', 'readline(prompt)', 'Read a line interactively (needs a terminal).', 'interactive()', 'r-io'],
    ['Sys.Date', 'Sys.Date()', 'Today\'s date.', 'class(Sys.Date())', 'r-dataframes'],
    ['file.remove', 'file.remove(path)', 'Delete a file.', 'f <- tempfile()\nwriteLines("x", f)\nfile.remove(f)', 'r-io'],
    ['unlink', 'unlink(path)', 'Delete files or folders.', 'f <- tempfile()\nwriteLines("x", f)\nunlink(f)\nfile.exists(f)', 'r-io'],
    ['dir.create', 'dir.create(path)', 'Create a directory.', 'd <- file.path(tempdir(), "newdir")\ndir.create(d)\ndir.exists(d)', 'r-io'],
    ['list.files', 'list.files(path)', 'Names of files in a folder.', 'd <- tempfile(); dir.create(d); writeLines("a", file.path(d, "a.txt"))\nlist.files(d)', 'r-io'],
  ],
  'Distributions & simulation': [
    ['rnorm', 'rnorm(n, mean, sd)', 'Random normal draws.', 'set.seed(1)\nround(rnorm(3), 4)', 'r-inference'],
    ['dnorm', 'dnorm(x, mean, sd)', 'Normal density.', 'round(dnorm(0), 5)', 'r-inference'],
    ['pnorm', 'pnorm(q, mean, sd)', 'Normal cumulative probability.', 'round(pnorm(1.96), 4)', 'r-inference'],
    ['qnorm', 'qnorm(p, mean, sd)', 'Normal quantile.', 'round(qnorm(0.975), 4)', 'r-inference'],
    ['runif', 'runif(n, min, max)', 'Uniform random numbers.', 'set.seed(2)\nlength(runif(5))', 'r-inference'],
    ['dbinom', 'dbinom(x, size, prob)', 'Binomial probability mass.', 'dbinom(3, 10, 0.5)', 'r-inference'],
    ['pbinom', 'pbinom(q, size, prob)', 'Binomial cumulative probability.', 'pbinom(3, 10, 0.5)', 'r-inference'],
    ['rbinom', 'rbinom(n, size, prob)', 'Binomial random draws.', 'set.seed(3)\nlength(rbinom(4, 10, 0.5))', 'r-inference'],
    ['dpois', 'dpois(x, lambda)', 'Poisson mass.', 'round(dpois(2, 3), 4)', 'r-inference'],
    ['ppois', 'ppois(q, lambda)', 'Poisson cumulative probability.', 'round(ppois(2, 3), 4)', 'r-inference'],
    ['rpois', 'rpois(n, lambda)', 'Poisson random draws.', 'set.seed(4)\nlength(rpois(3, 2))', 'r-inference'],
    ['dexp', 'dexp(x, rate)', 'Exponential density.', 'round(dexp(1, 2), 4)', 'r-inference'],
    ['pexp', 'pexp(q, rate)', 'Exponential cumulative probability.', 'round(pexp(1, 2), 4)', 'r-inference'],
    ['pt', 'pt(q, df)', 'Student t cumulative probability.', 'round(pt(2, 10), 4)', 'r-inference'],
    ['qt', 'qt(p, df)', 'Student t quantile.', 'round(qt(0.975, 10), 4)', 'r-inference'],
    ['pchisq', 'pchisq(q, df)', 'Chi-squared cumulative probability.', 'round(pchisq(3.84, 1), 4)', 'r-inference'],
    ['sample', 'sample(x, size, replace)', 'Random sample from a vector.', 'set.seed(42)\nlength(sample(1:6, 10, replace = TRUE))', 'r-inference'],
    ['replicate', 'replicate(n, expr)', 'Repeat an experiment.', 'set.seed(1)\nlength(replicate(100, mean(rnorm(5))))', 'r-inference'],
    ['sample.int', 'sample.int(n, size)', 'Random integers 1..n.', 'set.seed(5)\nlength(sample.int(10, 3))', 'r-inference'],
    ['density', 'density(x)', 'Kernel density estimate.', 'class(density(c(1, 2, 3, 4)))', 'r-inference'],
    ['ecdf', 'ecdf(x)', 'Empirical cumulative distribution function.', 'e <- ecdf(c(1, 2, 2, 3))\ne(2)', 'r-inference'],
  ],
  'Tests & models': [
    ['t.test', 't.test(x, y) / t.test(y ~ g, data)', 'Student/Welch t-test.', 'round(t.test(extra ~ group, data = sleep)$p.value, 4)', 'r-inference'],
    ['chisq.test', 'chisq.test(table)', 'Chi-squared test of independence.', 'round(suppressWarnings(chisq.test(table(mtcars$cyl, mtcars$am)))$p.value, 4)', 'r-inference'],
    ['cor.test', 'cor.test(x, y)', 'Test a correlation.', 'round(cor.test(mtcars$mpg, mtcars$wt)$estimate, 4)', 'r-inference'],
    ['prop.test', 'prop.test(x, n)', 'Test a proportion.', 'round(prop.test(45, 100)$p.value, 4)', 'r-inference'],
    ['wilcox.test', 'wilcox.test(x, y)', 'Rank-sum test.', 'round(suppressWarnings(wilcox.test(mpg ~ am, data = mtcars))$p.value, 5)', 'r-inference'],
    ['shapiro.test', 'shapiro.test(x)', 'Normality test.', 'round(shapiro.test(mtcars$mpg)$p.value, 4)', 'r-inference'],
    ['binom.test', 'binom.test(x, n, p)', 'Exact binomial test.', 'round(binom.test(7, 10, 0.5)$p.value, 4)', 'r-inference'],
    ['fisher.test', 'fisher.test(table)', 'Fisher\'s exact test.', 'round(fisher.test(matrix(c(3, 1, 1, 3), 2))$p.value, 4)', 'r-inference'],
    ['var.test', 'var.test(x, y)', 'Compare two variances.', 'round(var.test(extra ~ group, data = sleep)$p.value, 4)', 'r-inference'],
    ['aov', 'aov(y ~ g, data)', 'One-way ANOVA.', 'round(summary(aov(weight ~ group, data = PlantGrowth))[[1]][["F value"]][1], 4)', 'r-inference'],
    ['TukeyHSD', 'TukeyHSD(aov)', 'All pairwise comparisons.', 'round(TukeyHSD(aov(weight ~ group, data = PlantGrowth))$group[, "p adj"], 4)', 'r-inference'],
    ['kruskal.test', 'kruskal.test(y ~ g, data)', 'Rank-based ANOVA.', 'round(kruskal.test(weight ~ group, data = PlantGrowth)$p.value, 4)', 'r-inference'],
    ['p.adjust', 'p.adjust(p, method)', 'Multiple-testing correction.', 'p.adjust(c(0.01, 0.02, 0.04), method = "bonferroni")', 'r-inference'],
    ['anova', 'anova(m1, m2)', 'Compare nested models.', 'round(anova(lm(mpg ~ wt, mtcars), lm(mpg ~ wt + hp, mtcars))[["Pr(>F)"]][2], 5)', 'r-inference'],
    ['lm', 'lm(y ~ x, data)', 'Linear model.', 'round(coef(lm(mpg ~ wt, data = mtcars)), 3)', 'r-lm'],
    ['coef', 'coef(model)', 'Model coefficients.', 'round(coef(lm(mpg ~ wt, data = mtcars))[["wt"]], 3)', 'r-lm'],
    ['predict', 'predict(model, newdata)', 'Predictions.', 'round(unname(predict(lm(mpg ~ wt, data = mtcars), data.frame(wt = 3))), 3)', 'r-lm'],
    ['residuals', 'residuals(model)', 'Observed minus fitted.', 'round(mean(residuals(lm(mpg ~ wt, data = mtcars))), 6)', 'r-lm'],
    ['fitted', 'fitted(model)', 'Fitted values.', 'length(fitted(lm(mpg ~ wt, data = mtcars)))', 'r-lm'],
    ['confint', 'confint(model)', 'Confidence intervals for coefficients.', 'round(confint(lm(mpg ~ wt, data = mtcars))["wt", ], 3)', 'r-lm'],
    ['glm', 'glm(y ~ x, family, data)', 'Generalised linear model.', 'round(coef(glm(am ~ wt, data = mtcars, family = binomial)), 3)', 'r-lm'],
    ['AIC', 'AIC(model)', 'Akaike information criterion.', 'round(AIC(glm(am ~ wt, data = mtcars, family = binomial)), 3)', 'r-lm'],
    ['deviance', 'deviance(model)', 'Model deviance.', 'round(deviance(glm(am ~ wt, data = mtcars, family = binomial)), 3)', 'r-lm'],
    ['nls', 'nls(formula, data, start)', 'Nonlinear least squares.', 'x <- 1:6\ny <- c(2.7, 3.6, 4.9, 6.7, 9.1, 12.2)\nround(coef(nls(y ~ a * exp(b * x), start = list(a = 1, b = 0.1))), 3)', 'r-lm'],
    ['optim', 'optim(par, fn)', 'General optimisation.', 'round(optim(c(0, 0), function(p) (p[1] - 1)^2 + (p[2] + 2)^2, method = "BFGS")$par, 3)', 'r-lm'],
    ['optimize', 'optimize(f, interval)', 'One-dimensional minimum.', 'round(optimize(function(x) (x - 3)^2, c(0, 10))$minimum, 3)', 'r-lm'],
    ['uniroot', 'uniroot(f, interval)', 'Find a root.', 'round(uniroot(function(x) x^2 - 2, c(0, 2))$root, 3)', 'r-lm'],
    ['integrate', 'integrate(f, lower, upper)', 'Numerical integral.', 'round(integrate(dnorm, -1.96, 1.96)$value, 4)', 'r-lm'],
    ['D', 'D(expr, name)', 'Symbolic derivative.', 'D(quote(x^2 + 3 * x), "x")', 'r-lm'],
    ['model.matrix', 'model.matrix(~ g, data)', 'The design matrix of a model.', 'dim(model.matrix(~ group, data = PlantGrowth))', 'r-inference'],
  ],
  'OOP: S3, S4, Reference classes': [
    ['UseMethod', 'UseMethod("generic")', 'Dispatch an S3 generic on the class of the first argument.', 'speak <- function(x, ...) UseMethod("speak")\nspeak.dog <- function(x, ...) "Woof"\nspeak(structure(list(), class = "dog"))', 'r-s3'],
    ['NextMethod', 'NextMethod()', 'Call the next S3 method up the class chain.', 'hi <- function(x) UseMethod("hi")\nhi.animal <- function(x) "animal"\nhi.dog <- function(x) paste("dog >", NextMethod())\nhi(structure(1, class = c("dog", "animal")))', 'r-s3'],
    ['structure', 'structure(.Data, class = )', 'Attach attributes (e.g. a class) to an object.', 'class(structure(list(), class = "thing"))', 'r-s3'],
    ['inherits', 'inherits(x, what)', 'Is x of the class (or inherits from it)?', 'inherits(structure(1, class = c("a", "b")), "b")', 'r-s3'],
    ['unclass', 'unclass(x)', 'Remove the class attribute.', 'unclass(structure(5, class = "money"))', 'r-s3'],
    ['print.myclass', 'print.myclass <- function(x, ...)', 'Custom printing for your S3 class.', 'print.temp <- function(x, ...) cat(x, "degrees\\n")\nprint(structure(21, class = "temp"))', 'r-s3'],
    ['format.myclass', 'format.myclass <- function(x, ...)', 'Custom format() for your class.', 'format.temp <- function(x, ...) paste0(unclass(x), "°C")\nformat(structure(21, class = "temp"))', 'r-s3'],
    ['Ops.myclass', 'Ops.myclass <- function(e1, e2)', 'Overload operators for an S3 class.', 'Ops.money <- function(e1, e2) { v <- get(.Generic)(unclass(e1), unclass(e2)); if (.Generic %in% c("+", "-")) structure(v, class = "money") else v }\nunclass(structure(2, class = "money") + structure(3, class = "money"))', 'r-s3'],
    ['methods', 'methods(generic)', 'List the methods of an S3 generic.', 'head(as.character(methods(class = "Date")), 3)', 'r-s3'],
    ['setClass', 'setClass(name, representation, contains)', 'Define an S4 class.', 'setClass("P", representation(n = "numeric"))\nnew("P", n = 3)@n', 'r-s4'],
    ['new', 'new("Class", ...)', 'Create an S4 object.', 'setClass("Q", representation(a = "character"))\nnew("Q", a = "x")@a', 'r-s4'],
    ['setGeneric', 'setGeneric(name, def)', 'Declare an S4 generic function.', 'setGeneric("area", function(shape) standardGeneric("area"))', 'r-s4'],
    ['setMethod', 'setMethod(name, signature, def)', 'Define an S4 method.', 'setClass("Sq", representation(s = "numeric"))\nsetGeneric("area", function(shape) standardGeneric("area"))\nsetMethod("area", "Sq", function(shape) shape@s^2)\narea(new("Sq", s = 3))', 'r-s4'],
    ['setValidity', 'setValidity(class, fn)', 'Add validity checking to an S4 class.', 'setClass("Pos", representation(v = "numeric"))\nsetValidity("Pos", function(object) if (object@v < 0) "negative" else TRUE)\ntryCatch(new("Pos", v = -1), error = function(e) "invalid")', 'r-s4'],
    ['callNextMethod', 'callNextMethod()', 'Call the parent S4 method.', 'setClass("A", representation(x = "numeric"))\nsetClass("B", contains = "A")\nsetGeneric("desc", function(o) standardGeneric("desc"))\nsetMethod("desc", "A", function(o) "A")\nsetMethod("desc", "B", function(o) paste("B >", callNextMethod()))\ndesc(new("B", x = 1))', 'r-s4'],
    ['isVirtualClass', 'setClass("Base", representation("VIRTUAL"))', 'Define an abstract S4 class.', 'setClass("Shape", representation("VIRTUAL"))\nisVirtualClass("Shape")', 'r-s4'],
    ['is', 'is(object, "Class")', 'Is an object of an S4 class (or subclass)?', 'setClass("A", representation(x = "numeric"))\nsetClass("B", contains = "A")\nis(new("B", x = 1), "A")', 'r-s4'],
    ['slotNames', 'slotNames("Class")', 'The slots of an S4 class.', 'setClass("Pt", representation(x = "numeric", y = "numeric"))\nslotNames("Pt")', 'r-s4'],
    ['setRefClass', 'setRefClass(name, fields, methods)', 'Define a Reference (R5) class: mutable objects with methods.', 'Acc <- setRefClass("Acc", fields = list(bal = "numeric"), methods = list(add = function(x) { bal <<- bal + x; invisible(.self) }))\na <- Acc$new(bal = 10)\na$add(5)\na$bal', 'r-s4'],
    ['callSuper', 'callSuper(...)', 'Call the parent method inside a Reference class.', 'P <- setRefClass("P", fields = list(), methods = list(hi = function() "P"))\nC <- setRefClass("C", contains = "P", methods = list(hi = function() paste("C >", callSuper())))\nC$new()$hi()', 'r-s4'],
  ],
};
